// Package trainingpeaks provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package trainingpeaks

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AthleteProfileGender.
const (
	Female AthleteProfileGender = "Female"
	Male   AthleteProfileGender = "Male"
	Other  AthleteProfileGender = "Other"
)

// Defines values for ExchangeTokenFormdataBodyGrantType.
const (
	AuthorizationCode ExchangeTokenFormdataBodyGrantType = "authorization_code"
	RefreshToken      ExchangeTokenFormdataBodyGrantType = "refresh_token"
)

// AthleteProfile defines model for AthleteProfile.
type AthleteProfile struct {
	// DateOfBirth Athlete date of birth
	DateOfBirth *openapi_types.Date `json:"DateOfBirth,omitempty"`

	// Email Athlete email address
	Email *openapi_types.Email `json:"Email,omitempty"`

	// FirstName Athlete first name
	FirstName *string `json:"FirstName,omitempty"`

	// Gender Athlete gender
	Gender *AthleteProfileGender `json:"Gender,omitempty"`

	// Id Athlete ID
	Id *string `json:"Id,omitempty"`

	// LastName Athlete last name
	LastName *string `json:"LastName,omitempty"`

	// ThresholdHeartRate Threshold heart rate in BPM
	ThresholdHeartRate *int `json:"ThresholdHeartRate,omitempty"`

	// ThresholdPace Threshold pace
	ThresholdPace *float32 `json:"ThresholdPace,omitempty"`

	// ThresholdPower Functional threshold power in watts
	ThresholdPower *int `json:"ThresholdPower,omitempty"`

	// Weight Athlete weight in kg
	Weight *float32 `json:"Weight,omitempty"`
}

// AthleteProfileGender Athlete gender
type AthleteProfileGender string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken OAuth access token
	AccessToken string `json:"access_token"`

	// AthleteId Athlete ID (may be included in token response)
	AthleteId *string `json:"athlete_id,omitempty"`

	// ExpiresIn Token expiration time in seconds
	ExpiresIn int `json:"expires_in"`

	// RefreshToken OAuth refresh token
	RefreshToken string `json:"refresh_token"`

	// TokenType Token type (usually 'Bearer')
	TokenType *string `json:"token_type,omitempty"`
}

// ExchangeTokenFormdataBody defines parameters for ExchangeToken.
type ExchangeTokenFormdataBody struct {
	// ClientId OAuth client ID
	ClientId string `form:"client_id" json:"client_id"`

	// ClientSecret OAuth client secret
	ClientSecret string `form:"client_secret" json:"client_secret"`

	// Code Authorization code from OAuth callback
	Code string `form:"code" json:"code"`

	// GrantType OAuth grant type
	GrantType ExchangeTokenFormdataBodyGrantType `form:"grant_type" json:"grant_type"`

	// RedirectUri Redirect URI used in authorization request
	RedirectUri string `form:"redirect_uri" json:"redirect_uri"`

	// RefreshToken Refresh token (required when grant_type is refresh_token)
	RefreshToken *string `form:"refresh_token,omitempty" json:"refresh_token,omitempty"`
}

// ExchangeTokenFormdataBodyGrantType defines parameters for ExchangeToken.
type ExchangeTokenFormdataBodyGrantType string

// ExchangeTokenFormdataRequestBody defines body for ExchangeToken for application/x-www-form-urlencoded ContentType.
type ExchangeTokenFormdataRequestBody ExchangeTokenFormdataBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ExchangeTokenWithBody request with any body
	ExchangeTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ExchangeTokenWithFormdataBody(ctx context.Context, body ExchangeTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAthleteProfile request
	GetAthleteProfile(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ExchangeTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExchangeTokenRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExchangeTokenWithFormdataBody(ctx context.Context, body ExchangeTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExchangeTokenRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAthleteProfile(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAthleteProfileRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewExchangeTokenRequestWithFormdataBody calls the generic ExchangeToken builder with application/x-www-form-urlencoded body
func NewExchangeTokenRequestWithFormdataBody(server string, body ExchangeTokenFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewExchangeTokenRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewExchangeTokenRequestWithBody generates requests for ExchangeToken with any type of body
func NewExchangeTokenRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/token")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetAthleteProfileRequest generates requests for GetAthleteProfile
func NewGetAthleteProfileRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/athlete/profile")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ExchangeTokenWithBodyWithResponse request with any body
	ExchangeTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExchangeTokenResponse, error)

	ExchangeTokenWithFormdataBodyWithResponse(ctx context.Context, body ExchangeTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*ExchangeTokenResponse, error)

	// GetAthleteProfileWithResponse request
	GetAthleteProfileWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAthleteProfileResponse, error)
}

type ExchangeTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TokenResponse
}

// Status returns HTTPResponse.Status
func (r ExchangeTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExchangeTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAthleteProfileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AthleteProfile
}

// Status returns HTTPResponse.Status
func (r GetAthleteProfileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAthleteProfileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ExchangeTokenWithBodyWithResponse request with arbitrary body returning *ExchangeTokenResponse
func (c *ClientWithResponses) ExchangeTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExchangeTokenResponse, error) {
	rsp, err := c.ExchangeTokenWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExchangeTokenResponse(rsp)
}

func (c *ClientWithResponses) ExchangeTokenWithFormdataBodyWithResponse(ctx context.Context, body ExchangeTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*ExchangeTokenResponse, error) {
	rsp, err := c.ExchangeTokenWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExchangeTokenResponse(rsp)
}

// GetAthleteProfileWithResponse request returning *GetAthleteProfileResponse
func (c *ClientWithResponses) GetAthleteProfileWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAthleteProfileResponse, error) {
	rsp, err := c.GetAthleteProfile(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAthleteProfileResponse(rsp)
}

// ParseExchangeTokenResponse parses an HTTP response from a ExchangeTokenWithResponse call
func ParseExchangeTokenResponse(rsp *http.Response) (*ExchangeTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExchangeTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetAthleteProfileResponse parses an HTTP response from a GetAthleteProfileWithResponse call
func ParseGetAthleteProfileResponse(rsp *http.Response) (*GetAthleteProfileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAthleteProfileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AthleteProfile
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
