// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: models/activity/standardized.proto

package activity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MuscleGroup int32

const (
	MuscleGroup_MUSCLE_GROUP_UNSPECIFIED MuscleGroup = 0
	MuscleGroup_MUSCLE_GROUP_ABDOMINALS  MuscleGroup = 1
	MuscleGroup_MUSCLE_GROUP_SHOULDERS   MuscleGroup = 2
	MuscleGroup_MUSCLE_GROUP_BICEPS      MuscleGroup = 3
	MuscleGroup_MUSCLE_GROUP_TRICEPS     MuscleGroup = 4
	MuscleGroup_MUSCLE_GROUP_FOREARMS    MuscleGroup = 5
	MuscleGroup_MUSCLE_GROUP_QUADRICEPS  MuscleGroup = 6
	MuscleGroup_MUSCLE_GROUP_HAMSTRINGS  MuscleGroup = 7
	MuscleGroup_MUSCLE_GROUP_CALVES      MuscleGroup = 8
	MuscleGroup_MUSCLE_GROUP_GLUTES      MuscleGroup = 9
	MuscleGroup_MUSCLE_GROUP_ABDUCTORS   MuscleGroup = 10
	MuscleGroup_MUSCLE_GROUP_ADDUCTORS   MuscleGroup = 11
	MuscleGroup_MUSCLE_GROUP_LATS        MuscleGroup = 12
	MuscleGroup_MUSCLE_GROUP_UPPER_BACK  MuscleGroup = 13
	MuscleGroup_MUSCLE_GROUP_TRAPS       MuscleGroup = 14
	MuscleGroup_MUSCLE_GROUP_LOWER_BACK  MuscleGroup = 15
	MuscleGroup_MUSCLE_GROUP_CHEST       MuscleGroup = 16
	MuscleGroup_MUSCLE_GROUP_CARDIO      MuscleGroup = 17
	MuscleGroup_MUSCLE_GROUP_NECK        MuscleGroup = 18
	MuscleGroup_MUSCLE_GROUP_FULL_BODY   MuscleGroup = 19
	MuscleGroup_MUSCLE_GROUP_OTHER       MuscleGroup = 20
)

// Enum value maps for MuscleGroup.
var (
	MuscleGroup_name = map[int32]string{
		0:  "MUSCLE_GROUP_UNSPECIFIED",
		1:  "MUSCLE_GROUP_ABDOMINALS",
		2:  "MUSCLE_GROUP_SHOULDERS",
		3:  "MUSCLE_GROUP_BICEPS",
		4:  "MUSCLE_GROUP_TRICEPS",
		5:  "MUSCLE_GROUP_FOREARMS",
		6:  "MUSCLE_GROUP_QUADRICEPS",
		7:  "MUSCLE_GROUP_HAMSTRINGS",
		8:  "MUSCLE_GROUP_CALVES",
		9:  "MUSCLE_GROUP_GLUTES",
		10: "MUSCLE_GROUP_ABDUCTORS",
		11: "MUSCLE_GROUP_ADDUCTORS",
		12: "MUSCLE_GROUP_LATS",
		13: "MUSCLE_GROUP_UPPER_BACK",
		14: "MUSCLE_GROUP_TRAPS",
		15: "MUSCLE_GROUP_LOWER_BACK",
		16: "MUSCLE_GROUP_CHEST",
		17: "MUSCLE_GROUP_CARDIO",
		18: "MUSCLE_GROUP_NECK",
		19: "MUSCLE_GROUP_FULL_BODY",
		20: "MUSCLE_GROUP_OTHER",
	}
	MuscleGroup_value = map[string]int32{
		"MUSCLE_GROUP_UNSPECIFIED": 0,
		"MUSCLE_GROUP_ABDOMINALS":  1,
		"MUSCLE_GROUP_SHOULDERS":   2,
		"MUSCLE_GROUP_BICEPS":      3,
		"MUSCLE_GROUP_TRICEPS":     4,
		"MUSCLE_GROUP_FOREARMS":    5,
		"MUSCLE_GROUP_QUADRICEPS":  6,
		"MUSCLE_GROUP_HAMSTRINGS":  7,
		"MUSCLE_GROUP_CALVES":      8,
		"MUSCLE_GROUP_GLUTES":      9,
		"MUSCLE_GROUP_ABDUCTORS":   10,
		"MUSCLE_GROUP_ADDUCTORS":   11,
		"MUSCLE_GROUP_LATS":        12,
		"MUSCLE_GROUP_UPPER_BACK":  13,
		"MUSCLE_GROUP_TRAPS":       14,
		"MUSCLE_GROUP_LOWER_BACK":  15,
		"MUSCLE_GROUP_CHEST":       16,
		"MUSCLE_GROUP_CARDIO":      17,
		"MUSCLE_GROUP_NECK":        18,
		"MUSCLE_GROUP_FULL_BODY":   19,
		"MUSCLE_GROUP_OTHER":       20,
	}
)

func (x MuscleGroup) Enum() *MuscleGroup {
	p := new(MuscleGroup)
	*p = x
	return p
}

func (x MuscleGroup) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MuscleGroup) Descriptor() protoreflect.EnumDescriptor {
	return file_models_activity_standardized_proto_enumTypes[0].Descriptor()
}

func (MuscleGroup) Type() protoreflect.EnumType {
	return &file_models_activity_standardized_proto_enumTypes[0]
}

func (x MuscleGroup) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MuscleGroup.Descriptor instead.
func (MuscleGroup) EnumDescriptor() ([]byte, []int) {
	return file_models_activity_standardized_proto_rawDescGZIP(), []int{0}
}

type StandardizedActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        ActivitySource         `protobuf:"varint,1,opt,name=source,proto3,enum=fitglue.models.activity.ActivitySource" json:"source,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Type          ActivityType           `protobuf:"varint,6,opt,name=type,proto3,enum=fitglue.models.activity.ActivityType" json:"type,omitempty"`
	Sessions      []*Session             `protobuf:"bytes,7,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Notes         string                 `protobuf:"bytes,10,opt,name=notes,proto3" json:"notes,omitempty"`
	TimeMarkers   []*TimeMarker          `protobuf:"bytes,11,rep,name=time_markers,json=timeMarkers,proto3" json:"time_markers,omitempty"`
	Workout       *WorkoutDefinition     `protobuf:"bytes,12,opt,name=workout,proto3,oneof" json:"workout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandardizedActivity) Reset() {
	*x = StandardizedActivity{}
	mi := &file_models_activity_standardized_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandardizedActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardizedActivity) ProtoMessage() {}

func (x *StandardizedActivity) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_standardized_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardizedActivity.ProtoReflect.Descriptor instead.
func (*StandardizedActivity) Descriptor() ([]byte, []int) {
	return file_models_activity_standardized_proto_rawDescGZIP(), []int{0}
}

func (x *StandardizedActivity) GetSource() ActivitySource {
	if x != nil {
		return x.Source
	}
	return ActivitySource_SOURCE_UNSPECIFIED
}

func (x *StandardizedActivity) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *StandardizedActivity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StandardizedActivity) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *StandardizedActivity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StandardizedActivity) GetType() ActivityType {
	if x != nil {
		return x.Type
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

func (x *StandardizedActivity) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *StandardizedActivity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StandardizedActivity) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *StandardizedActivity) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *StandardizedActivity) GetTimeMarkers() []*TimeMarker {
	if x != nil {
		return x.TimeMarkers
	}
	return nil
}

func (x *StandardizedActivity) GetWorkout() *WorkoutDefinition {
	if x != nil {
		return x.Workout
	}
	return nil
}

type TimeMarker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	MarkerType    string                 `protobuf:"bytes,3,opt,name=marker_type,json=markerType,proto3" json:"marker_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeMarker) Reset() {
	*x = TimeMarker{}
	mi := &file_models_activity_standardized_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeMarker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeMarker) ProtoMessage() {}

func (x *TimeMarker) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_standardized_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeMarker.ProtoReflect.Descriptor instead.
func (*TimeMarker) Descriptor() ([]byte, []int) {
	return file_models_activity_standardized_proto_rawDescGZIP(), []int{1}
}

func (x *TimeMarker) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TimeMarker) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TimeMarker) GetMarkerType() string {
	if x != nil {
		return x.MarkerType
	}
	return ""
}

type Session struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StartTime        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	TotalElapsedTime float64                `protobuf:"fixed64,2,opt,name=total_elapsed_time,json=totalElapsedTime,proto3" json:"total_elapsed_time,omitempty"`
	TotalDistance    float64                `protobuf:"fixed64,3,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`
	Laps             []*Lap                 `protobuf:"bytes,4,rep,name=laps,proto3" json:"laps,omitempty"`
	StrengthSets     []*StrengthSet         `protobuf:"bytes,5,rep,name=strength_sets,json=strengthSets,proto3" json:"strength_sets,omitempty"`
	TotalCalories    *float64               `protobuf:"fixed64,6,opt,name=total_calories,json=totalCalories,proto3,oneof" json:"total_calories,omitempty"`
	AvgHeartRate     *int32                 `protobuf:"varint,7,opt,name=avg_heart_rate,json=avgHeartRate,proto3,oneof" json:"avg_heart_rate,omitempty"`
	MaxHeartRate     *int32                 `protobuf:"varint,8,opt,name=max_heart_rate,json=maxHeartRate,proto3,oneof" json:"max_heart_rate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_models_activity_standardized_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_standardized_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_models_activity_standardized_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Session) GetTotalElapsedTime() float64 {
	if x != nil {
		return x.TotalElapsedTime
	}
	return 0
}

func (x *Session) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *Session) GetLaps() []*Lap {
	if x != nil {
		return x.Laps
	}
	return nil
}

func (x *Session) GetStrengthSets() []*StrengthSet {
	if x != nil {
		return x.StrengthSets
	}
	return nil
}

func (x *Session) GetTotalCalories() float64 {
	if x != nil && x.TotalCalories != nil {
		return *x.TotalCalories
	}
	return 0
}

func (x *Session) GetAvgHeartRate() int32 {
	if x != nil && x.AvgHeartRate != nil {
		return *x.AvgHeartRate
	}
	return 0
}

func (x *Session) GetMaxHeartRate() int32 {
	if x != nil && x.MaxHeartRate != nil {
		return *x.MaxHeartRate
	}
	return 0
}

type Lap struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StartTime        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	TotalElapsedTime float64                `protobuf:"fixed64,2,opt,name=total_elapsed_time,json=totalElapsedTime,proto3" json:"total_elapsed_time,omitempty"`
	TotalDistance    float64                `protobuf:"fixed64,3,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`
	Records          []*Record              `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	ExerciseName     string                 `protobuf:"bytes,5,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`
	Intensity        string                 `protobuf:"bytes,6,opt,name=intensity,proto3" json:"intensity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Lap) Reset() {
	*x = Lap{}
	mi := &file_models_activity_standardized_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lap) ProtoMessage() {}

func (x *Lap) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_standardized_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lap.ProtoReflect.Descriptor instead.
func (*Lap) Descriptor() ([]byte, []int) {
	return file_models_activity_standardized_proto_rawDescGZIP(), []int{3}
}

func (x *Lap) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Lap) GetTotalElapsedTime() float64 {
	if x != nil {
		return x.TotalElapsedTime
	}
	return 0
}

func (x *Lap) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *Lap) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *Lap) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

func (x *Lap) GetIntensity() string {
	if x != nil {
		return x.Intensity
	}
	return ""
}

type Record struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Timestamp           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	HeartRate           int32                  `protobuf:"varint,2,opt,name=heart_rate,json=heartRate,proto3" json:"heart_rate,omitempty"`
	Power               int32                  `protobuf:"varint,3,opt,name=power,proto3" json:"power,omitempty"`
	Cadence             int32                  `protobuf:"varint,4,opt,name=cadence,proto3" json:"cadence,omitempty"`
	Speed               float64                `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`
	Altitude            float64                `protobuf:"fixed64,6,opt,name=altitude,proto3" json:"altitude,omitempty"`
	PositionLat         float64                `protobuf:"fixed64,7,opt,name=position_lat,json=positionLat,proto3" json:"position_lat,omitempty"`
	PositionLong        float64                `protobuf:"fixed64,8,opt,name=position_long,json=positionLong,proto3" json:"position_long,omitempty"`
	GroundContactTime   *int32                 `protobuf:"varint,9,opt,name=ground_contact_time,json=groundContactTime,proto3,oneof" json:"ground_contact_time,omitempty"`
	VerticalOscillation *int32                 `protobuf:"varint,10,opt,name=vertical_oscillation,json=verticalOscillation,proto3,oneof" json:"vertical_oscillation,omitempty"`
	VerticalRatio       *int32                 `protobuf:"varint,11,opt,name=vertical_ratio,json=verticalRatio,proto3,oneof" json:"vertical_ratio,omitempty"`
	StepLength          *float64               `protobuf:"fixed64,12,opt,name=step_length,json=stepLength,proto3,oneof" json:"step_length,omitempty"`
	Distance            float64                `protobuf:"fixed64,13,opt,name=distance,proto3" json:"distance,omitempty"` // Cumulative distance in meters from activity start
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_models_activity_standardized_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_standardized_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_models_activity_standardized_proto_rawDescGZIP(), []int{4}
}

func (x *Record) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Record) GetHeartRate() int32 {
	if x != nil {
		return x.HeartRate
	}
	return 0
}

func (x *Record) GetPower() int32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *Record) GetCadence() int32 {
	if x != nil {
		return x.Cadence
	}
	return 0
}

func (x *Record) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Record) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *Record) GetPositionLat() float64 {
	if x != nil {
		return x.PositionLat
	}
	return 0
}

func (x *Record) GetPositionLong() float64 {
	if x != nil {
		return x.PositionLong
	}
	return 0
}

func (x *Record) GetGroundContactTime() int32 {
	if x != nil && x.GroundContactTime != nil {
		return *x.GroundContactTime
	}
	return 0
}

func (x *Record) GetVerticalOscillation() int32 {
	if x != nil && x.VerticalOscillation != nil {
		return *x.VerticalOscillation
	}
	return 0
}

func (x *Record) GetVerticalRatio() int32 {
	if x != nil && x.VerticalRatio != nil {
		return *x.VerticalRatio
	}
	return 0
}

func (x *Record) GetStepLength() float64 {
	if x != nil && x.StepLength != nil {
		return *x.StepLength
	}
	return 0
}

func (x *Record) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type StrengthSet struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ExerciseName          string                 `protobuf:"bytes,1,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`
	Reps                  int32                  `protobuf:"varint,2,opt,name=reps,proto3" json:"reps,omitempty"`
	WeightKg              float64                `protobuf:"fixed64,3,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	StartTime             *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	DurationSeconds       int32                  `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Notes                 string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	SupersetId            string                 `protobuf:"bytes,7,opt,name=superset_id,json=supersetId,proto3" json:"superset_id,omitempty"`
	PrimaryMuscleGroup    MuscleGroup            `protobuf:"varint,8,opt,name=primary_muscle_group,json=primaryMuscleGroup,proto3,enum=fitglue.models.activity.MuscleGroup" json:"primary_muscle_group,omitempty"`
	SecondaryMuscleGroups []MuscleGroup          `protobuf:"varint,9,rep,packed,name=secondary_muscle_groups,json=secondaryMuscleGroups,proto3,enum=fitglue.models.activity.MuscleGroup" json:"secondary_muscle_groups,omitempty"`
	DistanceMeters        float64                `protobuf:"fixed64,10,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	SetType               string                 `protobuf:"bytes,11,opt,name=set_type,json=setType,proto3" json:"set_type,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StrengthSet) Reset() {
	*x = StrengthSet{}
	mi := &file_models_activity_standardized_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrengthSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrengthSet) ProtoMessage() {}

func (x *StrengthSet) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_standardized_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrengthSet.ProtoReflect.Descriptor instead.
func (*StrengthSet) Descriptor() ([]byte, []int) {
	return file_models_activity_standardized_proto_rawDescGZIP(), []int{5}
}

func (x *StrengthSet) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

func (x *StrengthSet) GetReps() int32 {
	if x != nil {
		return x.Reps
	}
	return 0
}

func (x *StrengthSet) GetWeightKg() float64 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *StrengthSet) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *StrengthSet) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *StrengthSet) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *StrengthSet) GetSupersetId() string {
	if x != nil {
		return x.SupersetId
	}
	return ""
}

func (x *StrengthSet) GetPrimaryMuscleGroup() MuscleGroup {
	if x != nil {
		return x.PrimaryMuscleGroup
	}
	return MuscleGroup_MUSCLE_GROUP_UNSPECIFIED
}

func (x *StrengthSet) GetSecondaryMuscleGroups() []MuscleGroup {
	if x != nil {
		return x.SecondaryMuscleGroups
	}
	return nil
}

func (x *StrengthSet) GetDistanceMeters() float64 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

func (x *StrengthSet) GetSetType() string {
	if x != nil {
		return x.SetType
	}
	return ""
}

type WorkoutDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Steps         []*WorkoutStep         `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkoutDefinition) Reset() {
	*x = WorkoutDefinition{}
	mi := &file_models_activity_standardized_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutDefinition) ProtoMessage() {}

func (x *WorkoutDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_standardized_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutDefinition.ProtoReflect.Descriptor instead.
func (*WorkoutDefinition) Descriptor() ([]byte, []int) {
	return file_models_activity_standardized_proto_rawDescGZIP(), []int{6}
}

func (x *WorkoutDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkoutDefinition) GetSteps() []*WorkoutStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type WorkoutStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intensity     string                 `protobuf:"bytes,1,opt,name=intensity,proto3" json:"intensity,omitempty"`
	DurationType  string                 `protobuf:"bytes,2,opt,name=duration_type,json=durationType,proto3" json:"duration_type,omitempty"`
	DurationValue uint32                 `protobuf:"varint,3,opt,name=duration_value,json=durationValue,proto3" json:"duration_value,omitempty"`
	TargetType    string                 `protobuf:"bytes,4,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetLow     uint32                 `protobuf:"varint,5,opt,name=target_low,json=targetLow,proto3" json:"target_low,omitempty"`
	TargetHigh    uint32                 `protobuf:"varint,6,opt,name=target_high,json=targetHigh,proto3" json:"target_high,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkoutStep) Reset() {
	*x = WorkoutStep{}
	mi := &file_models_activity_standardized_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutStep) ProtoMessage() {}

func (x *WorkoutStep) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_standardized_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutStep.ProtoReflect.Descriptor instead.
func (*WorkoutStep) Descriptor() ([]byte, []int) {
	return file_models_activity_standardized_proto_rawDescGZIP(), []int{7}
}

func (x *WorkoutStep) GetIntensity() string {
	if x != nil {
		return x.Intensity
	}
	return ""
}

func (x *WorkoutStep) GetDurationType() string {
	if x != nil {
		return x.DurationType
	}
	return ""
}

func (x *WorkoutStep) GetDurationValue() uint32 {
	if x != nil {
		return x.DurationValue
	}
	return 0
}

func (x *WorkoutStep) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *WorkoutStep) GetTargetLow() uint32 {
	if x != nil {
		return x.TargetLow
	}
	return 0
}

func (x *WorkoutStep) GetTargetHigh() uint32 {
	if x != nil {
		return x.TargetHigh
	}
	return 0
}

var File_models_activity_standardized_proto protoreflect.FileDescriptor

const file_models_activity_standardized_proto_rawDesc = "" +
	"\n" +
	"\"models/activity/standardized.proto\x12\x17fitglue.models.activity\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cmodels/activity/source.proto\"\xc4\x04\n" +
	"\x14StandardizedActivity\x12?\n" +
	"\x06source\x18\x01 \x01(\x0e2'.fitglue.models.activity.ActivitySourceR\x06source\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x129\n" +
	"\x04type\x18\x06 \x01(\x0e2%.fitglue.models.activity.ActivityTypeR\x04type\x12<\n" +
	"\bsessions\x18\a \x03(\v2 .fitglue.models.activity.SessionR\bsessions\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12\x14\n" +
	"\x05notes\x18\n" +
	" \x01(\tR\x05notes\x12F\n" +
	"\ftime_markers\x18\v \x03(\v2#.fitglue.models.activity.TimeMarkerR\vtimeMarkers\x12I\n" +
	"\aworkout\x18\f \x01(\v2*.fitglue.models.activity.WorkoutDefinitionH\x00R\aworkout\x88\x01\x01B\n" +
	"\n" +
	"\b_workout\"}\n" +
	"\n" +
	"TimeMarker\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1f\n" +
	"\vmarker_type\x18\x03 \x01(\tR\n" +
	"markerType\"\xd1\x03\n" +
	"\aSession\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12,\n" +
	"\x12total_elapsed_time\x18\x02 \x01(\x01R\x10totalElapsedTime\x12%\n" +
	"\x0etotal_distance\x18\x03 \x01(\x01R\rtotalDistance\x120\n" +
	"\x04laps\x18\x04 \x03(\v2\x1c.fitglue.models.activity.LapR\x04laps\x12I\n" +
	"\rstrength_sets\x18\x05 \x03(\v2$.fitglue.models.activity.StrengthSetR\fstrengthSets\x12*\n" +
	"\x0etotal_calories\x18\x06 \x01(\x01H\x00R\rtotalCalories\x88\x01\x01\x12)\n" +
	"\x0eavg_heart_rate\x18\a \x01(\x05H\x01R\favgHeartRate\x88\x01\x01\x12)\n" +
	"\x0emax_heart_rate\x18\b \x01(\x05H\x02R\fmaxHeartRate\x88\x01\x01B\x11\n" +
	"\x0f_total_caloriesB\x11\n" +
	"\x0f_avg_heart_rateB\x11\n" +
	"\x0f_max_heart_rate\"\x93\x02\n" +
	"\x03Lap\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12,\n" +
	"\x12total_elapsed_time\x18\x02 \x01(\x01R\x10totalElapsedTime\x12%\n" +
	"\x0etotal_distance\x18\x03 \x01(\x01R\rtotalDistance\x129\n" +
	"\arecords\x18\x04 \x03(\v2\x1f.fitglue.models.activity.RecordR\arecords\x12#\n" +
	"\rexercise_name\x18\x05 \x01(\tR\fexerciseName\x12\x1c\n" +
	"\tintensity\x18\x06 \x01(\tR\tintensity\"\xba\x04\n" +
	"\x06Record\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"heart_rate\x18\x02 \x01(\x05R\theartRate\x12\x14\n" +
	"\x05power\x18\x03 \x01(\x05R\x05power\x12\x18\n" +
	"\acadence\x18\x04 \x01(\x05R\acadence\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x01R\x05speed\x12\x1a\n" +
	"\baltitude\x18\x06 \x01(\x01R\baltitude\x12!\n" +
	"\fposition_lat\x18\a \x01(\x01R\vpositionLat\x12#\n" +
	"\rposition_long\x18\b \x01(\x01R\fpositionLong\x123\n" +
	"\x13ground_contact_time\x18\t \x01(\x05H\x00R\x11groundContactTime\x88\x01\x01\x126\n" +
	"\x14vertical_oscillation\x18\n" +
	" \x01(\x05H\x01R\x13verticalOscillation\x88\x01\x01\x12*\n" +
	"\x0evertical_ratio\x18\v \x01(\x05H\x02R\rverticalRatio\x88\x01\x01\x12$\n" +
	"\vstep_length\x18\f \x01(\x01H\x03R\n" +
	"stepLength\x88\x01\x01\x12\x1a\n" +
	"\bdistance\x18\r \x01(\x01R\bdistanceB\x16\n" +
	"\x14_ground_contact_timeB\x17\n" +
	"\x15_vertical_oscillationB\x11\n" +
	"\x0f_vertical_ratioB\x0e\n" +
	"\f_step_length\"\xfa\x03\n" +
	"\vStrengthSet\x12#\n" +
	"\rexercise_name\x18\x01 \x01(\tR\fexerciseName\x12\x12\n" +
	"\x04reps\x18\x02 \x01(\x05R\x04reps\x12\x1b\n" +
	"\tweight_kg\x18\x03 \x01(\x01R\bweightKg\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x05R\x0fdurationSeconds\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\x12\x1f\n" +
	"\vsuperset_id\x18\a \x01(\tR\n" +
	"supersetId\x12V\n" +
	"\x14primary_muscle_group\x18\b \x01(\x0e2$.fitglue.models.activity.MuscleGroupR\x12primaryMuscleGroup\x12\\\n" +
	"\x17secondary_muscle_groups\x18\t \x03(\x0e2$.fitglue.models.activity.MuscleGroupR\x15secondaryMuscleGroups\x12'\n" +
	"\x0fdistance_meters\x18\n" +
	" \x01(\x01R\x0edistanceMeters\x12\x19\n" +
	"\bset_type\x18\v \x01(\tR\asetType\"c\n" +
	"\x11WorkoutDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12:\n" +
	"\x05steps\x18\x02 \x03(\v2$.fitglue.models.activity.WorkoutStepR\x05steps\"\xd8\x01\n" +
	"\vWorkoutStep\x12\x1c\n" +
	"\tintensity\x18\x01 \x01(\tR\tintensity\x12#\n" +
	"\rduration_type\x18\x02 \x01(\tR\fdurationType\x12%\n" +
	"\x0eduration_value\x18\x03 \x01(\rR\rdurationValue\x12\x1f\n" +
	"\vtarget_type\x18\x04 \x01(\tR\n" +
	"targetType\x12\x1d\n" +
	"\n" +
	"target_low\x18\x05 \x01(\rR\ttargetLow\x12\x1f\n" +
	"\vtarget_high\x18\x06 \x01(\rR\n" +
	"targetHigh*\xbb\x04\n" +
	"\vMuscleGroup\x12\x1c\n" +
	"\x18MUSCLE_GROUP_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MUSCLE_GROUP_ABDOMINALS\x10\x01\x12\x1a\n" +
	"\x16MUSCLE_GROUP_SHOULDERS\x10\x02\x12\x17\n" +
	"\x13MUSCLE_GROUP_BICEPS\x10\x03\x12\x18\n" +
	"\x14MUSCLE_GROUP_TRICEPS\x10\x04\x12\x19\n" +
	"\x15MUSCLE_GROUP_FOREARMS\x10\x05\x12\x1b\n" +
	"\x17MUSCLE_GROUP_QUADRICEPS\x10\x06\x12\x1b\n" +
	"\x17MUSCLE_GROUP_HAMSTRINGS\x10\a\x12\x17\n" +
	"\x13MUSCLE_GROUP_CALVES\x10\b\x12\x17\n" +
	"\x13MUSCLE_GROUP_GLUTES\x10\t\x12\x1a\n" +
	"\x16MUSCLE_GROUP_ABDUCTORS\x10\n" +
	"\x12\x1a\n" +
	"\x16MUSCLE_GROUP_ADDUCTORS\x10\v\x12\x15\n" +
	"\x11MUSCLE_GROUP_LATS\x10\f\x12\x1b\n" +
	"\x17MUSCLE_GROUP_UPPER_BACK\x10\r\x12\x16\n" +
	"\x12MUSCLE_GROUP_TRAPS\x10\x0e\x12\x1b\n" +
	"\x17MUSCLE_GROUP_LOWER_BACK\x10\x0f\x12\x16\n" +
	"\x12MUSCLE_GROUP_CHEST\x10\x10\x12\x17\n" +
	"\x13MUSCLE_GROUP_CARDIO\x10\x11\x12\x15\n" +
	"\x11MUSCLE_GROUP_NECK\x10\x12\x12\x1a\n" +
	"\x16MUSCLE_GROUP_FULL_BODY\x10\x13\x12\x16\n" +
	"\x12MUSCLE_GROUP_OTHER\x10\x14B?Z=github.com/fitglue/server/src/go/pkg/types/pb/models/activityb\x06proto3"

var (
	file_models_activity_standardized_proto_rawDescOnce sync.Once
	file_models_activity_standardized_proto_rawDescData []byte
)

func file_models_activity_standardized_proto_rawDescGZIP() []byte {
	file_models_activity_standardized_proto_rawDescOnce.Do(func() {
		file_models_activity_standardized_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_activity_standardized_proto_rawDesc), len(file_models_activity_standardized_proto_rawDesc)))
	})
	return file_models_activity_standardized_proto_rawDescData
}

var file_models_activity_standardized_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_models_activity_standardized_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_models_activity_standardized_proto_goTypes = []any{
	(MuscleGroup)(0),              // 0: fitglue.models.activity.MuscleGroup
	(*StandardizedActivity)(nil),  // 1: fitglue.models.activity.StandardizedActivity
	(*TimeMarker)(nil),            // 2: fitglue.models.activity.TimeMarker
	(*Session)(nil),               // 3: fitglue.models.activity.Session
	(*Lap)(nil),                   // 4: fitglue.models.activity.Lap
	(*Record)(nil),                // 5: fitglue.models.activity.Record
	(*StrengthSet)(nil),           // 6: fitglue.models.activity.StrengthSet
	(*WorkoutDefinition)(nil),     // 7: fitglue.models.activity.WorkoutDefinition
	(*WorkoutStep)(nil),           // 8: fitglue.models.activity.WorkoutStep
	(ActivitySource)(0),           // 9: fitglue.models.activity.ActivitySource
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(ActivityType)(0),             // 11: fitglue.models.activity.ActivityType
}
var file_models_activity_standardized_proto_depIdxs = []int32{
	9,  // 0: fitglue.models.activity.StandardizedActivity.source:type_name -> fitglue.models.activity.ActivitySource
	10, // 1: fitglue.models.activity.StandardizedActivity.start_time:type_name -> google.protobuf.Timestamp
	11, // 2: fitglue.models.activity.StandardizedActivity.type:type_name -> fitglue.models.activity.ActivityType
	3,  // 3: fitglue.models.activity.StandardizedActivity.sessions:type_name -> fitglue.models.activity.Session
	2,  // 4: fitglue.models.activity.StandardizedActivity.time_markers:type_name -> fitglue.models.activity.TimeMarker
	7,  // 5: fitglue.models.activity.StandardizedActivity.workout:type_name -> fitglue.models.activity.WorkoutDefinition
	10, // 6: fitglue.models.activity.TimeMarker.timestamp:type_name -> google.protobuf.Timestamp
	10, // 7: fitglue.models.activity.Session.start_time:type_name -> google.protobuf.Timestamp
	4,  // 8: fitglue.models.activity.Session.laps:type_name -> fitglue.models.activity.Lap
	6,  // 9: fitglue.models.activity.Session.strength_sets:type_name -> fitglue.models.activity.StrengthSet
	10, // 10: fitglue.models.activity.Lap.start_time:type_name -> google.protobuf.Timestamp
	5,  // 11: fitglue.models.activity.Lap.records:type_name -> fitglue.models.activity.Record
	10, // 12: fitglue.models.activity.Record.timestamp:type_name -> google.protobuf.Timestamp
	10, // 13: fitglue.models.activity.StrengthSet.start_time:type_name -> google.protobuf.Timestamp
	0,  // 14: fitglue.models.activity.StrengthSet.primary_muscle_group:type_name -> fitglue.models.activity.MuscleGroup
	0,  // 15: fitglue.models.activity.StrengthSet.secondary_muscle_groups:type_name -> fitglue.models.activity.MuscleGroup
	8,  // 16: fitglue.models.activity.WorkoutDefinition.steps:type_name -> fitglue.models.activity.WorkoutStep
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_models_activity_standardized_proto_init() }
func file_models_activity_standardized_proto_init() {
	if File_models_activity_standardized_proto != nil {
		return
	}
	file_models_activity_source_proto_init()
	file_models_activity_standardized_proto_msgTypes[0].OneofWrappers = []any{}
	file_models_activity_standardized_proto_msgTypes[2].OneofWrappers = []any{}
	file_models_activity_standardized_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_activity_standardized_proto_rawDesc), len(file_models_activity_standardized_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_activity_standardized_proto_goTypes,
		DependencyIndexes: file_models_activity_standardized_proto_depIdxs,
		EnumInfos:         file_models_activity_standardized_proto_enumTypes,
		MessageInfos:      file_models_activity_standardized_proto_msgTypes,
	}.Build()
	File_models_activity_standardized_proto = out.File
	file_models_activity_standardized_proto_goTypes = nil
	file_models_activity_standardized_proto_depIdxs = nil
}
