import { BaseConnector, ConnectorConfig, IngestStrategy, StandardizedActivity, CloudEventSource, ActivitySource, FrameworkContext, ActivityType } from '@fitglue/shared';

// Mock specific config (none needed beyond base for now)
export interface MockConnectorConfig extends ConnectorConfig {
  apiKey: string;
}

export class MockConnector extends BaseConnector<MockConnectorConfig, unknown> {
  readonly name = 'mock';
  readonly strategy: IngestStrategy = 'webhook';
  // Use the integer value 99 directly if the enum isn't updated in shared lib yet,
  // but better to cast or use the enum if valid.
  // Since we ran make generate, it should be there.
  readonly cloudEventSource = CloudEventSource.CLOUD_EVENT_SOURCE_MOCK;
  // We need a MOCK source in ActivitySource too?
  readonly activitySource = ActivitySource.SOURCE_TEST; // 99

  constructor(context: FrameworkContext) {
    super(context);
    context.logger.debug(`MockConnector: initialized`);
  }

  extractId(body: unknown): string | null {
    if (!body) return "unknown";
    return (body as { id?: string }).id || "unknown";
  }

  async fetchAndMap(activityId: string, config: MockConnectorConfig): Promise<StandardizedActivity[]> {
    this.context.logger.info(`MockConnector: generating mock activity for ${activityId}`);

    // Generate a dummy activity
    // We can parse the ID to vary the activity type if we want, e.g. "run_123"
    let type = ActivityType.ACTIVITY_TYPE_WEIGHT_TRAINING;
    let name = "Mock Workout";

    if (activityId && activityId.toLowerCase().includes("run")) {
      type = ActivityType.ACTIVITY_TYPE_RUN;
      name = "Mock Run";
    } else if (activityId.toLowerCase().includes("cycle") || activityId.toLowerCase().includes("ride")) {
      type = ActivityType.ACTIVITY_TYPE_RIDE;
      name = "Mock Ride";
    }

    const standardized: StandardizedActivity = {
      source: "SOURCE_TEST",
      externalId: activityId,
      userId: (config as unknown as { userId: string }).userId,
      startTime: new Date(),
      name: name,
      type: type,
      description: "Generated by Mock Source Handler",
      sessions: [{
        startTime: new Date(),
        totalElapsedTime: 3600, // 1 hour
        totalDistance: 5000,
        laps: [],
        strengthSets: []
      }],
      tags: ["mock"],
      notes: ""
    };

    return [standardized];
  }

  // Abstract method implementation required by BaseConnector,
  // even though fetchAndMap override bypasses it.
  async mapActivity(_: unknown): Promise<StandardizedActivity> {
    throw new Error("MockConnector.mapActivity should not be called directly as fetchAndMap is overridden.");
  }
}
