// Package wahoo provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package wahoo

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ExchangeTokenFormdataBodyGrantType.
const (
	AuthorizationCode ExchangeTokenFormdataBodyGrantType = "authorization_code"
	RefreshToken      ExchangeTokenFormdataBodyGrantType = "refresh_token"
)

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken OAuth access token
	AccessToken string `json:"access_token"`

	// CreatedAt Token creation timestamp (Unix epoch seconds)
	CreatedAt int `json:"created_at"`

	// ExpiresIn Token expiration time in seconds
	ExpiresIn int `json:"expires_in"`

	// RefreshToken OAuth refresh token
	RefreshToken string `json:"refresh_token"`

	// TokenType Token type (usually 'Bearer')
	TokenType *string `json:"token_type,omitempty"`
}

// User defines model for User.
type User struct {
	// CreatedAt Account creation timestamp
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Email User email address
	Email *openapi_types.Email `json:"email,omitempty"`

	// First First name
	First *string `json:"first,omitempty"`

	// Id Wahoo user ID
	Id int `json:"id"`

	// Last Last name
	Last *string `json:"last,omitempty"`

	// UpdatedAt Account last update timestamp
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// Workout defines model for Workout.
type Workout struct {
	// AscentAccum Total elevation gain in meters
	AscentAccum *float32 `json:"ascent_accum,omitempty"`

	// CadenceAvg Average cadence
	CadenceAvg *float32 `json:"cadence_avg,omitempty"`

	// Calories Calories burned
	Calories *float32 `json:"calories,omitempty"`

	// CreatedAt Record creation timestamp
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// DistanceAccum Total distance in meters
	DistanceAccum *float32 `json:"distance_accum,omitempty"`

	// HeartRateAvg Average heart rate in BPM
	HeartRateAvg *float32 `json:"heart_rate_avg,omitempty"`

	// Id Workout ID
	Id int `json:"id"`

	// Minutes Total workout duration in minutes
	Minutes *float32 `json:"minutes,omitempty"`

	// Name Workout name
	Name *string `json:"name,omitempty"`

	// PlanId Associated training plan ID if any
	PlanId *int `json:"plan_id"`

	// PowerAvg Average power in watts
	PowerAvg *float32 `json:"power_avg,omitempty"`

	// SpeedAvg Average speed in m/s
	SpeedAvg *float32 `json:"speed_avg,omitempty"`

	// Starts Workout start timestamp
	Starts *time.Time `json:"starts,omitempty"`

	// UpdatedAt Record last update timestamp
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// WorkoutToken Unique workout token
	WorkoutToken *string `json:"workout_token,omitempty"`

	// WorkoutTypeId Workout type ID (0=Cycling, 1=Running, 2=Walking, etc.)
	WorkoutTypeId *int `json:"workout_type_id,omitempty"`
}

// ExchangeTokenFormdataBody defines parameters for ExchangeToken.
type ExchangeTokenFormdataBody struct {
	// ClientId OAuth client ID
	ClientId string `form:"client_id" json:"client_id"`

	// ClientSecret OAuth client secret
	ClientSecret string `form:"client_secret" json:"client_secret"`

	// Code Authorization code from OAuth callback
	Code string `form:"code" json:"code"`

	// GrantType OAuth grant type
	GrantType ExchangeTokenFormdataBodyGrantType `form:"grant_type" json:"grant_type"`

	// RedirectUri Redirect URI used in authorization request
	RedirectUri string `form:"redirect_uri" json:"redirect_uri"`

	// RefreshToken Refresh token (required when grant_type is refresh_token)
	RefreshToken *string `form:"refresh_token,omitempty" json:"refresh_token,omitempty"`
}

// ExchangeTokenFormdataBodyGrantType defines parameters for ExchangeToken.
type ExchangeTokenFormdataBodyGrantType string

// ExchangeTokenFormdataRequestBody defines body for ExchangeToken for application/x-www-form-urlencoded ContentType.
type ExchangeTokenFormdataRequestBody ExchangeTokenFormdataBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ExchangeTokenWithBody request with any body
	ExchangeTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ExchangeTokenWithFormdataBody(ctx context.Context, body ExchangeTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUser request
	GetUser(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetWorkout request
	GetWorkout(ctx context.Context, workoutId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetWorkoutFile request
	GetWorkoutFile(ctx context.Context, workoutId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ExchangeTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExchangeTokenRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExchangeTokenWithFormdataBody(ctx context.Context, body ExchangeTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExchangeTokenRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUser(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetWorkout(ctx context.Context, workoutId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWorkoutRequest(c.Server, workoutId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetWorkoutFile(ctx context.Context, workoutId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWorkoutFileRequest(c.Server, workoutId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewExchangeTokenRequestWithFormdataBody calls the generic ExchangeToken builder with application/x-www-form-urlencoded body
func NewExchangeTokenRequestWithFormdataBody(server string, body ExchangeTokenFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewExchangeTokenRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewExchangeTokenRequestWithBody generates requests for ExchangeToken with any type of body
func NewExchangeTokenRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/oauth/token")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetUserRequest generates requests for GetUser
func NewGetUserRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/user")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetWorkoutRequest generates requests for GetWorkout
func NewGetWorkoutRequest(server string, workoutId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "workoutId", runtime.ParamLocationPath, workoutId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/workouts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetWorkoutFileRequest generates requests for GetWorkoutFile
func NewGetWorkoutFileRequest(server string, workoutId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "workoutId", runtime.ParamLocationPath, workoutId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/workouts/%s/file", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ExchangeTokenWithBodyWithResponse request with any body
	ExchangeTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExchangeTokenResponse, error)

	ExchangeTokenWithFormdataBodyWithResponse(ctx context.Context, body ExchangeTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*ExchangeTokenResponse, error)

	// GetUserWithResponse request
	GetUserWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUserResponse, error)

	// GetWorkoutWithResponse request
	GetWorkoutWithResponse(ctx context.Context, workoutId string, reqEditors ...RequestEditorFn) (*GetWorkoutResponse, error)

	// GetWorkoutFileWithResponse request
	GetWorkoutFileWithResponse(ctx context.Context, workoutId string, reqEditors ...RequestEditorFn) (*GetWorkoutFileResponse, error)
}

type ExchangeTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TokenResponse
}

// Status returns HTTPResponse.Status
func (r ExchangeTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExchangeTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *User
}

// Status returns HTTPResponse.Status
func (r GetUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetWorkoutResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Workout
}

// Status returns HTTPResponse.Status
func (r GetWorkoutResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetWorkoutResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetWorkoutFileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetWorkoutFileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetWorkoutFileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ExchangeTokenWithBodyWithResponse request with arbitrary body returning *ExchangeTokenResponse
func (c *ClientWithResponses) ExchangeTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExchangeTokenResponse, error) {
	rsp, err := c.ExchangeTokenWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExchangeTokenResponse(rsp)
}

func (c *ClientWithResponses) ExchangeTokenWithFormdataBodyWithResponse(ctx context.Context, body ExchangeTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*ExchangeTokenResponse, error) {
	rsp, err := c.ExchangeTokenWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExchangeTokenResponse(rsp)
}

// GetUserWithResponse request returning *GetUserResponse
func (c *ClientWithResponses) GetUserWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUserResponse, error) {
	rsp, err := c.GetUser(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserResponse(rsp)
}

// GetWorkoutWithResponse request returning *GetWorkoutResponse
func (c *ClientWithResponses) GetWorkoutWithResponse(ctx context.Context, workoutId string, reqEditors ...RequestEditorFn) (*GetWorkoutResponse, error) {
	rsp, err := c.GetWorkout(ctx, workoutId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWorkoutResponse(rsp)
}

// GetWorkoutFileWithResponse request returning *GetWorkoutFileResponse
func (c *ClientWithResponses) GetWorkoutFileWithResponse(ctx context.Context, workoutId string, reqEditors ...RequestEditorFn) (*GetWorkoutFileResponse, error) {
	rsp, err := c.GetWorkoutFile(ctx, workoutId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWorkoutFileResponse(rsp)
}

// ParseExchangeTokenResponse parses an HTTP response from a ExchangeTokenWithResponse call
func ParseExchangeTokenResponse(rsp *http.Response) (*ExchangeTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExchangeTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetUserResponse parses an HTTP response from a GetUserWithResponse call
func ParseGetUserResponse(rsp *http.Response) (*GetUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetWorkoutResponse parses an HTTP response from a GetWorkoutWithResponse call
func ParseGetWorkoutResponse(rsp *http.Response) (*GetWorkoutResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetWorkoutResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Workout
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetWorkoutFileResponse parses an HTTP response from a GetWorkoutFileWithResponse call
func ParseGetWorkoutFileResponse(rsp *http.Response) (*GetWorkoutFileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetWorkoutFileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
