/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange authorization code for tokens
         * @description Exchange an OAuth authorization code for access and refresh tokens. Note: This endpoint is on oauth.trainingpeaks.com
         */
        post: operations["exchangeToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/athlete/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get athlete profile
         * @description Returns the authenticated athlete's profile information.
         */
        get: operations["getAthleteProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TokenResponse: {
            /** @description OAuth access token */
            access_token: string;
            /** @description OAuth refresh token */
            refresh_token: string;
            /** @description Token expiration time in seconds */
            expires_in: number;
            /** @description Token type (usually 'Bearer') */
            token_type?: string;
            /** @description Athlete ID (may be included in token response) */
            athlete_id?: string;
        };
        AthleteProfile: {
            /** @description Athlete ID */
            Id?: string;
            /** @description Athlete first name */
            FirstName?: string;
            /** @description Athlete last name */
            LastName?: string;
            /**
             * Format: email
             * @description Athlete email address
             */
            Email?: string;
            /**
             * Format: date
             * @description Athlete date of birth
             */
            DateOfBirth?: string;
            /**
             * @description Athlete gender
             * @enum {string}
             */
            Gender?: "Male" | "Female" | "Other";
            /** @description Athlete weight in kg */
            Weight?: number;
            /** @description Threshold heart rate in BPM */
            ThresholdHeartRate?: number;
            /** @description Functional threshold power in watts */
            ThresholdPower?: number;
            /** @description Threshold pace */
            ThresholdPace?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    exchangeToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @description OAuth client ID */
                    client_id: string;
                    /** @description OAuth client secret */
                    client_secret: string;
                    /** @description Authorization code from OAuth callback */
                    code: string;
                    /**
                     * @description OAuth grant type
                     * @enum {string}
                     */
                    grant_type: "authorization_code" | "refresh_token";
                    /** @description Redirect URI used in authorization request */
                    redirect_uri: string;
                    /** @description Refresh token (required when grant_type is refresh_token) */
                    refresh_token?: string;
                };
            };
        };
        responses: {
            /** @description Successful token exchange */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAthleteProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Athlete profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AthleteProfile"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
