// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: services/registry/registry.proto

package registry

import (
	plugin "github.com/fitglue/server/src/go/pkg/types/pb/models/plugin"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_services_registry_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_registry_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_services_registry_registry_proto_rawDescGZIP(), []int{0}
}

func (x *ListPluginsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListPluginsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Plugins       []*plugin.PluginManifest `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_services_registry_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_registry_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_services_registry_registry_proto_rawDescGZIP(), []int{1}
}

func (x *ListPluginsResponse) GetPlugins() []*plugin.PluginManifest {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type GetPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginRequest) Reset() {
	*x = GetPluginRequest{}
	mi := &file_services_registry_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginRequest) ProtoMessage() {}

func (x *GetPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_registry_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginRequest.ProtoReflect.Descriptor instead.
func (*GetPluginRequest) Descriptor() ([]byte, []int) {
	return file_services_registry_registry_proto_rawDescGZIP(), []int{2}
}

func (x *GetPluginRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_services_registry_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_registry_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_services_registry_registry_proto_rawDescGZIP(), []int{3}
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []string               `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_services_registry_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_registry_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_services_registry_registry_proto_rawDescGZIP(), []int{4}
}

func (x *ListCategoriesResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type GetPluginIconRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginIconRequest) Reset() {
	*x = GetPluginIconRequest{}
	mi := &file_services_registry_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginIconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginIconRequest) ProtoMessage() {}

func (x *GetPluginIconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_registry_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginIconRequest.ProtoReflect.Descriptor instead.
func (*GetPluginIconRequest) Descriptor() ([]byte, []int) {
	return file_services_registry_registry_proto_rawDescGZIP(), []int{5}
}

func (x *GetPluginIconRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

type GetPluginIconResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IconData      []byte                 `protobuf:"bytes,1,opt,name=icon_data,json=iconData,proto3" json:"icon_data,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginIconResponse) Reset() {
	*x = GetPluginIconResponse{}
	mi := &file_services_registry_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginIconResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginIconResponse) ProtoMessage() {}

func (x *GetPluginIconResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_registry_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginIconResponse.ProtoReflect.Descriptor instead.
func (*GetPluginIconResponse) Descriptor() ([]byte, []int) {
	return file_services_registry_registry_proto_rawDescGZIP(), []int{6}
}

func (x *GetPluginIconResponse) GetIconData() []byte {
	if x != nil {
		return x.IconData
	}
	return nil
}

func (x *GetPluginIconResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type ListSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesRequest) Reset() {
	*x = ListSourcesRequest{}
	mi := &file_services_registry_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesRequest) ProtoMessage() {}

func (x *ListSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_registry_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListSourcesRequest) Descriptor() ([]byte, []int) {
	return file_services_registry_registry_proto_rawDescGZIP(), []int{7}
}

type ListSourcesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Sources       []*plugin.PluginManifest `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesResponse) Reset() {
	*x = ListSourcesResponse{}
	mi := &file_services_registry_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesResponse) ProtoMessage() {}

func (x *ListSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_registry_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListSourcesResponse) Descriptor() ([]byte, []int) {
	return file_services_registry_registry_proto_rawDescGZIP(), []int{8}
}

func (x *ListSourcesResponse) GetSources() []*plugin.PluginManifest {
	if x != nil {
		return x.Sources
	}
	return nil
}

type ListDestinationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDestinationsRequest) Reset() {
	*x = ListDestinationsRequest{}
	mi := &file_services_registry_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDestinationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDestinationsRequest) ProtoMessage() {}

func (x *ListDestinationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_registry_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDestinationsRequest.ProtoReflect.Descriptor instead.
func (*ListDestinationsRequest) Descriptor() ([]byte, []int) {
	return file_services_registry_registry_proto_rawDescGZIP(), []int{9}
}

type ListDestinationsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Destinations  []*plugin.PluginManifest `protobuf:"bytes,1,rep,name=destinations,proto3" json:"destinations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDestinationsResponse) Reset() {
	*x = ListDestinationsResponse{}
	mi := &file_services_registry_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDestinationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDestinationsResponse) ProtoMessage() {}

func (x *ListDestinationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_registry_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDestinationsResponse.ProtoReflect.Descriptor instead.
func (*ListDestinationsResponse) Descriptor() ([]byte, []int) {
	return file_services_registry_registry_proto_rawDescGZIP(), []int{10}
}

func (x *ListDestinationsResponse) GetDestinations() []*plugin.PluginManifest {
	if x != nil {
		return x.Destinations
	}
	return nil
}

var File_services_registry_registry_proto protoreflect.FileDescriptor

const file_services_registry_registry_proto_rawDesc = "" +
	"\n" +
	" services/registry/registry.proto\x12\x19fitglue.services.registry\x1a\x1cgoogle/api/annotations.proto\x1a\x1cmodels/plugin/manifest.proto\"0\n" +
	"\x12ListPluginsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\"V\n" +
	"\x13ListPluginsResponse\x12?\n" +
	"\aplugins\x18\x01 \x03(\v2%.fitglue.models.plugin.PluginManifestR\aplugins\"/\n" +
	"\x10GetPluginRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\"\x17\n" +
	"\x15ListCategoriesRequest\"8\n" +
	"\x16ListCategoriesResponse\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories\"3\n" +
	"\x14GetPluginIconRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\"W\n" +
	"\x15GetPluginIconResponse\x12\x1b\n" +
	"\ticon_data\x18\x01 \x01(\fR\biconData\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"\x14\n" +
	"\x12ListSourcesRequest\"V\n" +
	"\x13ListSourcesResponse\x12?\n" +
	"\asources\x18\x01 \x03(\v2%.fitglue.models.plugin.PluginManifestR\asources\"\x19\n" +
	"\x17ListDestinationsRequest\"e\n" +
	"\x18ListDestinationsResponse\x12I\n" +
	"\fdestinations\x18\x01 \x03(\v2%.fitglue.models.plugin.PluginManifestR\fdestinations2\x95\a\n" +
	"\x0fRegistryService\x12\x8a\x01\n" +
	"\vListPlugins\x12-.fitglue.services.registry.ListPluginsRequest\x1a..fitglue.services.registry.ListPluginsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v2/registry/plugins\x12\x89\x01\n" +
	"\tGetPlugin\x12+.fitglue.services.registry.GetPluginRequest\x1a%.fitglue.models.plugin.PluginManifest\"(\x82\xd3\xe4\x93\x02\"\x12 /v2/registry/plugins/{plugin_id}\x12\x96\x01\n" +
	"\x0eListCategories\x120.fitglue.services.registry.ListCategoriesRequest\x1a1.fitglue.services.registry.ListCategoriesResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v2/registry/categories\x12\xa1\x01\n" +
	"\rGetPluginIcon\x12/.fitglue.services.registry.GetPluginIconRequest\x1a0.fitglue.services.registry.GetPluginIconResponse\"-\x82\xd3\xe4\x93\x02'\x12%/v2/registry/plugins/{plugin_id}/icon\x12\x8a\x01\n" +
	"\vListSources\x12-.fitglue.services.registry.ListSourcesRequest\x1a..fitglue.services.registry.ListSourcesResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v2/registry/sources\x12\x9e\x01\n" +
	"\x10ListDestinations\x122.fitglue.services.registry.ListDestinationsRequest\x1a3.fitglue.services.registry.ListDestinationsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v2/registry/destinationsBAZ?github.com/fitglue/server/src/go/pkg/types/pb/services/registryb\x06proto3"

var (
	file_services_registry_registry_proto_rawDescOnce sync.Once
	file_services_registry_registry_proto_rawDescData []byte
)

func file_services_registry_registry_proto_rawDescGZIP() []byte {
	file_services_registry_registry_proto_rawDescOnce.Do(func() {
		file_services_registry_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_registry_registry_proto_rawDesc), len(file_services_registry_registry_proto_rawDesc)))
	})
	return file_services_registry_registry_proto_rawDescData
}

var file_services_registry_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_services_registry_registry_proto_goTypes = []any{
	(*ListPluginsRequest)(nil),       // 0: fitglue.services.registry.ListPluginsRequest
	(*ListPluginsResponse)(nil),      // 1: fitglue.services.registry.ListPluginsResponse
	(*GetPluginRequest)(nil),         // 2: fitglue.services.registry.GetPluginRequest
	(*ListCategoriesRequest)(nil),    // 3: fitglue.services.registry.ListCategoriesRequest
	(*ListCategoriesResponse)(nil),   // 4: fitglue.services.registry.ListCategoriesResponse
	(*GetPluginIconRequest)(nil),     // 5: fitglue.services.registry.GetPluginIconRequest
	(*GetPluginIconResponse)(nil),    // 6: fitglue.services.registry.GetPluginIconResponse
	(*ListSourcesRequest)(nil),       // 7: fitglue.services.registry.ListSourcesRequest
	(*ListSourcesResponse)(nil),      // 8: fitglue.services.registry.ListSourcesResponse
	(*ListDestinationsRequest)(nil),  // 9: fitglue.services.registry.ListDestinationsRequest
	(*ListDestinationsResponse)(nil), // 10: fitglue.services.registry.ListDestinationsResponse
	(*plugin.PluginManifest)(nil),    // 11: fitglue.models.plugin.PluginManifest
}
var file_services_registry_registry_proto_depIdxs = []int32{
	11, // 0: fitglue.services.registry.ListPluginsResponse.plugins:type_name -> fitglue.models.plugin.PluginManifest
	11, // 1: fitglue.services.registry.ListSourcesResponse.sources:type_name -> fitglue.models.plugin.PluginManifest
	11, // 2: fitglue.services.registry.ListDestinationsResponse.destinations:type_name -> fitglue.models.plugin.PluginManifest
	0,  // 3: fitglue.services.registry.RegistryService.ListPlugins:input_type -> fitglue.services.registry.ListPluginsRequest
	2,  // 4: fitglue.services.registry.RegistryService.GetPlugin:input_type -> fitglue.services.registry.GetPluginRequest
	3,  // 5: fitglue.services.registry.RegistryService.ListCategories:input_type -> fitglue.services.registry.ListCategoriesRequest
	5,  // 6: fitglue.services.registry.RegistryService.GetPluginIcon:input_type -> fitglue.services.registry.GetPluginIconRequest
	7,  // 7: fitglue.services.registry.RegistryService.ListSources:input_type -> fitglue.services.registry.ListSourcesRequest
	9,  // 8: fitglue.services.registry.RegistryService.ListDestinations:input_type -> fitglue.services.registry.ListDestinationsRequest
	1,  // 9: fitglue.services.registry.RegistryService.ListPlugins:output_type -> fitglue.services.registry.ListPluginsResponse
	11, // 10: fitglue.services.registry.RegistryService.GetPlugin:output_type -> fitglue.models.plugin.PluginManifest
	4,  // 11: fitglue.services.registry.RegistryService.ListCategories:output_type -> fitglue.services.registry.ListCategoriesResponse
	6,  // 12: fitglue.services.registry.RegistryService.GetPluginIcon:output_type -> fitglue.services.registry.GetPluginIconResponse
	8,  // 13: fitglue.services.registry.RegistryService.ListSources:output_type -> fitglue.services.registry.ListSourcesResponse
	10, // 14: fitglue.services.registry.RegistryService.ListDestinations:output_type -> fitglue.services.registry.ListDestinationsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_services_registry_registry_proto_init() }
func file_services_registry_registry_proto_init() {
	if File_services_registry_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_registry_registry_proto_rawDesc), len(file_services_registry_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_registry_registry_proto_goTypes,
		DependencyIndexes: file_services_registry_registry_proto_depIdxs,
		MessageInfos:      file_services_registry_registry_proto_msgTypes,
	}.Build()
	File_services_registry_registry_proto = out.File
	file_services_registry_registry_proto_goTypes = nil
	file_services_registry_registry_proto_depIdxs = nil
}
