// Code generated by generate-enum-formatters.ts. DO NOT EDIT.
package formatters

import (
	"strings"

	pb "github.com/fitglue/server/src/go/pkg/types/pb"
)

func FormatActivityType(value pb.ActivityType) string {
	switch value {
	case pb.ActivityType_ACTIVITY_TYPE_UNSPECIFIED:
		return "Workout"
	case pb.ActivityType_ACTIVITY_TYPE_ALPINE_SKI:
		return "Alpine Ski"
	case pb.ActivityType_ACTIVITY_TYPE_BACKCOUNTRY_SKI:
		return "Backcountry Ski"
	case pb.ActivityType_ACTIVITY_TYPE_BADMINTON:
		return "Badminton"
	case pb.ActivityType_ACTIVITY_TYPE_CANOEING:
		return "Canoeing"
	case pb.ActivityType_ACTIVITY_TYPE_CROSSFIT:
		return "Crossfit"
	case pb.ActivityType_ACTIVITY_TYPE_EBIKE_RIDE:
		return "E-Bike Ride"
	case pb.ActivityType_ACTIVITY_TYPE_ELLIPTICAL:
		return "Elliptical"
	case pb.ActivityType_ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE:
		return "E-Mountain Bike Ride"
	case pb.ActivityType_ACTIVITY_TYPE_GOLF:
		return "Golf"
	case pb.ActivityType_ACTIVITY_TYPE_GRAVEL_RIDE:
		return "Gravel Ride"
	case pb.ActivityType_ACTIVITY_TYPE_HANDCYCLE:
		return "Handcycle"
	case pb.ActivityType_ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING:
		return "HIIT"
	case pb.ActivityType_ACTIVITY_TYPE_HIKE:
		return "Hike"
	case pb.ActivityType_ACTIVITY_TYPE_ICE_SKATE:
		return "Ice Skate"
	case pb.ActivityType_ACTIVITY_TYPE_INLINE_SKATE:
		return "Inline Skate"
	case pb.ActivityType_ACTIVITY_TYPE_KAYAKING:
		return "Kayaking"
	case pb.ActivityType_ACTIVITY_TYPE_KITESURF:
		return "Kitesurf"
	case pb.ActivityType_ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE:
		return "Mountain Bike Ride"
	case pb.ActivityType_ACTIVITY_TYPE_NORDIC_SKI:
		return "Nordic Ski"
	case pb.ActivityType_ACTIVITY_TYPE_PICKLEBALL:
		return "Pickleball"
	case pb.ActivityType_ACTIVITY_TYPE_PILATES:
		return "Pilates"
	case pb.ActivityType_ACTIVITY_TYPE_RACQUETBALL:
		return "Racquetball"
	case pb.ActivityType_ACTIVITY_TYPE_RIDE:
		return "Ride"
	case pb.ActivityType_ACTIVITY_TYPE_ROCK_CLIMBING:
		return "Rock Climbing"
	case pb.ActivityType_ACTIVITY_TYPE_ROLLER_SKI:
		return "Roller Ski"
	case pb.ActivityType_ACTIVITY_TYPE_ROWING:
		return "Rowing"
	case pb.ActivityType_ACTIVITY_TYPE_RUN:
		return "Run"
	case pb.ActivityType_ACTIVITY_TYPE_SAIL:
		return "Sail"
	case pb.ActivityType_ACTIVITY_TYPE_SKATEBOARD:
		return "Skateboard"
	case pb.ActivityType_ACTIVITY_TYPE_SNOWBOARD:
		return "Snowboard"
	case pb.ActivityType_ACTIVITY_TYPE_SNOWSHOE:
		return "Snowshoe"
	case pb.ActivityType_ACTIVITY_TYPE_SOCCER:
		return "Soccer"
	case pb.ActivityType_ACTIVITY_TYPE_SQUASH:
		return "Squash"
	case pb.ActivityType_ACTIVITY_TYPE_STAIR_STEPPER:
		return "Stair Stepper"
	case pb.ActivityType_ACTIVITY_TYPE_STAND_UP_PADDLING:
		return "Stand Up Paddling"
	case pb.ActivityType_ACTIVITY_TYPE_SURFING:
		return "Surfing"
	case pb.ActivityType_ACTIVITY_TYPE_SWIM:
		return "Swim"
	case pb.ActivityType_ACTIVITY_TYPE_TABLE_TENNIS:
		return "Table Tennis"
	case pb.ActivityType_ACTIVITY_TYPE_TENNIS:
		return "Tennis"
	case pb.ActivityType_ACTIVITY_TYPE_TRAIL_RUN:
		return "Trail Run"
	case pb.ActivityType_ACTIVITY_TYPE_VELOMOBILE:
		return "Velomobile"
	case pb.ActivityType_ACTIVITY_TYPE_VIRTUAL_RIDE:
		return "Virtual Ride"
	case pb.ActivityType_ACTIVITY_TYPE_VIRTUAL_ROW:
		return "Virtual Row"
	case pb.ActivityType_ACTIVITY_TYPE_VIRTUAL_RUN:
		return "Virtual Run"
	case pb.ActivityType_ACTIVITY_TYPE_WALK:
		return "Walk"
	case pb.ActivityType_ACTIVITY_TYPE_WEIGHT_TRAINING:
		return "Weight Training"
	case pb.ActivityType_ACTIVITY_TYPE_WHEELCHAIR:
		return "Wheelchair"
	case pb.ActivityType_ACTIVITY_TYPE_WINDSURF:
		return "Windsurf"
	case pb.ActivityType_ACTIVITY_TYPE_WORKOUT:
		return "Workout"
	case pb.ActivityType_ACTIVITY_TYPE_YOGA:
		return "Yoga"
	default:
		return "Workout"
	}
}

func ParseActivityType(input string) pb.ActivityType {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.ActivityType_value[input]; ok {
		return pb.ActivityType(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.ActivityType{
		"activity_type_unspecified":         pb.ActivityType_ACTIVITY_TYPE_UNSPECIFIED,
		"unspecified":                       pb.ActivityType_ACTIVITY_TYPE_UNSPECIFIED,
		"workout":                           pb.ActivityType_ACTIVITY_TYPE_UNSPECIFIED,
		"activity_type_alpine_ski":          pb.ActivityType_ACTIVITY_TYPE_ALPINE_SKI,
		"alpine_ski":                        pb.ActivityType_ACTIVITY_TYPE_ALPINE_SKI,
		"alpine ski":                        pb.ActivityType_ACTIVITY_TYPE_ALPINE_SKI,
		"activity_type_backcountry_ski":     pb.ActivityType_ACTIVITY_TYPE_BACKCOUNTRY_SKI,
		"backcountry_ski":                   pb.ActivityType_ACTIVITY_TYPE_BACKCOUNTRY_SKI,
		"backcountry ski":                   pb.ActivityType_ACTIVITY_TYPE_BACKCOUNTRY_SKI,
		"activity_type_badminton":           pb.ActivityType_ACTIVITY_TYPE_BADMINTON,
		"badminton":                         pb.ActivityType_ACTIVITY_TYPE_BADMINTON,
		"activity_type_canoeing":            pb.ActivityType_ACTIVITY_TYPE_CANOEING,
		"canoeing":                          pb.ActivityType_ACTIVITY_TYPE_CANOEING,
		"activity_type_crossfit":            pb.ActivityType_ACTIVITY_TYPE_CROSSFIT,
		"crossfit":                          pb.ActivityType_ACTIVITY_TYPE_CROSSFIT,
		"activity_type_ebike_ride":          pb.ActivityType_ACTIVITY_TYPE_EBIKE_RIDE,
		"ebike_ride":                        pb.ActivityType_ACTIVITY_TYPE_EBIKE_RIDE,
		"e-bike ride":                       pb.ActivityType_ACTIVITY_TYPE_EBIKE_RIDE,
		"activity_type_elliptical":          pb.ActivityType_ACTIVITY_TYPE_ELLIPTICAL,
		"elliptical":                        pb.ActivityType_ACTIVITY_TYPE_ELLIPTICAL,
		"activity_type_emountain_bike_ride": pb.ActivityType_ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE,
		"emountain_bike_ride":               pb.ActivityType_ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE,
		"e-mountain bike ride":              pb.ActivityType_ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE,
		"activity_type_golf":                pb.ActivityType_ACTIVITY_TYPE_GOLF,
		"golf":                              pb.ActivityType_ACTIVITY_TYPE_GOLF,
		"activity_type_gravel_ride":         pb.ActivityType_ACTIVITY_TYPE_GRAVEL_RIDE,
		"gravel_ride":                       pb.ActivityType_ACTIVITY_TYPE_GRAVEL_RIDE,
		"gravel ride":                       pb.ActivityType_ACTIVITY_TYPE_GRAVEL_RIDE,
		"activity_type_handcycle":           pb.ActivityType_ACTIVITY_TYPE_HANDCYCLE,
		"handcycle":                         pb.ActivityType_ACTIVITY_TYPE_HANDCYCLE,
		"activity_type_high_intensity_interval_training": pb.ActivityType_ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING,
		"high_intensity_interval_training":               pb.ActivityType_ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING,
		"hiit":                                           pb.ActivityType_ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING,
		"activity_type_hike":                             pb.ActivityType_ACTIVITY_TYPE_HIKE,
		"hike":                                           pb.ActivityType_ACTIVITY_TYPE_HIKE,
		"activity_type_ice_skate":                        pb.ActivityType_ACTIVITY_TYPE_ICE_SKATE,
		"ice_skate":                                      pb.ActivityType_ACTIVITY_TYPE_ICE_SKATE,
		"ice skate":                                      pb.ActivityType_ACTIVITY_TYPE_ICE_SKATE,
		"activity_type_inline_skate":                     pb.ActivityType_ACTIVITY_TYPE_INLINE_SKATE,
		"inline_skate":                                   pb.ActivityType_ACTIVITY_TYPE_INLINE_SKATE,
		"inline skate":                                   pb.ActivityType_ACTIVITY_TYPE_INLINE_SKATE,
		"activity_type_kayaking":                         pb.ActivityType_ACTIVITY_TYPE_KAYAKING,
		"kayaking":                                       pb.ActivityType_ACTIVITY_TYPE_KAYAKING,
		"activity_type_kitesurf":                         pb.ActivityType_ACTIVITY_TYPE_KITESURF,
		"kitesurf":                                       pb.ActivityType_ACTIVITY_TYPE_KITESURF,
		"activity_type_mountain_bike_ride":               pb.ActivityType_ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE,
		"mountain_bike_ride":                             pb.ActivityType_ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE,
		"mountain bike ride":                             pb.ActivityType_ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE,
		"activity_type_nordic_ski":                       pb.ActivityType_ACTIVITY_TYPE_NORDIC_SKI,
		"nordic_ski":                                     pb.ActivityType_ACTIVITY_TYPE_NORDIC_SKI,
		"nordic ski":                                     pb.ActivityType_ACTIVITY_TYPE_NORDIC_SKI,
		"activity_type_pickleball":                       pb.ActivityType_ACTIVITY_TYPE_PICKLEBALL,
		"pickleball":                                     pb.ActivityType_ACTIVITY_TYPE_PICKLEBALL,
		"activity_type_pilates":                          pb.ActivityType_ACTIVITY_TYPE_PILATES,
		"pilates":                                        pb.ActivityType_ACTIVITY_TYPE_PILATES,
		"activity_type_racquetball":                      pb.ActivityType_ACTIVITY_TYPE_RACQUETBALL,
		"racquetball":                                    pb.ActivityType_ACTIVITY_TYPE_RACQUETBALL,
		"activity_type_ride":                             pb.ActivityType_ACTIVITY_TYPE_RIDE,
		"ride":                                           pb.ActivityType_ACTIVITY_TYPE_RIDE,
		"activity_type_rock_climbing":                    pb.ActivityType_ACTIVITY_TYPE_ROCK_CLIMBING,
		"rock_climbing":                                  pb.ActivityType_ACTIVITY_TYPE_ROCK_CLIMBING,
		"rock climbing":                                  pb.ActivityType_ACTIVITY_TYPE_ROCK_CLIMBING,
		"activity_type_roller_ski":                       pb.ActivityType_ACTIVITY_TYPE_ROLLER_SKI,
		"roller_ski":                                     pb.ActivityType_ACTIVITY_TYPE_ROLLER_SKI,
		"roller ski":                                     pb.ActivityType_ACTIVITY_TYPE_ROLLER_SKI,
		"activity_type_rowing":                           pb.ActivityType_ACTIVITY_TYPE_ROWING,
		"rowing":                                         pb.ActivityType_ACTIVITY_TYPE_ROWING,
		"activity_type_run":                              pb.ActivityType_ACTIVITY_TYPE_RUN,
		"run":                                            pb.ActivityType_ACTIVITY_TYPE_RUN,
		"activity_type_sail":                             pb.ActivityType_ACTIVITY_TYPE_SAIL,
		"sail":                                           pb.ActivityType_ACTIVITY_TYPE_SAIL,
		"activity_type_skateboard":                       pb.ActivityType_ACTIVITY_TYPE_SKATEBOARD,
		"skateboard":                                     pb.ActivityType_ACTIVITY_TYPE_SKATEBOARD,
		"activity_type_snowboard":                        pb.ActivityType_ACTIVITY_TYPE_SNOWBOARD,
		"snowboard":                                      pb.ActivityType_ACTIVITY_TYPE_SNOWBOARD,
		"activity_type_snowshoe":                         pb.ActivityType_ACTIVITY_TYPE_SNOWSHOE,
		"snowshoe":                                       pb.ActivityType_ACTIVITY_TYPE_SNOWSHOE,
		"activity_type_soccer":                           pb.ActivityType_ACTIVITY_TYPE_SOCCER,
		"soccer":                                         pb.ActivityType_ACTIVITY_TYPE_SOCCER,
		"activity_type_squash":                           pb.ActivityType_ACTIVITY_TYPE_SQUASH,
		"squash":                                         pb.ActivityType_ACTIVITY_TYPE_SQUASH,
		"activity_type_stair_stepper":                    pb.ActivityType_ACTIVITY_TYPE_STAIR_STEPPER,
		"stair_stepper":                                  pb.ActivityType_ACTIVITY_TYPE_STAIR_STEPPER,
		"stair stepper":                                  pb.ActivityType_ACTIVITY_TYPE_STAIR_STEPPER,
		"activity_type_stand_up_paddling":                pb.ActivityType_ACTIVITY_TYPE_STAND_UP_PADDLING,
		"stand_up_paddling":                              pb.ActivityType_ACTIVITY_TYPE_STAND_UP_PADDLING,
		"stand up paddling":                              pb.ActivityType_ACTIVITY_TYPE_STAND_UP_PADDLING,
		"activity_type_surfing":                          pb.ActivityType_ACTIVITY_TYPE_SURFING,
		"surfing":                                        pb.ActivityType_ACTIVITY_TYPE_SURFING,
		"activity_type_swim":                             pb.ActivityType_ACTIVITY_TYPE_SWIM,
		"swim":                                           pb.ActivityType_ACTIVITY_TYPE_SWIM,
		"activity_type_table_tennis":                     pb.ActivityType_ACTIVITY_TYPE_TABLE_TENNIS,
		"table_tennis":                                   pb.ActivityType_ACTIVITY_TYPE_TABLE_TENNIS,
		"table tennis":                                   pb.ActivityType_ACTIVITY_TYPE_TABLE_TENNIS,
		"activity_type_tennis":                           pb.ActivityType_ACTIVITY_TYPE_TENNIS,
		"tennis":                                         pb.ActivityType_ACTIVITY_TYPE_TENNIS,
		"activity_type_trail_run":                        pb.ActivityType_ACTIVITY_TYPE_TRAIL_RUN,
		"trail_run":                                      pb.ActivityType_ACTIVITY_TYPE_TRAIL_RUN,
		"trail run":                                      pb.ActivityType_ACTIVITY_TYPE_TRAIL_RUN,
		"activity_type_velomobile":                       pb.ActivityType_ACTIVITY_TYPE_VELOMOBILE,
		"velomobile":                                     pb.ActivityType_ACTIVITY_TYPE_VELOMOBILE,
		"activity_type_virtual_ride":                     pb.ActivityType_ACTIVITY_TYPE_VIRTUAL_RIDE,
		"virtual_ride":                                   pb.ActivityType_ACTIVITY_TYPE_VIRTUAL_RIDE,
		"virtual ride":                                   pb.ActivityType_ACTIVITY_TYPE_VIRTUAL_RIDE,
		"activity_type_virtual_row":                      pb.ActivityType_ACTIVITY_TYPE_VIRTUAL_ROW,
		"virtual_row":                                    pb.ActivityType_ACTIVITY_TYPE_VIRTUAL_ROW,
		"virtual row":                                    pb.ActivityType_ACTIVITY_TYPE_VIRTUAL_ROW,
		"activity_type_virtual_run":                      pb.ActivityType_ACTIVITY_TYPE_VIRTUAL_RUN,
		"virtual_run":                                    pb.ActivityType_ACTIVITY_TYPE_VIRTUAL_RUN,
		"virtual run":                                    pb.ActivityType_ACTIVITY_TYPE_VIRTUAL_RUN,
		"activity_type_walk":                             pb.ActivityType_ACTIVITY_TYPE_WALK,
		"walk":                                           pb.ActivityType_ACTIVITY_TYPE_WALK,
		"activity_type_weight_training":                  pb.ActivityType_ACTIVITY_TYPE_WEIGHT_TRAINING,
		"weight_training":                                pb.ActivityType_ACTIVITY_TYPE_WEIGHT_TRAINING,
		"weight training":                                pb.ActivityType_ACTIVITY_TYPE_WEIGHT_TRAINING,
		"activity_type_wheelchair":                       pb.ActivityType_ACTIVITY_TYPE_WHEELCHAIR,
		"wheelchair":                                     pb.ActivityType_ACTIVITY_TYPE_WHEELCHAIR,
		"activity_type_windsurf":                         pb.ActivityType_ACTIVITY_TYPE_WINDSURF,
		"windsurf":                                       pb.ActivityType_ACTIVITY_TYPE_WINDSURF,
		"activity_type_workout":                          pb.ActivityType_ACTIVITY_TYPE_WORKOUT,
		"activity_type_yoga":                             pb.ActivityType_ACTIVITY_TYPE_YOGA,
		"yoga":                                           pb.ActivityType_ACTIVITY_TYPE_YOGA,
		"running":                                        pb.ActivityType_ACTIVITY_TYPE_RUN,
		"cycling":                                        pb.ActivityType_ACTIVITY_TYPE_RIDE,
		"biking":                                         pb.ActivityType_ACTIVITY_TYPE_RIDE,
		"bike":                                           pb.ActivityType_ACTIVITY_TYPE_RIDE,
		"swimming":                                       pb.ActivityType_ACTIVITY_TYPE_SWIM,
		"walking":                                        pb.ActivityType_ACTIVITY_TYPE_WALK,
		"hiking":                                         pb.ActivityType_ACTIVITY_TYPE_HIKE,
		"weights":                                        pb.ActivityType_ACTIVITY_TYPE_WEIGHT_TRAINING,
		"weighttraining":                                 pb.ActivityType_ACTIVITY_TYPE_WEIGHT_TRAINING,
		"strength":                                       pb.ActivityType_ACTIVITY_TYPE_WEIGHT_TRAINING,
		"trailrun":                                       pb.ActivityType_ACTIVITY_TYPE_TRAIL_RUN,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

func FormatMuscleGroup(value pb.MuscleGroup) string {
	switch value {
	case pb.MuscleGroup_MUSCLE_GROUP_UNSPECIFIED:
		return "Unknown"
	case pb.MuscleGroup_MUSCLE_GROUP_ABDOMINALS:
		return "Abdominals"
	case pb.MuscleGroup_MUSCLE_GROUP_SHOULDERS:
		return "Shoulders"
	case pb.MuscleGroup_MUSCLE_GROUP_BICEPS:
		return "Biceps"
	case pb.MuscleGroup_MUSCLE_GROUP_TRICEPS:
		return "Triceps"
	case pb.MuscleGroup_MUSCLE_GROUP_FOREARMS:
		return "Forearms"
	case pb.MuscleGroup_MUSCLE_GROUP_QUADRICEPS:
		return "Quadriceps"
	case pb.MuscleGroup_MUSCLE_GROUP_HAMSTRINGS:
		return "Hamstrings"
	case pb.MuscleGroup_MUSCLE_GROUP_CALVES:
		return "Calves"
	case pb.MuscleGroup_MUSCLE_GROUP_GLUTES:
		return "Glutes"
	case pb.MuscleGroup_MUSCLE_GROUP_ABDUCTORS:
		return "Abductors"
	case pb.MuscleGroup_MUSCLE_GROUP_ADDUCTORS:
		return "Adductors"
	case pb.MuscleGroup_MUSCLE_GROUP_LATS:
		return "Lats"
	case pb.MuscleGroup_MUSCLE_GROUP_UPPER_BACK:
		return "Upper Back"
	case pb.MuscleGroup_MUSCLE_GROUP_TRAPS:
		return "Traps"
	case pb.MuscleGroup_MUSCLE_GROUP_LOWER_BACK:
		return "Lower Back"
	case pb.MuscleGroup_MUSCLE_GROUP_CHEST:
		return "Chest"
	case pb.MuscleGroup_MUSCLE_GROUP_CARDIO:
		return "Cardio"
	case pb.MuscleGroup_MUSCLE_GROUP_NECK:
		return "Neck"
	case pb.MuscleGroup_MUSCLE_GROUP_FULL_BODY:
		return "Full Body"
	case pb.MuscleGroup_MUSCLE_GROUP_OTHER:
		return "Other"
	default:
		return "Unknown"
	}
}

func ParseMuscleGroup(input string) pb.MuscleGroup {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.MuscleGroup_value[input]; ok {
		return pb.MuscleGroup(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.MuscleGroup{
		"muscle_group_unspecified": pb.MuscleGroup_MUSCLE_GROUP_UNSPECIFIED,
		"unspecified":              pb.MuscleGroup_MUSCLE_GROUP_UNSPECIFIED,
		"unknown":                  pb.MuscleGroup_MUSCLE_GROUP_UNSPECIFIED,
		"muscle_group_abdominals":  pb.MuscleGroup_MUSCLE_GROUP_ABDOMINALS,
		"abdominals":               pb.MuscleGroup_MUSCLE_GROUP_ABDOMINALS,
		"muscle_group_shoulders":   pb.MuscleGroup_MUSCLE_GROUP_SHOULDERS,
		"shoulders":                pb.MuscleGroup_MUSCLE_GROUP_SHOULDERS,
		"muscle_group_biceps":      pb.MuscleGroup_MUSCLE_GROUP_BICEPS,
		"biceps":                   pb.MuscleGroup_MUSCLE_GROUP_BICEPS,
		"muscle_group_triceps":     pb.MuscleGroup_MUSCLE_GROUP_TRICEPS,
		"triceps":                  pb.MuscleGroup_MUSCLE_GROUP_TRICEPS,
		"muscle_group_forearms":    pb.MuscleGroup_MUSCLE_GROUP_FOREARMS,
		"forearms":                 pb.MuscleGroup_MUSCLE_GROUP_FOREARMS,
		"muscle_group_quadriceps":  pb.MuscleGroup_MUSCLE_GROUP_QUADRICEPS,
		"quadriceps":               pb.MuscleGroup_MUSCLE_GROUP_QUADRICEPS,
		"muscle_group_hamstrings":  pb.MuscleGroup_MUSCLE_GROUP_HAMSTRINGS,
		"hamstrings":               pb.MuscleGroup_MUSCLE_GROUP_HAMSTRINGS,
		"muscle_group_calves":      pb.MuscleGroup_MUSCLE_GROUP_CALVES,
		"calves":                   pb.MuscleGroup_MUSCLE_GROUP_CALVES,
		"muscle_group_glutes":      pb.MuscleGroup_MUSCLE_GROUP_GLUTES,
		"glutes":                   pb.MuscleGroup_MUSCLE_GROUP_GLUTES,
		"muscle_group_abductors":   pb.MuscleGroup_MUSCLE_GROUP_ABDUCTORS,
		"abductors":                pb.MuscleGroup_MUSCLE_GROUP_ABDUCTORS,
		"muscle_group_adductors":   pb.MuscleGroup_MUSCLE_GROUP_ADDUCTORS,
		"adductors":                pb.MuscleGroup_MUSCLE_GROUP_ADDUCTORS,
		"muscle_group_lats":        pb.MuscleGroup_MUSCLE_GROUP_LATS,
		"lats":                     pb.MuscleGroup_MUSCLE_GROUP_LATS,
		"muscle_group_upper_back":  pb.MuscleGroup_MUSCLE_GROUP_UPPER_BACK,
		"upper_back":               pb.MuscleGroup_MUSCLE_GROUP_UPPER_BACK,
		"upper back":               pb.MuscleGroup_MUSCLE_GROUP_UPPER_BACK,
		"muscle_group_traps":       pb.MuscleGroup_MUSCLE_GROUP_TRAPS,
		"traps":                    pb.MuscleGroup_MUSCLE_GROUP_TRAPS,
		"muscle_group_lower_back":  pb.MuscleGroup_MUSCLE_GROUP_LOWER_BACK,
		"lower_back":               pb.MuscleGroup_MUSCLE_GROUP_LOWER_BACK,
		"lower back":               pb.MuscleGroup_MUSCLE_GROUP_LOWER_BACK,
		"muscle_group_chest":       pb.MuscleGroup_MUSCLE_GROUP_CHEST,
		"chest":                    pb.MuscleGroup_MUSCLE_GROUP_CHEST,
		"muscle_group_cardio":      pb.MuscleGroup_MUSCLE_GROUP_CARDIO,
		"cardio":                   pb.MuscleGroup_MUSCLE_GROUP_CARDIO,
		"muscle_group_neck":        pb.MuscleGroup_MUSCLE_GROUP_NECK,
		"neck":                     pb.MuscleGroup_MUSCLE_GROUP_NECK,
		"muscle_group_full_body":   pb.MuscleGroup_MUSCLE_GROUP_FULL_BODY,
		"full_body":                pb.MuscleGroup_MUSCLE_GROUP_FULL_BODY,
		"full body":                pb.MuscleGroup_MUSCLE_GROUP_FULL_BODY,
		"muscle_group_other":       pb.MuscleGroup_MUSCLE_GROUP_OTHER,
		"other":                    pb.MuscleGroup_MUSCLE_GROUP_OTHER,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.MuscleGroup_MUSCLE_GROUP_UNSPECIFIED
}

func FormatDestination(value pb.Destination) string {
	switch value {
	case pb.Destination_DESTINATION_UNSPECIFIED:
		return "Unknown"
	case pb.Destination_DESTINATION_STRAVA:
		return "Strava"
	case pb.Destination_DESTINATION_SHOWCASE:
		return "Showcase"
	case pb.Destination_DESTINATION_HEVY:
		return "Hevy"
	case pb.Destination_DESTINATION_TRAININGPEAKS:
		return "Trainingpeaks"
	case pb.Destination_DESTINATION_INTERVALS:
		return "Intervals"
	case pb.Destination_DESTINATION_GOOGLESHEETS:
		return "Googlesheets"
	case pb.Destination_DESTINATION_GITHUB:
		return "Github"
	case pb.Destination_DESTINATION_MOCK:
		return "Mock"
	default:
		return "Unknown"
	}
}

func ParseDestination(input string) pb.Destination {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.Destination_value[input]; ok {
		return pb.Destination(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.Destination{
		"destination_unspecified":   pb.Destination_DESTINATION_UNSPECIFIED,
		"unspecified":               pb.Destination_DESTINATION_UNSPECIFIED,
		"unknown":                   pb.Destination_DESTINATION_UNSPECIFIED,
		"destination_strava":        pb.Destination_DESTINATION_STRAVA,
		"strava":                    pb.Destination_DESTINATION_STRAVA,
		"destination_showcase":      pb.Destination_DESTINATION_SHOWCASE,
		"showcase":                  pb.Destination_DESTINATION_SHOWCASE,
		"destination_hevy":          pb.Destination_DESTINATION_HEVY,
		"hevy":                      pb.Destination_DESTINATION_HEVY,
		"destination_trainingpeaks": pb.Destination_DESTINATION_TRAININGPEAKS,
		"trainingpeaks":             pb.Destination_DESTINATION_TRAININGPEAKS,
		"destination_intervals":     pb.Destination_DESTINATION_INTERVALS,
		"intervals":                 pb.Destination_DESTINATION_INTERVALS,
		"destination_googlesheets":  pb.Destination_DESTINATION_GOOGLESHEETS,
		"googlesheets":              pb.Destination_DESTINATION_GOOGLESHEETS,
		"destination_github":        pb.Destination_DESTINATION_GITHUB,
		"github":                    pb.Destination_DESTINATION_GITHUB,
		"destination_mock":          pb.Destination_DESTINATION_MOCK,
		"mock":                      pb.Destination_DESTINATION_MOCK,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.Destination_DESTINATION_UNSPECIFIED
}

func FormatCloudEventType(value pb.CloudEventType) string {
	switch value {
	case pb.CloudEventType_CLOUD_EVENT_TYPE_UNSPECIFIED:
		return "Unspecified"
	case pb.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_CREATED:
		return "Activity Created"
	case pb.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_ENRICHED:
		return "Activity Enriched"
	case pb.CloudEventType_CLOUD_EVENT_TYPE_JOB_ROUTED:
		return "Job Routed"
	case pb.CloudEventType_CLOUD_EVENT_TYPE_FITBIT_NOTIFICATION:
		return "Fitbit Notification"
	case pb.CloudEventType_CLOUD_EVENT_TYPE_ENRICHMENT_LAG:
		return "Enrichment Lag"
	case pb.CloudEventType_CLOUD_EVENT_TYPE_INPUT_RESOLVED:
		return "Input Resolved"
	case pb.CloudEventType_CLOUD_EVENT_TYPE_PARKRUN_RESULTS:
		return "Parkrun Results"
	default:
		return "Unknown"
	}
}

func ParseCloudEventType(input string) pb.CloudEventType {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.CloudEventType_value[input]; ok {
		return pb.CloudEventType(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.CloudEventType{
		"cloud_event_type_unspecified":         pb.CloudEventType_CLOUD_EVENT_TYPE_UNSPECIFIED,
		"unspecified":                          pb.CloudEventType_CLOUD_EVENT_TYPE_UNSPECIFIED,
		"cloud_event_type_activity_created":    pb.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_CREATED,
		"activity_created":                     pb.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_CREATED,
		"activity created":                     pb.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_CREATED,
		"cloud_event_type_activity_enriched":   pb.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_ENRICHED,
		"activity_enriched":                    pb.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_ENRICHED,
		"activity enriched":                    pb.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_ENRICHED,
		"cloud_event_type_job_routed":          pb.CloudEventType_CLOUD_EVENT_TYPE_JOB_ROUTED,
		"job_routed":                           pb.CloudEventType_CLOUD_EVENT_TYPE_JOB_ROUTED,
		"job routed":                           pb.CloudEventType_CLOUD_EVENT_TYPE_JOB_ROUTED,
		"cloud_event_type_fitbit_notification": pb.CloudEventType_CLOUD_EVENT_TYPE_FITBIT_NOTIFICATION,
		"fitbit_notification":                  pb.CloudEventType_CLOUD_EVENT_TYPE_FITBIT_NOTIFICATION,
		"fitbit notification":                  pb.CloudEventType_CLOUD_EVENT_TYPE_FITBIT_NOTIFICATION,
		"cloud_event_type_enrichment_lag":      pb.CloudEventType_CLOUD_EVENT_TYPE_ENRICHMENT_LAG,
		"enrichment_lag":                       pb.CloudEventType_CLOUD_EVENT_TYPE_ENRICHMENT_LAG,
		"enrichment lag":                       pb.CloudEventType_CLOUD_EVENT_TYPE_ENRICHMENT_LAG,
		"cloud_event_type_input_resolved":      pb.CloudEventType_CLOUD_EVENT_TYPE_INPUT_RESOLVED,
		"input_resolved":                       pb.CloudEventType_CLOUD_EVENT_TYPE_INPUT_RESOLVED,
		"input resolved":                       pb.CloudEventType_CLOUD_EVENT_TYPE_INPUT_RESOLVED,
		"cloud_event_type_parkrun_results":     pb.CloudEventType_CLOUD_EVENT_TYPE_PARKRUN_RESULTS,
		"parkrun_results":                      pb.CloudEventType_CLOUD_EVENT_TYPE_PARKRUN_RESULTS,
		"parkrun results":                      pb.CloudEventType_CLOUD_EVENT_TYPE_PARKRUN_RESULTS,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.CloudEventType_CLOUD_EVENT_TYPE_UNSPECIFIED
}

func FormatCloudEventSource(value pb.CloudEventSource) string {
	switch value {
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_UNSPECIFIED:
		return "Unspecified"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_HEVY:
		return "Hevy"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_WEBHOOK:
		return "Fitbit Webhook"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_INGEST:
		return "Fitbit Ingest"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_ENRICHER:
		return "Enricher"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_ROUTER:
		return "Router"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_INPUTS_HANDLER:
		return "Inputs Handler"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_PARKRUN_RESULTS:
		return "Parkrun Results"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_FILE_UPLOAD:
		return "File Upload"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_STRAVA:
		return "Strava"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_OURA:
		return "Oura"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_POLAR_WEBHOOK:
		return "Polar Webhook"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_WAHOO:
		return "Wahoo"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_PIPELINE_SPLITTER:
		return "Pipeline Splitter"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_GITHUB:
		return "Github"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_MOCK:
		return "Mock"
	default:
		return "Unknown"
	}
}

func ParseCloudEventSource(input string) pb.CloudEventSource {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.CloudEventSource_value[input]; ok {
		return pb.CloudEventSource(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.CloudEventSource{
		"cloud_event_source_unspecified":       pb.CloudEventSource_CLOUD_EVENT_SOURCE_UNSPECIFIED,
		"unspecified":                          pb.CloudEventSource_CLOUD_EVENT_SOURCE_UNSPECIFIED,
		"cloud_event_source_hevy":              pb.CloudEventSource_CLOUD_EVENT_SOURCE_HEVY,
		"hevy":                                 pb.CloudEventSource_CLOUD_EVENT_SOURCE_HEVY,
		"cloud_event_source_fitbit_webhook":    pb.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_WEBHOOK,
		"fitbit_webhook":                       pb.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_WEBHOOK,
		"fitbit webhook":                       pb.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_WEBHOOK,
		"cloud_event_source_fitbit_ingest":     pb.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_INGEST,
		"fitbit_ingest":                        pb.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_INGEST,
		"fitbit ingest":                        pb.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_INGEST,
		"cloud_event_source_enricher":          pb.CloudEventSource_CLOUD_EVENT_SOURCE_ENRICHER,
		"enricher":                             pb.CloudEventSource_CLOUD_EVENT_SOURCE_ENRICHER,
		"cloud_event_source_router":            pb.CloudEventSource_CLOUD_EVENT_SOURCE_ROUTER,
		"router":                               pb.CloudEventSource_CLOUD_EVENT_SOURCE_ROUTER,
		"cloud_event_source_inputs_handler":    pb.CloudEventSource_CLOUD_EVENT_SOURCE_INPUTS_HANDLER,
		"inputs_handler":                       pb.CloudEventSource_CLOUD_EVENT_SOURCE_INPUTS_HANDLER,
		"inputs handler":                       pb.CloudEventSource_CLOUD_EVENT_SOURCE_INPUTS_HANDLER,
		"cloud_event_source_parkrun_results":   pb.CloudEventSource_CLOUD_EVENT_SOURCE_PARKRUN_RESULTS,
		"parkrun_results":                      pb.CloudEventSource_CLOUD_EVENT_SOURCE_PARKRUN_RESULTS,
		"parkrun results":                      pb.CloudEventSource_CLOUD_EVENT_SOURCE_PARKRUN_RESULTS,
		"cloud_event_source_file_upload":       pb.CloudEventSource_CLOUD_EVENT_SOURCE_FILE_UPLOAD,
		"file_upload":                          pb.CloudEventSource_CLOUD_EVENT_SOURCE_FILE_UPLOAD,
		"file upload":                          pb.CloudEventSource_CLOUD_EVENT_SOURCE_FILE_UPLOAD,
		"cloud_event_source_strava":            pb.CloudEventSource_CLOUD_EVENT_SOURCE_STRAVA,
		"strava":                               pb.CloudEventSource_CLOUD_EVENT_SOURCE_STRAVA,
		"cloud_event_source_oura":              pb.CloudEventSource_CLOUD_EVENT_SOURCE_OURA,
		"oura":                                 pb.CloudEventSource_CLOUD_EVENT_SOURCE_OURA,
		"cloud_event_source_polar_webhook":     pb.CloudEventSource_CLOUD_EVENT_SOURCE_POLAR_WEBHOOK,
		"polar_webhook":                        pb.CloudEventSource_CLOUD_EVENT_SOURCE_POLAR_WEBHOOK,
		"polar webhook":                        pb.CloudEventSource_CLOUD_EVENT_SOURCE_POLAR_WEBHOOK,
		"cloud_event_source_wahoo":             pb.CloudEventSource_CLOUD_EVENT_SOURCE_WAHOO,
		"wahoo":                                pb.CloudEventSource_CLOUD_EVENT_SOURCE_WAHOO,
		"cloud_event_source_pipeline_splitter": pb.CloudEventSource_CLOUD_EVENT_SOURCE_PIPELINE_SPLITTER,
		"pipeline_splitter":                    pb.CloudEventSource_CLOUD_EVENT_SOURCE_PIPELINE_SPLITTER,
		"pipeline splitter":                    pb.CloudEventSource_CLOUD_EVENT_SOURCE_PIPELINE_SPLITTER,
		"cloud_event_source_github":            pb.CloudEventSource_CLOUD_EVENT_SOURCE_GITHUB,
		"github":                               pb.CloudEventSource_CLOUD_EVENT_SOURCE_GITHUB,
		"cloud_event_source_mock":              pb.CloudEventSource_CLOUD_EVENT_SOURCE_MOCK,
		"mock":                                 pb.CloudEventSource_CLOUD_EVENT_SOURCE_MOCK,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.CloudEventSource_CLOUD_EVENT_SOURCE_UNSPECIFIED
}

func FormatActivitySource(value pb.ActivitySource) string {
	switch value {
	case pb.ActivitySource_SOURCE_UNKNOWN:
		return "Unknown"
	case pb.ActivitySource_SOURCE_HEVY:
		return "Hevy"
	case pb.ActivitySource_SOURCE_FITBIT:
		return "Fitbit"
	case pb.ActivitySource_SOURCE_PARKRUN_RESULTS:
		return "Parkrun Results"
	case pb.ActivitySource_SOURCE_FILE_UPLOAD:
		return "File Upload"
	case pb.ActivitySource_SOURCE_STRAVA:
		return "Strava"
	case pb.ActivitySource_SOURCE_GARMIN:
		return "Garmin"
	case pb.ActivitySource_SOURCE_APPLE_HEALTH:
		return "Apple Health"
	case pb.ActivitySource_SOURCE_HEALTH_CONNECT:
		return "Health Connect"
	case pb.ActivitySource_SOURCE_OURA:
		return "Oura"
	case pb.ActivitySource_SOURCE_POLAR:
		return "Polar"
	case pb.ActivitySource_SOURCE_WAHOO:
		return "Wahoo"
	case pb.ActivitySource_SOURCE_INTERVALS:
		return "Intervals"
	case pb.ActivitySource_SOURCE_TRAININGPEAKS:
		return "Trainingpeaks"
	case pb.ActivitySource_SOURCE_GOOGLESHEETS:
		return "Googlesheets"
	case pb.ActivitySource_SOURCE_GITHUB:
		return "Github"
	case pb.ActivitySource_SOURCE_TEST:
		return "Test"
	default:
		return "Unknown"
	}
}

func ParseActivitySource(input string) pb.ActivitySource {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.ActivitySource_value[input]; ok {
		return pb.ActivitySource(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.ActivitySource{
		"source_unknown":         pb.ActivitySource_SOURCE_UNKNOWN,
		"unknown":                pb.ActivitySource_SOURCE_UNKNOWN,
		"source_hevy":            pb.ActivitySource_SOURCE_HEVY,
		"hevy":                   pb.ActivitySource_SOURCE_HEVY,
		"source_fitbit":          pb.ActivitySource_SOURCE_FITBIT,
		"fitbit":                 pb.ActivitySource_SOURCE_FITBIT,
		"source_parkrun_results": pb.ActivitySource_SOURCE_PARKRUN_RESULTS,
		"parkrun_results":        pb.ActivitySource_SOURCE_PARKRUN_RESULTS,
		"parkrun results":        pb.ActivitySource_SOURCE_PARKRUN_RESULTS,
		"source_file_upload":     pb.ActivitySource_SOURCE_FILE_UPLOAD,
		"file_upload":            pb.ActivitySource_SOURCE_FILE_UPLOAD,
		"file upload":            pb.ActivitySource_SOURCE_FILE_UPLOAD,
		"source_strava":          pb.ActivitySource_SOURCE_STRAVA,
		"strava":                 pb.ActivitySource_SOURCE_STRAVA,
		"source_garmin":          pb.ActivitySource_SOURCE_GARMIN,
		"garmin":                 pb.ActivitySource_SOURCE_GARMIN,
		"source_apple_health":    pb.ActivitySource_SOURCE_APPLE_HEALTH,
		"apple_health":           pb.ActivitySource_SOURCE_APPLE_HEALTH,
		"apple health":           pb.ActivitySource_SOURCE_APPLE_HEALTH,
		"source_health_connect":  pb.ActivitySource_SOURCE_HEALTH_CONNECT,
		"health_connect":         pb.ActivitySource_SOURCE_HEALTH_CONNECT,
		"health connect":         pb.ActivitySource_SOURCE_HEALTH_CONNECT,
		"source_oura":            pb.ActivitySource_SOURCE_OURA,
		"oura":                   pb.ActivitySource_SOURCE_OURA,
		"source_polar":           pb.ActivitySource_SOURCE_POLAR,
		"polar":                  pb.ActivitySource_SOURCE_POLAR,
		"source_wahoo":           pb.ActivitySource_SOURCE_WAHOO,
		"wahoo":                  pb.ActivitySource_SOURCE_WAHOO,
		"source_intervals":       pb.ActivitySource_SOURCE_INTERVALS,
		"intervals":              pb.ActivitySource_SOURCE_INTERVALS,
		"source_trainingpeaks":   pb.ActivitySource_SOURCE_TRAININGPEAKS,
		"trainingpeaks":          pb.ActivitySource_SOURCE_TRAININGPEAKS,
		"source_googlesheets":    pb.ActivitySource_SOURCE_GOOGLESHEETS,
		"googlesheets":           pb.ActivitySource_SOURCE_GOOGLESHEETS,
		"source_github":          pb.ActivitySource_SOURCE_GITHUB,
		"github":                 pb.ActivitySource_SOURCE_GITHUB,
		"source_test":            pb.ActivitySource_SOURCE_TEST,
		"test":                   pb.ActivitySource_SOURCE_TEST,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.ActivitySource_SOURCE_UNKNOWN
}

func FormatEnricherProviderType(value pb.EnricherProviderType) string {
	switch value {
	case pb.EnricherProviderType_ENRICHER_PROVIDER_UNSPECIFIED:
		return "Unknown"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_FITBIT_HEART_RATE:
		return "Fitbit Heart Rate"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_WORKOUT_SUMMARY:
		return "Workout Summary"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP:
		return "Muscle Heatmap"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_SOURCE_LINK:
		return "Source Link"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_VIRTUAL_GPS:
		return "Virtual Gps"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_TYPE_MAPPER:
		return "Type Mapper"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_PARKRUN:
		return "Parkrun"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_CONDITION_MATCHER:
		return "Condition Matcher"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_AUTO_INCREMENT:
		return "Auto Increment"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_USER_INPUT:
		return "User Input"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_ACTIVITY_FILTER:
		return "Activity Filter"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_LOGIC_GATE:
		return "Logic Gate"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_HEART_RATE_SUMMARY:
		return "Heart Rate Summary"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_AI_COMPANION:
		return "Ai Companion"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_PACE_SUMMARY:
		return "Pace Summary"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_CADENCE_SUMMARY:
		return "Cadence Summary"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_POWER_SUMMARY:
		return "Power Summary"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_SPEED_SUMMARY:
		return "Speed Summary"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_PERSONAL_RECORDS:
		return "Personal Records"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_TRAINING_LOAD:
		return "Training Load"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_SPOTIFY_TRACKS:
		return "Spotify Tracks"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_WEATHER:
		return "Weather"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_ELEVATION_SUMMARY:
		return "Elevation Summary"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_LOCATION_NAMING:
		return "Location Naming"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP_IMAGE:
		return "Muscle Heatmap Image"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_ROUTE_THUMBNAIL:
		return "Route Thumbnail"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_AI_BANNER:
		return "Ai Banner"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_FIT_FILE_HEART_RATE:
		return "Fit File Heart Rate"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_HYBRID_RACE_TAGGER:
		return "Hybrid Race Tagger"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_RUNNING_DYNAMICS:
		return "Running Dynamics"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_HEART_RATE_ZONES:
		return "Heart Rate Zones"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_CALORIES_BURNED:
		return "Calories Burned"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_GOAL_TRACKER:
		return "Goal Tracker"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_STREAK_TRACKER:
		return "Streak Tracker"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_DISTANCE_MILESTONES:
		return "Distance Milestones"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_RECOVERY_ADVISOR:
		return "Recovery Advisor"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_EFFORT_SCORE:
		return "Effort Score"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_INTERVALS:
		return "Intervals"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_MOCK:
		return "Mock"
	default:
		return "Unknown"
	}
}

func ParseEnricherProviderType(input string) pb.EnricherProviderType {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.EnricherProviderType_value[input]; ok {
		return pb.EnricherProviderType(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.EnricherProviderType{
		"enricher_provider_unspecified":          pb.EnricherProviderType_ENRICHER_PROVIDER_UNSPECIFIED,
		"unspecified":                            pb.EnricherProviderType_ENRICHER_PROVIDER_UNSPECIFIED,
		"unknown":                                pb.EnricherProviderType_ENRICHER_PROVIDER_UNSPECIFIED,
		"enricher_provider_fitbit_heart_rate":    pb.EnricherProviderType_ENRICHER_PROVIDER_FITBIT_HEART_RATE,
		"fitbit_heart_rate":                      pb.EnricherProviderType_ENRICHER_PROVIDER_FITBIT_HEART_RATE,
		"fitbit heart rate":                      pb.EnricherProviderType_ENRICHER_PROVIDER_FITBIT_HEART_RATE,
		"enricher_provider_workout_summary":      pb.EnricherProviderType_ENRICHER_PROVIDER_WORKOUT_SUMMARY,
		"workout_summary":                        pb.EnricherProviderType_ENRICHER_PROVIDER_WORKOUT_SUMMARY,
		"workout summary":                        pb.EnricherProviderType_ENRICHER_PROVIDER_WORKOUT_SUMMARY,
		"enricher_provider_muscle_heatmap":       pb.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP,
		"muscle_heatmap":                         pb.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP,
		"muscle heatmap":                         pb.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP,
		"enricher_provider_source_link":          pb.EnricherProviderType_ENRICHER_PROVIDER_SOURCE_LINK,
		"source_link":                            pb.EnricherProviderType_ENRICHER_PROVIDER_SOURCE_LINK,
		"source link":                            pb.EnricherProviderType_ENRICHER_PROVIDER_SOURCE_LINK,
		"enricher_provider_virtual_gps":          pb.EnricherProviderType_ENRICHER_PROVIDER_VIRTUAL_GPS,
		"virtual_gps":                            pb.EnricherProviderType_ENRICHER_PROVIDER_VIRTUAL_GPS,
		"virtual gps":                            pb.EnricherProviderType_ENRICHER_PROVIDER_VIRTUAL_GPS,
		"enricher_provider_type_mapper":          pb.EnricherProviderType_ENRICHER_PROVIDER_TYPE_MAPPER,
		"type_mapper":                            pb.EnricherProviderType_ENRICHER_PROVIDER_TYPE_MAPPER,
		"type mapper":                            pb.EnricherProviderType_ENRICHER_PROVIDER_TYPE_MAPPER,
		"enricher_provider_parkrun":              pb.EnricherProviderType_ENRICHER_PROVIDER_PARKRUN,
		"parkrun":                                pb.EnricherProviderType_ENRICHER_PROVIDER_PARKRUN,
		"enricher_provider_condition_matcher":    pb.EnricherProviderType_ENRICHER_PROVIDER_CONDITION_MATCHER,
		"condition_matcher":                      pb.EnricherProviderType_ENRICHER_PROVIDER_CONDITION_MATCHER,
		"condition matcher":                      pb.EnricherProviderType_ENRICHER_PROVIDER_CONDITION_MATCHER,
		"enricher_provider_auto_increment":       pb.EnricherProviderType_ENRICHER_PROVIDER_AUTO_INCREMENT,
		"auto_increment":                         pb.EnricherProviderType_ENRICHER_PROVIDER_AUTO_INCREMENT,
		"auto increment":                         pb.EnricherProviderType_ENRICHER_PROVIDER_AUTO_INCREMENT,
		"enricher_provider_user_input":           pb.EnricherProviderType_ENRICHER_PROVIDER_USER_INPUT,
		"user_input":                             pb.EnricherProviderType_ENRICHER_PROVIDER_USER_INPUT,
		"user input":                             pb.EnricherProviderType_ENRICHER_PROVIDER_USER_INPUT,
		"enricher_provider_activity_filter":      pb.EnricherProviderType_ENRICHER_PROVIDER_ACTIVITY_FILTER,
		"activity_filter":                        pb.EnricherProviderType_ENRICHER_PROVIDER_ACTIVITY_FILTER,
		"activity filter":                        pb.EnricherProviderType_ENRICHER_PROVIDER_ACTIVITY_FILTER,
		"enricher_provider_logic_gate":           pb.EnricherProviderType_ENRICHER_PROVIDER_LOGIC_GATE,
		"logic_gate":                             pb.EnricherProviderType_ENRICHER_PROVIDER_LOGIC_GATE,
		"logic gate":                             pb.EnricherProviderType_ENRICHER_PROVIDER_LOGIC_GATE,
		"enricher_provider_heart_rate_summary":   pb.EnricherProviderType_ENRICHER_PROVIDER_HEART_RATE_SUMMARY,
		"heart_rate_summary":                     pb.EnricherProviderType_ENRICHER_PROVIDER_HEART_RATE_SUMMARY,
		"heart rate summary":                     pb.EnricherProviderType_ENRICHER_PROVIDER_HEART_RATE_SUMMARY,
		"enricher_provider_ai_companion":         pb.EnricherProviderType_ENRICHER_PROVIDER_AI_COMPANION,
		"ai_companion":                           pb.EnricherProviderType_ENRICHER_PROVIDER_AI_COMPANION,
		"ai companion":                           pb.EnricherProviderType_ENRICHER_PROVIDER_AI_COMPANION,
		"enricher_provider_pace_summary":         pb.EnricherProviderType_ENRICHER_PROVIDER_PACE_SUMMARY,
		"pace_summary":                           pb.EnricherProviderType_ENRICHER_PROVIDER_PACE_SUMMARY,
		"pace summary":                           pb.EnricherProviderType_ENRICHER_PROVIDER_PACE_SUMMARY,
		"enricher_provider_cadence_summary":      pb.EnricherProviderType_ENRICHER_PROVIDER_CADENCE_SUMMARY,
		"cadence_summary":                        pb.EnricherProviderType_ENRICHER_PROVIDER_CADENCE_SUMMARY,
		"cadence summary":                        pb.EnricherProviderType_ENRICHER_PROVIDER_CADENCE_SUMMARY,
		"enricher_provider_power_summary":        pb.EnricherProviderType_ENRICHER_PROVIDER_POWER_SUMMARY,
		"power_summary":                          pb.EnricherProviderType_ENRICHER_PROVIDER_POWER_SUMMARY,
		"power summary":                          pb.EnricherProviderType_ENRICHER_PROVIDER_POWER_SUMMARY,
		"enricher_provider_speed_summary":        pb.EnricherProviderType_ENRICHER_PROVIDER_SPEED_SUMMARY,
		"speed_summary":                          pb.EnricherProviderType_ENRICHER_PROVIDER_SPEED_SUMMARY,
		"speed summary":                          pb.EnricherProviderType_ENRICHER_PROVIDER_SPEED_SUMMARY,
		"enricher_provider_personal_records":     pb.EnricherProviderType_ENRICHER_PROVIDER_PERSONAL_RECORDS,
		"personal_records":                       pb.EnricherProviderType_ENRICHER_PROVIDER_PERSONAL_RECORDS,
		"personal records":                       pb.EnricherProviderType_ENRICHER_PROVIDER_PERSONAL_RECORDS,
		"enricher_provider_training_load":        pb.EnricherProviderType_ENRICHER_PROVIDER_TRAINING_LOAD,
		"training_load":                          pb.EnricherProviderType_ENRICHER_PROVIDER_TRAINING_LOAD,
		"training load":                          pb.EnricherProviderType_ENRICHER_PROVIDER_TRAINING_LOAD,
		"enricher_provider_spotify_tracks":       pb.EnricherProviderType_ENRICHER_PROVIDER_SPOTIFY_TRACKS,
		"spotify_tracks":                         pb.EnricherProviderType_ENRICHER_PROVIDER_SPOTIFY_TRACKS,
		"spotify tracks":                         pb.EnricherProviderType_ENRICHER_PROVIDER_SPOTIFY_TRACKS,
		"enricher_provider_weather":              pb.EnricherProviderType_ENRICHER_PROVIDER_WEATHER,
		"weather":                                pb.EnricherProviderType_ENRICHER_PROVIDER_WEATHER,
		"enricher_provider_elevation_summary":    pb.EnricherProviderType_ENRICHER_PROVIDER_ELEVATION_SUMMARY,
		"elevation_summary":                      pb.EnricherProviderType_ENRICHER_PROVIDER_ELEVATION_SUMMARY,
		"elevation summary":                      pb.EnricherProviderType_ENRICHER_PROVIDER_ELEVATION_SUMMARY,
		"enricher_provider_location_naming":      pb.EnricherProviderType_ENRICHER_PROVIDER_LOCATION_NAMING,
		"location_naming":                        pb.EnricherProviderType_ENRICHER_PROVIDER_LOCATION_NAMING,
		"location naming":                        pb.EnricherProviderType_ENRICHER_PROVIDER_LOCATION_NAMING,
		"enricher_provider_muscle_heatmap_image": pb.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP_IMAGE,
		"muscle_heatmap_image":                   pb.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP_IMAGE,
		"muscle heatmap image":                   pb.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP_IMAGE,
		"enricher_provider_route_thumbnail":      pb.EnricherProviderType_ENRICHER_PROVIDER_ROUTE_THUMBNAIL,
		"route_thumbnail":                        pb.EnricherProviderType_ENRICHER_PROVIDER_ROUTE_THUMBNAIL,
		"route thumbnail":                        pb.EnricherProviderType_ENRICHER_PROVIDER_ROUTE_THUMBNAIL,
		"enricher_provider_ai_banner":            pb.EnricherProviderType_ENRICHER_PROVIDER_AI_BANNER,
		"ai_banner":                              pb.EnricherProviderType_ENRICHER_PROVIDER_AI_BANNER,
		"ai banner":                              pb.EnricherProviderType_ENRICHER_PROVIDER_AI_BANNER,
		"enricher_provider_fit_file_heart_rate":  pb.EnricherProviderType_ENRICHER_PROVIDER_FIT_FILE_HEART_RATE,
		"fit_file_heart_rate":                    pb.EnricherProviderType_ENRICHER_PROVIDER_FIT_FILE_HEART_RATE,
		"fit file heart rate":                    pb.EnricherProviderType_ENRICHER_PROVIDER_FIT_FILE_HEART_RATE,
		"enricher_provider_hybrid_race_tagger":   pb.EnricherProviderType_ENRICHER_PROVIDER_HYBRID_RACE_TAGGER,
		"hybrid_race_tagger":                     pb.EnricherProviderType_ENRICHER_PROVIDER_HYBRID_RACE_TAGGER,
		"hybrid race tagger":                     pb.EnricherProviderType_ENRICHER_PROVIDER_HYBRID_RACE_TAGGER,
		"enricher_provider_running_dynamics":     pb.EnricherProviderType_ENRICHER_PROVIDER_RUNNING_DYNAMICS,
		"running_dynamics":                       pb.EnricherProviderType_ENRICHER_PROVIDER_RUNNING_DYNAMICS,
		"running dynamics":                       pb.EnricherProviderType_ENRICHER_PROVIDER_RUNNING_DYNAMICS,
		"enricher_provider_heart_rate_zones":     pb.EnricherProviderType_ENRICHER_PROVIDER_HEART_RATE_ZONES,
		"heart_rate_zones":                       pb.EnricherProviderType_ENRICHER_PROVIDER_HEART_RATE_ZONES,
		"heart rate zones":                       pb.EnricherProviderType_ENRICHER_PROVIDER_HEART_RATE_ZONES,
		"enricher_provider_calories_burned":      pb.EnricherProviderType_ENRICHER_PROVIDER_CALORIES_BURNED,
		"calories_burned":                        pb.EnricherProviderType_ENRICHER_PROVIDER_CALORIES_BURNED,
		"calories burned":                        pb.EnricherProviderType_ENRICHER_PROVIDER_CALORIES_BURNED,
		"enricher_provider_goal_tracker":         pb.EnricherProviderType_ENRICHER_PROVIDER_GOAL_TRACKER,
		"goal_tracker":                           pb.EnricherProviderType_ENRICHER_PROVIDER_GOAL_TRACKER,
		"goal tracker":                           pb.EnricherProviderType_ENRICHER_PROVIDER_GOAL_TRACKER,
		"enricher_provider_streak_tracker":       pb.EnricherProviderType_ENRICHER_PROVIDER_STREAK_TRACKER,
		"streak_tracker":                         pb.EnricherProviderType_ENRICHER_PROVIDER_STREAK_TRACKER,
		"streak tracker":                         pb.EnricherProviderType_ENRICHER_PROVIDER_STREAK_TRACKER,
		"enricher_provider_distance_milestones":  pb.EnricherProviderType_ENRICHER_PROVIDER_DISTANCE_MILESTONES,
		"distance_milestones":                    pb.EnricherProviderType_ENRICHER_PROVIDER_DISTANCE_MILESTONES,
		"distance milestones":                    pb.EnricherProviderType_ENRICHER_PROVIDER_DISTANCE_MILESTONES,
		"enricher_provider_recovery_advisor":     pb.EnricherProviderType_ENRICHER_PROVIDER_RECOVERY_ADVISOR,
		"recovery_advisor":                       pb.EnricherProviderType_ENRICHER_PROVIDER_RECOVERY_ADVISOR,
		"recovery advisor":                       pb.EnricherProviderType_ENRICHER_PROVIDER_RECOVERY_ADVISOR,
		"enricher_provider_effort_score":         pb.EnricherProviderType_ENRICHER_PROVIDER_EFFORT_SCORE,
		"effort_score":                           pb.EnricherProviderType_ENRICHER_PROVIDER_EFFORT_SCORE,
		"effort score":                           pb.EnricherProviderType_ENRICHER_PROVIDER_EFFORT_SCORE,
		"enricher_provider_intervals":            pb.EnricherProviderType_ENRICHER_PROVIDER_INTERVALS,
		"intervals":                              pb.EnricherProviderType_ENRICHER_PROVIDER_INTERVALS,
		"enricher_provider_mock":                 pb.EnricherProviderType_ENRICHER_PROVIDER_MOCK,
		"mock":                                   pb.EnricherProviderType_ENRICHER_PROVIDER_MOCK,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.EnricherProviderType_ENRICHER_PROVIDER_UNSPECIFIED
}

func FormatUserTier(value pb.UserTier) string {
	switch value {
	case pb.UserTier_USER_TIER_UNSPECIFIED:
		return "Hobbyist"
	case pb.UserTier_USER_TIER_HOBBYIST:
		return "Hobbyist"
	case pb.UserTier_USER_TIER_ATHLETE:
		return "Athlete"
	default:
		return "Hobbyist"
	}
}

func ParseUserTier(input string) pb.UserTier {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.UserTier_value[input]; ok {
		return pb.UserTier(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.UserTier{
		"user_tier_unspecified": pb.UserTier_USER_TIER_UNSPECIFIED,
		"unspecified":           pb.UserTier_USER_TIER_UNSPECIFIED,
		"hobbyist":              pb.UserTier_USER_TIER_UNSPECIFIED,
		"user_tier_hobbyist":    pb.UserTier_USER_TIER_HOBBYIST,
		"user_tier_athlete":     pb.UserTier_USER_TIER_ATHLETE,
		"athlete":               pb.UserTier_USER_TIER_ATHLETE,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.UserTier_USER_TIER_UNSPECIFIED
}

func FormatExecutionStatus(value pb.ExecutionStatus) string {
	switch value {
	case pb.ExecutionStatus_STATUS_UNKNOWN:
		return "Unknown"
	case pb.ExecutionStatus_STATUS_STARTED:
		return "Started"
	case pb.ExecutionStatus_STATUS_SUCCESS:
		return "Success"
	case pb.ExecutionStatus_STATUS_FAILED:
		return "Failed"
	case pb.ExecutionStatus_STATUS_PENDING:
		return "Pending"
	case pb.ExecutionStatus_STATUS_WAITING:
		return "Waiting"
	case pb.ExecutionStatus_STATUS_LAGGED_RETRY:
		return "Lagged Retry"
	case pb.ExecutionStatus_STATUS_SKIPPED:
		return "Skipped"
	default:
		return "Unknown"
	}
}

func ParseExecutionStatus(input string) pb.ExecutionStatus {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.ExecutionStatus_value[input]; ok {
		return pb.ExecutionStatus(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.ExecutionStatus{
		"status_unknown":      pb.ExecutionStatus_STATUS_UNKNOWN,
		"unknown":             pb.ExecutionStatus_STATUS_UNKNOWN,
		"status_started":      pb.ExecutionStatus_STATUS_STARTED,
		"started":             pb.ExecutionStatus_STATUS_STARTED,
		"status_success":      pb.ExecutionStatus_STATUS_SUCCESS,
		"success":             pb.ExecutionStatus_STATUS_SUCCESS,
		"status_failed":       pb.ExecutionStatus_STATUS_FAILED,
		"failed":              pb.ExecutionStatus_STATUS_FAILED,
		"status_pending":      pb.ExecutionStatus_STATUS_PENDING,
		"pending":             pb.ExecutionStatus_STATUS_PENDING,
		"status_waiting":      pb.ExecutionStatus_STATUS_WAITING,
		"waiting":             pb.ExecutionStatus_STATUS_WAITING,
		"status_lagged_retry": pb.ExecutionStatus_STATUS_LAGGED_RETRY,
		"lagged_retry":        pb.ExecutionStatus_STATUS_LAGGED_RETRY,
		"lagged retry":        pb.ExecutionStatus_STATUS_LAGGED_RETRY,
		"status_skipped":      pb.ExecutionStatus_STATUS_SKIPPED,
		"skipped":             pb.ExecutionStatus_STATUS_SKIPPED,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.ExecutionStatus_STATUS_UNKNOWN
}

func FormatConfigFieldType(value pb.ConfigFieldType) string {
	switch value {
	case pb.ConfigFieldType_CONFIG_FIELD_TYPE_UNSPECIFIED:
		return "Unspecified"
	case pb.ConfigFieldType_CONFIG_FIELD_TYPE_STRING:
		return "String"
	case pb.ConfigFieldType_CONFIG_FIELD_TYPE_NUMBER:
		return "Number"
	case pb.ConfigFieldType_CONFIG_FIELD_TYPE_BOOLEAN:
		return "Boolean"
	case pb.ConfigFieldType_CONFIG_FIELD_TYPE_SELECT:
		return "Select"
	case pb.ConfigFieldType_CONFIG_FIELD_TYPE_MULTI_SELECT:
		return "Multi Select"
	case pb.ConfigFieldType_CONFIG_FIELD_TYPE_KEY_VALUE_MAP:
		return "Key Value Map"
	case pb.ConfigFieldType_CONFIG_FIELD_TYPE_DYNAMIC_SELECT:
		return "Dynamic Select"
	default:
		return "String"
	}
}

func ParseConfigFieldType(input string) pb.ConfigFieldType {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.ConfigFieldType_value[input]; ok {
		return pb.ConfigFieldType(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.ConfigFieldType{
		"config_field_type_unspecified":    pb.ConfigFieldType_CONFIG_FIELD_TYPE_UNSPECIFIED,
		"unspecified":                      pb.ConfigFieldType_CONFIG_FIELD_TYPE_UNSPECIFIED,
		"config_field_type_string":         pb.ConfigFieldType_CONFIG_FIELD_TYPE_STRING,
		"string":                           pb.ConfigFieldType_CONFIG_FIELD_TYPE_STRING,
		"config_field_type_number":         pb.ConfigFieldType_CONFIG_FIELD_TYPE_NUMBER,
		"number":                           pb.ConfigFieldType_CONFIG_FIELD_TYPE_NUMBER,
		"config_field_type_boolean":        pb.ConfigFieldType_CONFIG_FIELD_TYPE_BOOLEAN,
		"boolean":                          pb.ConfigFieldType_CONFIG_FIELD_TYPE_BOOLEAN,
		"config_field_type_select":         pb.ConfigFieldType_CONFIG_FIELD_TYPE_SELECT,
		"select":                           pb.ConfigFieldType_CONFIG_FIELD_TYPE_SELECT,
		"config_field_type_multi_select":   pb.ConfigFieldType_CONFIG_FIELD_TYPE_MULTI_SELECT,
		"multi_select":                     pb.ConfigFieldType_CONFIG_FIELD_TYPE_MULTI_SELECT,
		"multi select":                     pb.ConfigFieldType_CONFIG_FIELD_TYPE_MULTI_SELECT,
		"config_field_type_key_value_map":  pb.ConfigFieldType_CONFIG_FIELD_TYPE_KEY_VALUE_MAP,
		"key_value_map":                    pb.ConfigFieldType_CONFIG_FIELD_TYPE_KEY_VALUE_MAP,
		"key value map":                    pb.ConfigFieldType_CONFIG_FIELD_TYPE_KEY_VALUE_MAP,
		"config_field_type_dynamic_select": pb.ConfigFieldType_CONFIG_FIELD_TYPE_DYNAMIC_SELECT,
		"dynamic_select":                   pb.ConfigFieldType_CONFIG_FIELD_TYPE_DYNAMIC_SELECT,
		"dynamic select":                   pb.ConfigFieldType_CONFIG_FIELD_TYPE_DYNAMIC_SELECT,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.ConfigFieldType_CONFIG_FIELD_TYPE_UNSPECIFIED
}

func FormatIntegrationAuthType(value pb.IntegrationAuthType) string {
	switch value {
	case pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_UNSPECIFIED:
		return "Manual"
	case pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_OAUTH:
		return "Oauth"
	case pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_API_KEY:
		return "API Key"
	case pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_APP_SYNC:
		return "App Sync"
	case pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_PUBLIC_ID:
		return "Public ID"
	default:
		return "Manual"
	}
}

func ParseIntegrationAuthType(input string) pb.IntegrationAuthType {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.IntegrationAuthType_value[input]; ok {
		return pb.IntegrationAuthType(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.IntegrationAuthType{
		"integration_auth_type_unspecified": pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_UNSPECIFIED,
		"unspecified":                       pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_UNSPECIFIED,
		"manual":                            pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_UNSPECIFIED,
		"integration_auth_type_oauth":       pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_OAUTH,
		"oauth":                             pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_OAUTH,
		"integration_auth_type_api_key":     pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_API_KEY,
		"api_key":                           pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_API_KEY,
		"api key":                           pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_API_KEY,
		"integration_auth_type_app_sync":    pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_APP_SYNC,
		"app_sync":                          pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_APP_SYNC,
		"app sync":                          pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_APP_SYNC,
		"integration_auth_type_public_id":   pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_PUBLIC_ID,
		"public_id":                         pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_PUBLIC_ID,
		"public id":                         pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_PUBLIC_ID,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.IntegrationAuthType_INTEGRATION_AUTH_TYPE_UNSPECIFIED
}

func FormatPluginType(value pb.PluginType) string {
	switch value {
	case pb.PluginType_PLUGIN_TYPE_UNSPECIFIED:
		return "Unspecified"
	case pb.PluginType_PLUGIN_TYPE_SOURCE:
		return "Source"
	case pb.PluginType_PLUGIN_TYPE_ENRICHER:
		return "Enricher"
	case pb.PluginType_PLUGIN_TYPE_DESTINATION:
		return "Destination"
	default:
		return "Unknown"
	}
}

func ParsePluginType(input string) pb.PluginType {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.PluginType_value[input]; ok {
		return pb.PluginType(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.PluginType{
		"plugin_type_unspecified": pb.PluginType_PLUGIN_TYPE_UNSPECIFIED,
		"unspecified":             pb.PluginType_PLUGIN_TYPE_UNSPECIFIED,
		"plugin_type_source":      pb.PluginType_PLUGIN_TYPE_SOURCE,
		"source":                  pb.PluginType_PLUGIN_TYPE_SOURCE,
		"plugin_type_enricher":    pb.PluginType_PLUGIN_TYPE_ENRICHER,
		"enricher":                pb.PluginType_PLUGIN_TYPE_ENRICHER,
		"plugin_type_destination": pb.PluginType_PLUGIN_TYPE_DESTINATION,
		"destination":             pb.PluginType_PLUGIN_TYPE_DESTINATION,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.PluginType_PLUGIN_TYPE_UNSPECIFIED
}

func FormatMuscleHeatmapPreset(value pb.MuscleHeatmapPreset) string {
	switch value {
	case pb.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_UNSPECIFIED:
		return "Unspecified"
	case pb.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_STANDARD:
		return "Standard"
	case pb.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_POWERLIFTING:
		return "Powerlifting"
	case pb.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_BODYBUILDING:
		return "Bodybuilding"
	default:
		return "Standard"
	}
}

func ParseMuscleHeatmapPreset(input string) pb.MuscleHeatmapPreset {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.MuscleHeatmapPreset_value[input]; ok {
		return pb.MuscleHeatmapPreset(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.MuscleHeatmapPreset{
		"muscle_heatmap_preset_unspecified":  pb.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_UNSPECIFIED,
		"unspecified":                        pb.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_UNSPECIFIED,
		"muscle_heatmap_preset_standard":     pb.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_STANDARD,
		"standard":                           pb.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_STANDARD,
		"muscle_heatmap_preset_powerlifting": pb.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_POWERLIFTING,
		"powerlifting":                       pb.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_POWERLIFTING,
		"muscle_heatmap_preset_bodybuilding": pb.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_BODYBUILDING,
		"bodybuilding":                       pb.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_BODYBUILDING,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_UNSPECIFIED
}

func FormatMuscleHeatmapStyle(value pb.MuscleHeatmapStyle) string {
	switch value {
	case pb.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_UNSPECIFIED:
		return "Unspecified"
	case pb.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_EMOJI_BARS:
		return "Emoji Bars"
	case pb.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_PERCENTAGE:
		return "Percentage"
	case pb.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_TEXT_ONLY:
		return "Text Only"
	default:
		return "Emoji Bars"
	}
}

func ParseMuscleHeatmapStyle(input string) pb.MuscleHeatmapStyle {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.MuscleHeatmapStyle_value[input]; ok {
		return pb.MuscleHeatmapStyle(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.MuscleHeatmapStyle{
		"muscle_heatmap_style_unspecified": pb.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_UNSPECIFIED,
		"unspecified":                      pb.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_UNSPECIFIED,
		"muscle_heatmap_style_emoji_bars":  pb.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_EMOJI_BARS,
		"emoji_bars":                       pb.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_EMOJI_BARS,
		"emoji bars":                       pb.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_EMOJI_BARS,
		"muscle_heatmap_style_percentage":  pb.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_PERCENTAGE,
		"percentage":                       pb.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_PERCENTAGE,
		"muscle_heatmap_style_text_only":   pb.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_TEXT_ONLY,
		"text_only":                        pb.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_TEXT_ONLY,
		"text only":                        pb.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_TEXT_ONLY,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_UNSPECIFIED
}

func FormatParkrunResultsState(value pb.ParkrunResultsState) string {
	switch value {
	case pb.ParkrunResultsState_PARKRUN_RESULTS_STATE_UNSPECIFIED:
		return "Unspecified"
	case pb.ParkrunResultsState_PARKRUN_RESULTS_STATE_PENDING:
		return "Pending"
	case pb.ParkrunResultsState_PARKRUN_RESULTS_STATE_COMPLETE:
		return "Complete"
	case pb.ParkrunResultsState_PARKRUN_RESULTS_STATE_EXPIRED:
		return "Expired"
	case pb.ParkrunResultsState_PARKRUN_RESULTS_STATE_IMMEDIATE:
		return "Immediate"
	default:
		return "Pending"
	}
}

func ParseParkrunResultsState(input string) pb.ParkrunResultsState {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.ParkrunResultsState_value[input]; ok {
		return pb.ParkrunResultsState(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.ParkrunResultsState{
		"parkrun_results_state_unspecified": pb.ParkrunResultsState_PARKRUN_RESULTS_STATE_UNSPECIFIED,
		"unspecified":                       pb.ParkrunResultsState_PARKRUN_RESULTS_STATE_UNSPECIFIED,
		"parkrun_results_state_pending":     pb.ParkrunResultsState_PARKRUN_RESULTS_STATE_PENDING,
		"pending":                           pb.ParkrunResultsState_PARKRUN_RESULTS_STATE_PENDING,
		"parkrun_results_state_complete":    pb.ParkrunResultsState_PARKRUN_RESULTS_STATE_COMPLETE,
		"complete":                          pb.ParkrunResultsState_PARKRUN_RESULTS_STATE_COMPLETE,
		"parkrun_results_state_expired":     pb.ParkrunResultsState_PARKRUN_RESULTS_STATE_EXPIRED,
		"expired":                           pb.ParkrunResultsState_PARKRUN_RESULTS_STATE_EXPIRED,
		"parkrun_results_state_immediate":   pb.ParkrunResultsState_PARKRUN_RESULTS_STATE_IMMEDIATE,
		"immediate":                         pb.ParkrunResultsState_PARKRUN_RESULTS_STATE_IMMEDIATE,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.ParkrunResultsState_PARKRUN_RESULTS_STATE_UNSPECIFIED
}

func FormatVirtualGPSRoute(value pb.VirtualGPSRoute) string {
	switch value {
	case pb.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_UNSPECIFIED:
		return "Unspecified"
	case pb.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_LONDON:
		return "London"
	case pb.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_NYC:
		return "Nyc"
	default:
		return "None"
	}
}

func ParseVirtualGPSRoute(input string) pb.VirtualGPSRoute {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.VirtualGPSRoute_value[input]; ok {
		return pb.VirtualGPSRoute(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.VirtualGPSRoute{
		"virtual_gps_route_unspecified": pb.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_UNSPECIFIED,
		"unspecified":                   pb.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_UNSPECIFIED,
		"virtual_gps_route_london":      pb.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_LONDON,
		"london":                        pb.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_LONDON,
		"virtual_gps_route_nyc":         pb.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_NYC,
		"nyc":                           pb.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_NYC,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_UNSPECIFIED
}

func FormatWorkoutSummaryFormat(value pb.WorkoutSummaryFormat) string {
	switch value {
	case pb.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_UNSPECIFIED:
		return "Unspecified"
	case pb.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_COMPACT:
		return "Compact"
	case pb.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_DETAILED:
		return "Detailed"
	case pb.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_VERBOSE:
		return "Verbose"
	default:
		return "Compact"
	}
}

func ParseWorkoutSummaryFormat(input string) pb.WorkoutSummaryFormat {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.WorkoutSummaryFormat_value[input]; ok {
		return pb.WorkoutSummaryFormat(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.WorkoutSummaryFormat{
		"workout_summary_format_unspecified": pb.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_UNSPECIFIED,
		"unspecified":                        pb.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_UNSPECIFIED,
		"workout_summary_format_compact":     pb.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_COMPACT,
		"compact":                            pb.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_COMPACT,
		"workout_summary_format_detailed":    pb.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_DETAILED,
		"detailed":                           pb.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_DETAILED,
		"workout_summary_format_verbose":     pb.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_VERBOSE,
		"verbose":                            pb.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_VERBOSE,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_UNSPECIFIED
}

func FormatPendingInputStatus(value pb.PendingInput_Status) string {
	switch value {
	case pb.PendingInput_STATUS_UNSPECIFIED:
		return "Unspecified"
	case pb.PendingInput_STATUS_WAITING:
		return "Waiting"
	case pb.PendingInput_STATUS_COMPLETED:
		return "Completed"
	default:
		return "Waiting"
	}
}

func ParsePendingInputStatus(input string) pb.PendingInput_Status {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.PendingInput_Status_value[input]; ok {
		return pb.PendingInput_Status(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.PendingInput_Status{
		"status_unspecified": pb.PendingInput_STATUS_UNSPECIFIED,
		"unspecified":        pb.PendingInput_STATUS_UNSPECIFIED,
		"status_waiting":     pb.PendingInput_STATUS_WAITING,
		"waiting":            pb.PendingInput_STATUS_WAITING,
		"status_completed":   pb.PendingInput_STATUS_COMPLETED,
		"completed":          pb.PendingInput_STATUS_COMPLETED,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.PendingInput_STATUS_UNSPECIFIED
}

func FormatPipelineRunStatus(value pb.PipelineRunStatus) string {
	switch value {
	case pb.PipelineRunStatus_PIPELINE_RUN_STATUS_UNSPECIFIED:
		return "Unknown"
	case pb.PipelineRunStatus_PIPELINE_RUN_STATUS_RUNNING:
		return "In Progress"
	case pb.PipelineRunStatus_PIPELINE_RUN_STATUS_SYNCED:
		return "Synced"
	case pb.PipelineRunStatus_PIPELINE_RUN_STATUS_PARTIAL:
		return "Partial"
	case pb.PipelineRunStatus_PIPELINE_RUN_STATUS_FAILED:
		return "Failed"
	case pb.PipelineRunStatus_PIPELINE_RUN_STATUS_PENDING:
		return "Pending"
	case pb.PipelineRunStatus_PIPELINE_RUN_STATUS_SKIPPED:
		return "Skipped"
	case pb.PipelineRunStatus_PIPELINE_RUN_STATUS_ARCHIVED:
		return "Archived"
	case pb.PipelineRunStatus_PIPELINE_RUN_STATUS_TIER_BLOCKED:
		return "Tier Blocked"
	default:
		return "Unknown"
	}
}

func ParsePipelineRunStatus(input string) pb.PipelineRunStatus {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.PipelineRunStatus_value[input]; ok {
		return pb.PipelineRunStatus(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.PipelineRunStatus{
		"pipeline_run_status_unspecified":  pb.PipelineRunStatus_PIPELINE_RUN_STATUS_UNSPECIFIED,
		"unspecified":                      pb.PipelineRunStatus_PIPELINE_RUN_STATUS_UNSPECIFIED,
		"unknown":                          pb.PipelineRunStatus_PIPELINE_RUN_STATUS_UNSPECIFIED,
		"pipeline_run_status_running":      pb.PipelineRunStatus_PIPELINE_RUN_STATUS_RUNNING,
		"running":                          pb.PipelineRunStatus_PIPELINE_RUN_STATUS_RUNNING,
		"in progress":                      pb.PipelineRunStatus_PIPELINE_RUN_STATUS_RUNNING,
		"pipeline_run_status_synced":       pb.PipelineRunStatus_PIPELINE_RUN_STATUS_SYNCED,
		"synced":                           pb.PipelineRunStatus_PIPELINE_RUN_STATUS_SYNCED,
		"pipeline_run_status_partial":      pb.PipelineRunStatus_PIPELINE_RUN_STATUS_PARTIAL,
		"partial":                          pb.PipelineRunStatus_PIPELINE_RUN_STATUS_PARTIAL,
		"pipeline_run_status_failed":       pb.PipelineRunStatus_PIPELINE_RUN_STATUS_FAILED,
		"failed":                           pb.PipelineRunStatus_PIPELINE_RUN_STATUS_FAILED,
		"pipeline_run_status_pending":      pb.PipelineRunStatus_PIPELINE_RUN_STATUS_PENDING,
		"pending":                          pb.PipelineRunStatus_PIPELINE_RUN_STATUS_PENDING,
		"pipeline_run_status_skipped":      pb.PipelineRunStatus_PIPELINE_RUN_STATUS_SKIPPED,
		"skipped":                          pb.PipelineRunStatus_PIPELINE_RUN_STATUS_SKIPPED,
		"pipeline_run_status_archived":     pb.PipelineRunStatus_PIPELINE_RUN_STATUS_ARCHIVED,
		"archived":                         pb.PipelineRunStatus_PIPELINE_RUN_STATUS_ARCHIVED,
		"pipeline_run_status_tier_blocked": pb.PipelineRunStatus_PIPELINE_RUN_STATUS_TIER_BLOCKED,
		"tier_blocked":                     pb.PipelineRunStatus_PIPELINE_RUN_STATUS_TIER_BLOCKED,
		"tier blocked":                     pb.PipelineRunStatus_PIPELINE_RUN_STATUS_TIER_BLOCKED,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.PipelineRunStatus_PIPELINE_RUN_STATUS_UNSPECIFIED
}

func FormatDestinationStatus(value pb.DestinationStatus) string {
	switch value {
	case pb.DestinationStatus_DESTINATION_STATUS_UNSPECIFIED:
		return "Unknown"
	case pb.DestinationStatus_DESTINATION_STATUS_PENDING:
		return "Pending"
	case pb.DestinationStatus_DESTINATION_STATUS_SUCCESS:
		return "Success"
	case pb.DestinationStatus_DESTINATION_STATUS_FAILED:
		return "Failed"
	case pb.DestinationStatus_DESTINATION_STATUS_SKIPPED:
		return "Skipped"
	default:
		return "Unknown"
	}
}

func ParseDestinationStatus(input string) pb.DestinationStatus {
	// Try exact proto enum name first (fast path)
	if v, ok := pb.DestinationStatus_value[input]; ok {
		return pb.DestinationStatus(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pb.DestinationStatus{
		"destination_status_unspecified": pb.DestinationStatus_DESTINATION_STATUS_UNSPECIFIED,
		"unspecified":                    pb.DestinationStatus_DESTINATION_STATUS_UNSPECIFIED,
		"unknown":                        pb.DestinationStatus_DESTINATION_STATUS_UNSPECIFIED,
		"destination_status_pending":     pb.DestinationStatus_DESTINATION_STATUS_PENDING,
		"pending":                        pb.DestinationStatus_DESTINATION_STATUS_PENDING,
		"destination_status_success":     pb.DestinationStatus_DESTINATION_STATUS_SUCCESS,
		"success":                        pb.DestinationStatus_DESTINATION_STATUS_SUCCESS,
		"destination_status_failed":      pb.DestinationStatus_DESTINATION_STATUS_FAILED,
		"failed":                         pb.DestinationStatus_DESTINATION_STATUS_FAILED,
		"destination_status_skipped":     pb.DestinationStatus_DESTINATION_STATUS_SKIPPED,
		"skipped":                        pb.DestinationStatus_DESTINATION_STATUS_SKIPPED,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pb.DestinationStatus_DESTINATION_STATUS_UNSPECIFIED
}
