// Code generated by generate-enum-formatters.ts. DO NOT EDIT.
package formatters

import pb "github.com/fitglue/server/src/go/pkg/types/pb"

func FormatActivityType(value pb.ActivityType) string {
	switch value {
	case pb.ActivityType_ACTIVITY_TYPE_UNSPECIFIED:
		return "Workout"
	case pb.ActivityType_ACTIVITY_TYPE_ALPINE_SKI:
		return "Alpine Ski"
	case pb.ActivityType_ACTIVITY_TYPE_BACKCOUNTRY_SKI:
		return "Backcountry Ski"
	case pb.ActivityType_ACTIVITY_TYPE_BADMINTON:
		return "Badminton"
	case pb.ActivityType_ACTIVITY_TYPE_CANOEING:
		return "Canoeing"
	case pb.ActivityType_ACTIVITY_TYPE_CROSSFIT:
		return "Crossfit"
	case pb.ActivityType_ACTIVITY_TYPE_EBIKE_RIDE:
		return "E-Bike Ride"
	case pb.ActivityType_ACTIVITY_TYPE_ELLIPTICAL:
		return "Elliptical"
	case pb.ActivityType_ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE:
		return "E-Mountain Bike Ride"
	case pb.ActivityType_ACTIVITY_TYPE_GOLF:
		return "Golf"
	case pb.ActivityType_ACTIVITY_TYPE_GRAVEL_RIDE:
		return "Gravel Ride"
	case pb.ActivityType_ACTIVITY_TYPE_HANDCYCLE:
		return "Handcycle"
	case pb.ActivityType_ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING:
		return "HIIT"
	case pb.ActivityType_ACTIVITY_TYPE_HIKE:
		return "Hike"
	case pb.ActivityType_ACTIVITY_TYPE_ICE_SKATE:
		return "Ice Skate"
	case pb.ActivityType_ACTIVITY_TYPE_INLINE_SKATE:
		return "Inline Skate"
	case pb.ActivityType_ACTIVITY_TYPE_KAYAKING:
		return "Kayaking"
	case pb.ActivityType_ACTIVITY_TYPE_KITESURF:
		return "Kitesurf"
	case pb.ActivityType_ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE:
		return "Mountain Bike Ride"
	case pb.ActivityType_ACTIVITY_TYPE_NORDIC_SKI:
		return "Nordic Ski"
	case pb.ActivityType_ACTIVITY_TYPE_PICKLEBALL:
		return "Pickleball"
	case pb.ActivityType_ACTIVITY_TYPE_PILATES:
		return "Pilates"
	case pb.ActivityType_ACTIVITY_TYPE_RACQUETBALL:
		return "Racquetball"
	case pb.ActivityType_ACTIVITY_TYPE_RIDE:
		return "Ride"
	case pb.ActivityType_ACTIVITY_TYPE_ROCK_CLIMBING:
		return "Rock Climbing"
	case pb.ActivityType_ACTIVITY_TYPE_ROLLER_SKI:
		return "Roller Ski"
	case pb.ActivityType_ACTIVITY_TYPE_ROWING:
		return "Rowing"
	case pb.ActivityType_ACTIVITY_TYPE_RUN:
		return "Run"
	case pb.ActivityType_ACTIVITY_TYPE_SAIL:
		return "Sail"
	case pb.ActivityType_ACTIVITY_TYPE_SKATEBOARD:
		return "Skateboard"
	case pb.ActivityType_ACTIVITY_TYPE_SNOWBOARD:
		return "Snowboard"
	case pb.ActivityType_ACTIVITY_TYPE_SNOWSHOE:
		return "Snowshoe"
	case pb.ActivityType_ACTIVITY_TYPE_SOCCER:
		return "Soccer"
	case pb.ActivityType_ACTIVITY_TYPE_SQUASH:
		return "Squash"
	case pb.ActivityType_ACTIVITY_TYPE_STAIR_STEPPER:
		return "Stair Stepper"
	case pb.ActivityType_ACTIVITY_TYPE_STAND_UP_PADDLING:
		return "Stand Up Paddling"
	case pb.ActivityType_ACTIVITY_TYPE_SURFING:
		return "Surfing"
	case pb.ActivityType_ACTIVITY_TYPE_SWIM:
		return "Swim"
	case pb.ActivityType_ACTIVITY_TYPE_TABLE_TENNIS:
		return "Table Tennis"
	case pb.ActivityType_ACTIVITY_TYPE_TENNIS:
		return "Tennis"
	case pb.ActivityType_ACTIVITY_TYPE_TRAIL_RUN:
		return "Trail Run"
	case pb.ActivityType_ACTIVITY_TYPE_VELOMOBILE:
		return "Velomobile"
	case pb.ActivityType_ACTIVITY_TYPE_VIRTUAL_RIDE:
		return "Virtual Ride"
	case pb.ActivityType_ACTIVITY_TYPE_VIRTUAL_ROW:
		return "Virtual Row"
	case pb.ActivityType_ACTIVITY_TYPE_VIRTUAL_RUN:
		return "Virtual Run"
	case pb.ActivityType_ACTIVITY_TYPE_WALK:
		return "Walk"
	case pb.ActivityType_ACTIVITY_TYPE_WEIGHT_TRAINING:
		return "Weight Training"
	case pb.ActivityType_ACTIVITY_TYPE_WHEELCHAIR:
		return "Wheelchair"
	case pb.ActivityType_ACTIVITY_TYPE_WINDSURF:
		return "Windsurf"
	case pb.ActivityType_ACTIVITY_TYPE_WORKOUT:
		return "Workout"
	case pb.ActivityType_ACTIVITY_TYPE_YOGA:
		return "Yoga"
	default:
		return "Workout"
	}
}

func FormatMuscleGroup(value pb.MuscleGroup) string {
	switch value {
	case pb.MuscleGroup_MUSCLE_GROUP_UNSPECIFIED:
		return "Unknown"
	case pb.MuscleGroup_MUSCLE_GROUP_ABDOMINALS:
		return "Abdominals"
	case pb.MuscleGroup_MUSCLE_GROUP_SHOULDERS:
		return "Shoulders"
	case pb.MuscleGroup_MUSCLE_GROUP_BICEPS:
		return "Biceps"
	case pb.MuscleGroup_MUSCLE_GROUP_TRICEPS:
		return "Triceps"
	case pb.MuscleGroup_MUSCLE_GROUP_FOREARMS:
		return "Forearms"
	case pb.MuscleGroup_MUSCLE_GROUP_QUADRICEPS:
		return "Quadriceps"
	case pb.MuscleGroup_MUSCLE_GROUP_HAMSTRINGS:
		return "Hamstrings"
	case pb.MuscleGroup_MUSCLE_GROUP_CALVES:
		return "Calves"
	case pb.MuscleGroup_MUSCLE_GROUP_GLUTES:
		return "Glutes"
	case pb.MuscleGroup_MUSCLE_GROUP_ABDUCTORS:
		return "Abductors"
	case pb.MuscleGroup_MUSCLE_GROUP_ADDUCTORS:
		return "Adductors"
	case pb.MuscleGroup_MUSCLE_GROUP_LATS:
		return "Lats"
	case pb.MuscleGroup_MUSCLE_GROUP_UPPER_BACK:
		return "Upper Back"
	case pb.MuscleGroup_MUSCLE_GROUP_TRAPS:
		return "Traps"
	case pb.MuscleGroup_MUSCLE_GROUP_LOWER_BACK:
		return "Lower Back"
	case pb.MuscleGroup_MUSCLE_GROUP_CHEST:
		return "Chest"
	case pb.MuscleGroup_MUSCLE_GROUP_CARDIO:
		return "Cardio"
	case pb.MuscleGroup_MUSCLE_GROUP_NECK:
		return "Neck"
	case pb.MuscleGroup_MUSCLE_GROUP_FULL_BODY:
		return "Full Body"
	case pb.MuscleGroup_MUSCLE_GROUP_OTHER:
		return "Other"
	default:
		return "Unknown"
	}
}

func FormatDestination(value pb.Destination) string {
	switch value {
	case pb.Destination_DESTINATION_UNSPECIFIED:
		return "Unknown"
	case pb.Destination_DESTINATION_STRAVA:
		return "Strava"
	case pb.Destination_DESTINATION_SHOWCASE:
		return "Showcase"
	case pb.Destination_DESTINATION_HEVY:
		return "Hevy"
	case pb.Destination_DESTINATION_TRAININGPEAKS:
		return "Trainingpeaks"
	case pb.Destination_DESTINATION_INTERVALS:
		return "Intervals"
	case pb.Destination_DESTINATION_GOOGLESHEETS:
		return "Googlesheets"
	case pb.Destination_DESTINATION_MOCK:
		return "Mock"
	default:
		return "Unknown"
	}
}

func FormatCloudEventType(value pb.CloudEventType) string {
	switch value {
	case pb.CloudEventType_CLOUD_EVENT_TYPE_UNSPECIFIED:
		return "Unspecified"
	case pb.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_CREATED:
		return "Activity Created"
	case pb.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_ENRICHED:
		return "Activity Enriched"
	case pb.CloudEventType_CLOUD_EVENT_TYPE_JOB_ROUTED:
		return "Job Routed"
	case pb.CloudEventType_CLOUD_EVENT_TYPE_FITBIT_NOTIFICATION:
		return "Fitbit Notification"
	case pb.CloudEventType_CLOUD_EVENT_TYPE_ENRICHMENT_LAG:
		return "Enrichment Lag"
	case pb.CloudEventType_CLOUD_EVENT_TYPE_INPUT_RESOLVED:
		return "Input Resolved"
	case pb.CloudEventType_CLOUD_EVENT_TYPE_PARKRUN_RESULTS:
		return "Parkrun Results"
	default:
		return "Unknown"
	}
}

func FormatCloudEventSource(value pb.CloudEventSource) string {
	switch value {
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_UNSPECIFIED:
		return "Unspecified"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_HEVY:
		return "Hevy"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_WEBHOOK:
		return "Fitbit Webhook"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_INGEST:
		return "Fitbit Ingest"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_ENRICHER:
		return "Enricher"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_ROUTER:
		return "Router"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_INPUTS_HANDLER:
		return "Inputs Handler"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_PARKRUN_RESULTS:
		return "Parkrun Results"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_FILE_UPLOAD:
		return "File Upload"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_STRAVA:
		return "Strava"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_OURA:
		return "Oura"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_POLAR_WEBHOOK:
		return "Polar Webhook"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_WAHOO:
		return "Wahoo"
	case pb.CloudEventSource_CLOUD_EVENT_SOURCE_MOCK:
		return "Mock"
	default:
		return "Unknown"
	}
}

func FormatActivitySource(value pb.ActivitySource) string {
	switch value {
	case pb.ActivitySource_SOURCE_UNKNOWN:
		return "Unknown"
	case pb.ActivitySource_SOURCE_HEVY:
		return "Hevy"
	case pb.ActivitySource_SOURCE_FITBIT:
		return "Fitbit"
	case pb.ActivitySource_SOURCE_PARKRUN_RESULTS:
		return "Parkrun Results"
	case pb.ActivitySource_SOURCE_FILE_UPLOAD:
		return "File Upload"
	case pb.ActivitySource_SOURCE_STRAVA:
		return "Strava"
	case pb.ActivitySource_SOURCE_GARMIN:
		return "Garmin"
	case pb.ActivitySource_SOURCE_APPLE_HEALTH:
		return "Apple Health"
	case pb.ActivitySource_SOURCE_HEALTH_CONNECT:
		return "Health Connect"
	case pb.ActivitySource_SOURCE_OURA:
		return "Oura"
	case pb.ActivitySource_SOURCE_POLAR:
		return "Polar"
	case pb.ActivitySource_SOURCE_WAHOO:
		return "Wahoo"
	case pb.ActivitySource_SOURCE_TEST:
		return "Test"
	default:
		return "Unknown"
	}
}

func FormatEnricherProviderType(value pb.EnricherProviderType) string {
	switch value {
	case pb.EnricherProviderType_ENRICHER_PROVIDER_UNSPECIFIED:
		return "Unknown"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_FITBIT_HEART_RATE:
		return "Fitbit Heart Rate"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_WORKOUT_SUMMARY:
		return "Workout Summary"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP:
		return "Muscle Heatmap"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_SOURCE_LINK:
		return "Source Link"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_VIRTUAL_GPS:
		return "Virtual Gps"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_TYPE_MAPPER:
		return "Type Mapper"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_PARKRUN:
		return "Parkrun"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_CONDITION_MATCHER:
		return "Condition Matcher"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_AUTO_INCREMENT:
		return "Auto Increment"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_USER_INPUT:
		return "User Input"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_ACTIVITY_FILTER:
		return "Activity Filter"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_LOGIC_GATE:
		return "Logic Gate"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_HEART_RATE_SUMMARY:
		return "Heart Rate Summary"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_AI_COMPANION:
		return "Ai Companion"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_PACE_SUMMARY:
		return "Pace Summary"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_CADENCE_SUMMARY:
		return "Cadence Summary"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_POWER_SUMMARY:
		return "Power Summary"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_SPEED_SUMMARY:
		return "Speed Summary"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_PERSONAL_RECORDS:
		return "Personal Records"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_TRAINING_LOAD:
		return "Training Load"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_SPOTIFY_TRACKS:
		return "Spotify Tracks"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_WEATHER:
		return "Weather"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_ELEVATION_SUMMARY:
		return "Elevation Summary"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_LOCATION_NAMING:
		return "Location Naming"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP_IMAGE:
		return "Muscle Heatmap Image"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_ROUTE_THUMBNAIL:
		return "Route Thumbnail"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_AI_BANNER:
		return "Ai Banner"
	case pb.EnricherProviderType_ENRICHER_PROVIDER_MOCK:
		return "Mock"
	default:
		return "Unknown"
	}
}

func FormatUserTier(value pb.UserTier) string {
	switch value {
	case pb.UserTier_USER_TIER_UNSPECIFIED:
		return "Hobbyist"
	case pb.UserTier_USER_TIER_HOBBYIST:
		return "Hobbyist"
	case pb.UserTier_USER_TIER_ATHLETE:
		return "Athlete"
	default:
		return "Hobbyist"
	}
}
