// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: services/pipeline/pipeline.proto

package pipeline

import (
	pipeline "github.com/fitglue/server/src/go/pkg/types/pb/models/pipeline"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPipelinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelinesRequest) Reset() {
	*x = ListPipelinesRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelinesRequest) ProtoMessage() {}

func (x *ListPipelinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelinesRequest.ProtoReflect.Descriptor instead.
func (*ListPipelinesRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{0}
}

func (x *ListPipelinesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListPipelinesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Pipelines     []*pipeline.PipelineConfig `protobuf:"bytes,1,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelinesResponse) Reset() {
	*x = ListPipelinesResponse{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelinesResponse) ProtoMessage() {}

func (x *ListPipelinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelinesResponse.ProtoReflect.Descriptor instead.
func (*ListPipelinesResponse) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{1}
}

func (x *ListPipelinesResponse) GetPipelines() []*pipeline.PipelineConfig {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

type GetPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PipelineId    string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineRequest) Reset() {
	*x = GetPipelineRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineRequest) ProtoMessage() {}

func (x *GetPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineRequest.ProtoReflect.Descriptor instead.
func (*GetPipelineRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{2}
}

func (x *GetPipelineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPipelineRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

type CreatePipelineRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	UserId        string                   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pipeline      *pipeline.PipelineConfig `protobuf:"bytes,2,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePipelineRequest) Reset() {
	*x = CreatePipelineRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePipelineRequest) ProtoMessage() {}

func (x *CreatePipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePipelineRequest.ProtoReflect.Descriptor instead.
func (*CreatePipelineRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePipelineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePipelineRequest) GetPipeline() *pipeline.PipelineConfig {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

type UpdatePipelineRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	UserId        string                   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PipelineId    string                   `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Pipeline      *pipeline.PipelineConfig `protobuf:"bytes,3,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePipelineRequest) Reset() {
	*x = UpdatePipelineRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePipelineRequest) ProtoMessage() {}

func (x *UpdatePipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePipelineRequest.ProtoReflect.Descriptor instead.
func (*UpdatePipelineRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePipelineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePipelineRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *UpdatePipelineRequest) GetPipeline() *pipeline.PipelineConfig {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

type DeletePipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PipelineId    string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePipelineRequest) Reset() {
	*x = DeletePipelineRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePipelineRequest) ProtoMessage() {}

func (x *DeletePipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePipelineRequest.ProtoReflect.Descriptor instead.
func (*DeletePipelineRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePipelineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeletePipelineRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

type SubmitInputRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PendingInputId string                 `protobuf:"bytes,2,opt,name=pending_input_id,json=pendingInputId,proto3" json:"pending_input_id,omitempty"`
	InputData      map[string]string      `protobuf:"bytes,3,rep,name=input_data,json=inputData,proto3" json:"input_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitInputRequest) Reset() {
	*x = SubmitInputRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitInputRequest) ProtoMessage() {}

func (x *SubmitInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitInputRequest.ProtoReflect.Descriptor instead.
func (*SubmitInputRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitInputRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitInputRequest) GetPendingInputId() string {
	if x != nil {
		return x.PendingInputId
	}
	return ""
}

func (x *SubmitInputRequest) GetInputData() map[string]string {
	if x != nil {
		return x.InputData
	}
	return nil
}

type ListPendingInputsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingInputsRequest) Reset() {
	*x = ListPendingInputsRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingInputsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingInputsRequest) ProtoMessage() {}

func (x *ListPendingInputsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingInputsRequest.ProtoReflect.Descriptor instead.
func (*ListPendingInputsRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{7}
}

func (x *ListPendingInputsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListPendingInputsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Inputs        []*pipeline.PendingInput `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingInputsResponse) Reset() {
	*x = ListPendingInputsResponse{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingInputsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingInputsResponse) ProtoMessage() {}

func (x *ListPendingInputsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingInputsResponse.ProtoReflect.Descriptor instead.
func (*ListPendingInputsResponse) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{8}
}

func (x *ListPendingInputsResponse) GetInputs() []*pipeline.PendingInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type ResolvePendingInputRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PendingInputId string                 `protobuf:"bytes,2,opt,name=pending_input_id,json=pendingInputId,proto3" json:"pending_input_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolvePendingInputRequest) Reset() {
	*x = ResolvePendingInputRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePendingInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePendingInputRequest) ProtoMessage() {}

func (x *ResolvePendingInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePendingInputRequest.ProtoReflect.Descriptor instead.
func (*ResolvePendingInputRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{9}
}

func (x *ResolvePendingInputRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResolvePendingInputRequest) GetPendingInputId() string {
	if x != nil {
		return x.PendingInputId
	}
	return ""
}

type RepostActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId    string                 `protobuf:"bytes,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepostActivityRequest) Reset() {
	*x = RepostActivityRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepostActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepostActivityRequest) ProtoMessage() {}

func (x *RepostActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepostActivityRequest.ProtoReflect.Descriptor instead.
func (*RepostActivityRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{10}
}

func (x *RepostActivityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RepostActivityRequest) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

type GetPipelineRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineRunRequest) Reset() {
	*x = GetPipelineRunRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineRunRequest) ProtoMessage() {}

func (x *GetPipelineRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineRunRequest.ProtoReflect.Descriptor instead.
func (*GetPipelineRunRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{11}
}

func (x *GetPipelineRunRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPipelineRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ListPipelineRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PipelineId    string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelineRunsRequest) Reset() {
	*x = ListPipelineRunsRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelineRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelineRunsRequest) ProtoMessage() {}

func (x *ListPipelineRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelineRunsRequest.ProtoReflect.Descriptor instead.
func (*ListPipelineRunsRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{12}
}

func (x *ListPipelineRunsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListPipelineRunsRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *ListPipelineRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPipelineRunsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListPipelineRunsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Runs          []*pipeline.PipelineRun `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	NextPageToken string                  `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelineRunsResponse) Reset() {
	*x = ListPipelineRunsResponse{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelineRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelineRunsResponse) ProtoMessage() {}

func (x *ListPipelineRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelineRunsResponse.ProtoReflect.Descriptor instead.
func (*ListPipelineRunsResponse) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{13}
}

func (x *ListPipelineRunsResponse) GetRuns() []*pipeline.PipelineRun {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *ListPipelineRunsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_services_pipeline_pipeline_proto protoreflect.FileDescriptor

const file_services_pipeline_pipeline_proto_rawDesc = "" +
	"\n" +
	" services/pipeline/pipeline.proto\x12\x19fitglue.services.pipeline\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1cmodels/pipeline/config.proto\x1a\x1fmodels/pipeline/execution.proto\x1a#models/pipeline/pending_input.proto\"/\n" +
	"\x14ListPipelinesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"^\n" +
	"\x15ListPipelinesResponse\x12E\n" +
	"\tpipelines\x18\x01 \x03(\v2'.fitglue.models.pipeline.PipelineConfigR\tpipelines\"N\n" +
	"\x12GetPipelineRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\"u\n" +
	"\x15CreatePipelineRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12C\n" +
	"\bpipeline\x18\x02 \x01(\v2'.fitglue.models.pipeline.PipelineConfigR\bpipeline\"\x96\x01\n" +
	"\x15UpdatePipelineRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12C\n" +
	"\bpipeline\x18\x03 \x01(\v2'.fitglue.models.pipeline.PipelineConfigR\bpipeline\"Q\n" +
	"\x15DeletePipelineRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\"\xf2\x01\n" +
	"\x12SubmitInputRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\x10pending_input_id\x18\x02 \x01(\tR\x0ependingInputId\x12[\n" +
	"\n" +
	"input_data\x18\x03 \x03(\v2<.fitglue.services.pipeline.SubmitInputRequest.InputDataEntryR\tinputData\x1a<\n" +
	"\x0eInputDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\x18ListPendingInputsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Z\n" +
	"\x19ListPendingInputsResponse\x12=\n" +
	"\x06inputs\x18\x01 \x03(\v2%.fitglue.models.pipeline.PendingInputR\x06inputs\"_\n" +
	"\x1aResolvePendingInputRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\x10pending_input_id\x18\x02 \x01(\tR\x0ependingInputId\"Q\n" +
	"\x15RepostActivityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\tR\n" +
	"activityId\"G\n" +
	"\x15GetPipelineRunRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"\x88\x01\n" +
	"\x17ListPipelineRunsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"|\n" +
	"\x18ListPipelineRunsResponse\x128\n" +
	"\x04runs\x18\x01 \x03(\v2$.fitglue.models.pipeline.PipelineRunR\x04runs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\x8b\x0e\n" +
	"\x0fPipelineService\x12\x99\x01\n" +
	"\rListPipelines\x12/.fitglue.services.pipeline.ListPipelinesRequest\x1a0.fitglue.services.pipeline.ListPipelinesResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v2/users/{user_id}/pipelines\x12\x9a\x01\n" +
	"\vGetPipeline\x12-.fitglue.services.pipeline.GetPipelineRequest\x1a'.fitglue.models.pipeline.PipelineConfig\"3\x82\xd3\xe4\x93\x02-\x12+/v2/users/{user_id}/pipelines/{pipeline_id}\x12\x9c\x01\n" +
	"\x0eCreatePipeline\x120.fitglue.services.pipeline.CreatePipelineRequest\x1a'.fitglue.models.pipeline.PipelineConfig\"/\x82\xd3\xe4\x93\x02):\bpipeline\"\x1d/v2/users/{user_id}/pipelines\x12\xaa\x01\n" +
	"\x0eUpdatePipeline\x120.fitglue.services.pipeline.UpdatePipelineRequest\x1a'.fitglue.models.pipeline.PipelineConfig\"=\x82\xd3\xe4\x93\x027:\bpipeline2+/v2/users/{user_id}/pipelines/{pipeline_id}\x12\x8f\x01\n" +
	"\x0eDeletePipeline\x120.fitglue.services.pipeline.DeletePipelineRequest\x1a\x16.google.protobuf.Empty\"3\x82\xd3\xe4\x93\x02-*+/v2/users/{user_id}/pipelines/{pipeline_id}\x12\x9d\x01\n" +
	"\vSubmitInput\x12-.fitglue.services.pipeline.SubmitInputRequest\x1a\x16.google.protobuf.Empty\"G\x82\xd3\xe4\x93\x02A:\x01*\"</v2/users/{user_id}/pending-inputs/{pending_input_id}/submit\x12\xaa\x01\n" +
	"\x11ListPendingInputs\x123.fitglue.services.pipeline.ListPendingInputsRequest\x1a4.fitglue.services.pipeline.ListPendingInputsResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v2/users/{user_id}/pending-inputs\x12\xae\x01\n" +
	"\x13ResolvePendingInput\x125.fitglue.services.pipeline.ResolvePendingInputRequest\x1a\x16.google.protobuf.Empty\"H\x82\xd3\xe4\x93\x02B:\x01*\"=/v2/users/{user_id}/pending-inputs/{pending_input_id}/resolve\x12\x9a\x01\n" +
	"\x0eRepostActivity\x120.fitglue.services.pipeline.RepostActivityRequest\x1a\x16.google.protobuf.Empty\">\x82\xd3\xe4\x93\x028:\x01*\"3/v2/users/{user_id}/activities/{activity_id}/repost\x12\x9c\x01\n" +
	"\x0eGetPipelineRun\x120.fitglue.services.pipeline.GetPipelineRunRequest\x1a$.fitglue.models.pipeline.PipelineRun\"2\x82\xd3\xe4\x93\x02,\x12*/v2/users/{user_id}/pipeline-runs/{run_id}\x12\xa6\x01\n" +
	"\x10ListPipelineRuns\x122.fitglue.services.pipeline.ListPipelineRunsRequest\x1a3.fitglue.services.pipeline.ListPipelineRunsResponse\")\x82\xd3\xe4\x93\x02#\x12!/v2/users/{user_id}/pipeline-runsBAZ?github.com/fitglue/server/src/go/pkg/types/pb/services/pipelineb\x06proto3"

var (
	file_services_pipeline_pipeline_proto_rawDescOnce sync.Once
	file_services_pipeline_pipeline_proto_rawDescData []byte
)

func file_services_pipeline_pipeline_proto_rawDescGZIP() []byte {
	file_services_pipeline_pipeline_proto_rawDescOnce.Do(func() {
		file_services_pipeline_pipeline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_pipeline_pipeline_proto_rawDesc), len(file_services_pipeline_pipeline_proto_rawDesc)))
	})
	return file_services_pipeline_pipeline_proto_rawDescData
}

var file_services_pipeline_pipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_services_pipeline_pipeline_proto_goTypes = []any{
	(*ListPipelinesRequest)(nil),       // 0: fitglue.services.pipeline.ListPipelinesRequest
	(*ListPipelinesResponse)(nil),      // 1: fitglue.services.pipeline.ListPipelinesResponse
	(*GetPipelineRequest)(nil),         // 2: fitglue.services.pipeline.GetPipelineRequest
	(*CreatePipelineRequest)(nil),      // 3: fitglue.services.pipeline.CreatePipelineRequest
	(*UpdatePipelineRequest)(nil),      // 4: fitglue.services.pipeline.UpdatePipelineRequest
	(*DeletePipelineRequest)(nil),      // 5: fitglue.services.pipeline.DeletePipelineRequest
	(*SubmitInputRequest)(nil),         // 6: fitglue.services.pipeline.SubmitInputRequest
	(*ListPendingInputsRequest)(nil),   // 7: fitglue.services.pipeline.ListPendingInputsRequest
	(*ListPendingInputsResponse)(nil),  // 8: fitglue.services.pipeline.ListPendingInputsResponse
	(*ResolvePendingInputRequest)(nil), // 9: fitglue.services.pipeline.ResolvePendingInputRequest
	(*RepostActivityRequest)(nil),      // 10: fitglue.services.pipeline.RepostActivityRequest
	(*GetPipelineRunRequest)(nil),      // 11: fitglue.services.pipeline.GetPipelineRunRequest
	(*ListPipelineRunsRequest)(nil),    // 12: fitglue.services.pipeline.ListPipelineRunsRequest
	(*ListPipelineRunsResponse)(nil),   // 13: fitglue.services.pipeline.ListPipelineRunsResponse
	nil,                                // 14: fitglue.services.pipeline.SubmitInputRequest.InputDataEntry
	(*pipeline.PipelineConfig)(nil),    // 15: fitglue.models.pipeline.PipelineConfig
	(*pipeline.PendingInput)(nil),      // 16: fitglue.models.pipeline.PendingInput
	(*pipeline.PipelineRun)(nil),       // 17: fitglue.models.pipeline.PipelineRun
	(*emptypb.Empty)(nil),              // 18: google.protobuf.Empty
}
var file_services_pipeline_pipeline_proto_depIdxs = []int32{
	15, // 0: fitglue.services.pipeline.ListPipelinesResponse.pipelines:type_name -> fitglue.models.pipeline.PipelineConfig
	15, // 1: fitglue.services.pipeline.CreatePipelineRequest.pipeline:type_name -> fitglue.models.pipeline.PipelineConfig
	15, // 2: fitglue.services.pipeline.UpdatePipelineRequest.pipeline:type_name -> fitglue.models.pipeline.PipelineConfig
	14, // 3: fitglue.services.pipeline.SubmitInputRequest.input_data:type_name -> fitglue.services.pipeline.SubmitInputRequest.InputDataEntry
	16, // 4: fitglue.services.pipeline.ListPendingInputsResponse.inputs:type_name -> fitglue.models.pipeline.PendingInput
	17, // 5: fitglue.services.pipeline.ListPipelineRunsResponse.runs:type_name -> fitglue.models.pipeline.PipelineRun
	0,  // 6: fitglue.services.pipeline.PipelineService.ListPipelines:input_type -> fitglue.services.pipeline.ListPipelinesRequest
	2,  // 7: fitglue.services.pipeline.PipelineService.GetPipeline:input_type -> fitglue.services.pipeline.GetPipelineRequest
	3,  // 8: fitglue.services.pipeline.PipelineService.CreatePipeline:input_type -> fitglue.services.pipeline.CreatePipelineRequest
	4,  // 9: fitglue.services.pipeline.PipelineService.UpdatePipeline:input_type -> fitglue.services.pipeline.UpdatePipelineRequest
	5,  // 10: fitglue.services.pipeline.PipelineService.DeletePipeline:input_type -> fitglue.services.pipeline.DeletePipelineRequest
	6,  // 11: fitglue.services.pipeline.PipelineService.SubmitInput:input_type -> fitglue.services.pipeline.SubmitInputRequest
	7,  // 12: fitglue.services.pipeline.PipelineService.ListPendingInputs:input_type -> fitglue.services.pipeline.ListPendingInputsRequest
	9,  // 13: fitglue.services.pipeline.PipelineService.ResolvePendingInput:input_type -> fitglue.services.pipeline.ResolvePendingInputRequest
	10, // 14: fitglue.services.pipeline.PipelineService.RepostActivity:input_type -> fitglue.services.pipeline.RepostActivityRequest
	11, // 15: fitglue.services.pipeline.PipelineService.GetPipelineRun:input_type -> fitglue.services.pipeline.GetPipelineRunRequest
	12, // 16: fitglue.services.pipeline.PipelineService.ListPipelineRuns:input_type -> fitglue.services.pipeline.ListPipelineRunsRequest
	1,  // 17: fitglue.services.pipeline.PipelineService.ListPipelines:output_type -> fitglue.services.pipeline.ListPipelinesResponse
	15, // 18: fitglue.services.pipeline.PipelineService.GetPipeline:output_type -> fitglue.models.pipeline.PipelineConfig
	15, // 19: fitglue.services.pipeline.PipelineService.CreatePipeline:output_type -> fitglue.models.pipeline.PipelineConfig
	15, // 20: fitglue.services.pipeline.PipelineService.UpdatePipeline:output_type -> fitglue.models.pipeline.PipelineConfig
	18, // 21: fitglue.services.pipeline.PipelineService.DeletePipeline:output_type -> google.protobuf.Empty
	18, // 22: fitglue.services.pipeline.PipelineService.SubmitInput:output_type -> google.protobuf.Empty
	8,  // 23: fitglue.services.pipeline.PipelineService.ListPendingInputs:output_type -> fitglue.services.pipeline.ListPendingInputsResponse
	18, // 24: fitglue.services.pipeline.PipelineService.ResolvePendingInput:output_type -> google.protobuf.Empty
	18, // 25: fitglue.services.pipeline.PipelineService.RepostActivity:output_type -> google.protobuf.Empty
	17, // 26: fitglue.services.pipeline.PipelineService.GetPipelineRun:output_type -> fitglue.models.pipeline.PipelineRun
	13, // 27: fitglue.services.pipeline.PipelineService.ListPipelineRuns:output_type -> fitglue.services.pipeline.ListPipelineRunsResponse
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_services_pipeline_pipeline_proto_init() }
func file_services_pipeline_pipeline_proto_init() {
	if File_services_pipeline_pipeline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_pipeline_pipeline_proto_rawDesc), len(file_services_pipeline_pipeline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_pipeline_pipeline_proto_goTypes,
		DependencyIndexes: file_services_pipeline_pipeline_proto_depIdxs,
		MessageInfos:      file_services_pipeline_pipeline_proto_msgTypes,
	}.Build()
	File_services_pipeline_pipeline_proto = out.File
	file_services_pipeline_pipeline_proto_goTypes = nil
	file_services_pipeline_pipeline_proto_depIdxs = nil
}
