// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.2
// source: activity.proto

/* eslint-disable */
import type { StandardizedActivity } from "./standardized_activity";

export const protobufPackage = "fitglue";

/** ActivitySource enum defines where the data originated. */
export enum ActivitySource {
  SOURCE_UNKNOWN = 0,
  SOURCE_HEVY = 1,
  SOURCE_KEISER = 2,
  SOURCE_TEST = 3,
  UNRECOGNIZED = -1,
}

/** ActivityPayload is the unified message format published to Pub/Sub. */
export interface ActivityPayload {
  source: ActivitySource;
  /** Internal FitGlue User ID */
  userId: string;
  /** ISO 8601 Timestamp of activity start */
  timestamp: string;
  /** Raw JSON payload stringified (flexible but preserved) */
  originalPayloadJson: string;
  /** Extra tracing context */
  metadata: { [key: string]: string };
  standardizedActivity: StandardizedActivity | undefined;
}

export interface ActivityPayload_MetadataEntry {
  key: string;
  value: string;
}

/** EnrichedActivityEvent is the message format for topic-enriched-activity. */
export interface EnrichedActivityEvent {
  userId: string;
  /** Unique ID for the processed activity */
  activityId: string;
  /** Path to the generated FIT file */
  gcsUri: string;
  /** Generated description/hashtags */
  description: string;
  /** Extra stats */
  metadataJson: string;
}
