// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.2
// source: events.proto

/* eslint-disable */

export const protobufPackage = "fitglue.events";

/** CloudEventType enumerates all valid event types in the system. */
export enum CloudEventType {
  CLOUD_EVENT_TYPE_UNSPECIFIED = 0,
  /** CLOUD_EVENT_TYPE_ACTIVITY_CREATED - Activity Created: Payload is ActivityPayload */
  CLOUD_EVENT_TYPE_ACTIVITY_CREATED = 1,
  /** CLOUD_EVENT_TYPE_ACTIVITY_ENRICHED - Activity Enriched: Payload is ActivityPayload */
  CLOUD_EVENT_TYPE_ACTIVITY_ENRICHED = 2,
  /** CLOUD_EVENT_TYPE_JOB_ROUTED - Job Routed: Payload is ActivityPayload */
  CLOUD_EVENT_TYPE_JOB_ROUTED = 3,
  /** CLOUD_EVENT_TYPE_FITBIT_NOTIFICATION - Fitbit Notification: Payload is FitbitNotification (raw JSON) */
  CLOUD_EVENT_TYPE_FITBIT_NOTIFICATION = 4,
  /** CLOUD_EVENT_TYPE_ENRICHMENT_LAG - Enrichment Lag: Payload is ActivityPayload */
  CLOUD_EVENT_TYPE_ENRICHMENT_LAG = 5,
  UNRECOGNIZED = -1,
}

/** CloudEventSource strings are URI references. */
export enum CloudEventSource {
  CLOUD_EVENT_SOURCE_UNSPECIFIED = 0,
  CLOUD_EVENT_SOURCE_HEVY = 1,
  CLOUD_EVENT_SOURCE_FITBIT_WEBHOOK = 2,
  CLOUD_EVENT_SOURCE_FITBIT_INGEST = 3,
  CLOUD_EVENT_SOURCE_ENRICHER = 4,
  CLOUD_EVENT_SOURCE_ROUTER = 5,
  UNRECOGNIZED = -1,
}
