// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.2
// source: standardized_activity.proto

/* eslint-disable */

export const protobufPackage = "fitglue";

/**
 * StandardizedActivity represents a normalized fitness activity.
 * It is designed to be the canonical input format for the Enricher,
 * decoupling it from specific ingestion sources (Hevy, Keiser, etc).
 *
 * Structure mimics the FIT SDK hierarchy:
 * Activity -> Sessions -> Laps -> Records
 */
export interface StandardizedActivity {
  /** e.g. "HEVY", "KEISER" */
  source: string;
  /** Source's ID (e.g. Hevy workout ID) */
  externalId: string;
  userId: string;
  /** High-level summary */
  startTime: string;
  /** e.g. "Morning Run" */
  name: string;
  /** e.g. "RUNNING", "CYCLING", "WEIGHT_TRAINING" */
  type: string;
  /** Hierarchy */
  sessions: Session[];
  /** Rich metadata (preserved from source) */
  description: string;
  tags: string[];
  notes: string;
}

export interface Session {
  startTime: string;
  /** seconds */
  totalElapsedTime: number;
  /** meters */
  totalDistance: number;
  laps: Lap[];
  /** High-fidelity strength data (not just 1Hz streams) */
  strengthSets: StrengthSet[];
}

export interface Lap {
  startTime: string;
  /** seconds */
  totalElapsedTime: number;
  /** meters */
  totalDistance: number;
  records: Record[];
}

/** Record represents a single data point in time (1Hz is typical) */
export interface Record {
  /** ISO 8601 */
  timestamp: string;
  /** Core Telemetry */
  heartRate: number;
  /** watts */
  power: number;
  /** rpm */
  cadence: number;
  /** m/s */
  speed: number;
  /** meters */
  altitude: number;
  /** Location */
  positionLat: number;
  positionLong: number;
}

/**
 * StrengthSet represents a discrete set of an exercise (common in weightlifting)
 * This is distinct from continuous Record streams.
 */
export interface StrengthSet {
  /** e.g. "Bench Press" */
  exerciseName: string;
  reps: number;
  weightKg: number;
  /** ISO 8601 */
  startTime: string;
  durationSeconds: number;
  notes: string;
  /** Organization */
  supersetId: string;
  /** Muscle Targeting */
  primaryMuscleGroup: string;
  secondaryMuscleGroups: string[];
}
