// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.2
// source: user.proto

/* eslint-disable */

export const protobufPackage = "fitglue";

export interface UserRecord {
  userId: string;
  createdAt: Date | undefined;
  integrations: UserIntegrations | undefined;
}

export interface UserIntegrations {
  hevy: HevyIntegration | undefined;
}

export interface HevyIntegration {
  enabled: boolean;
  apiKey: string;
  userId: string;
}
