// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: gateway/admin.proto

package gateway

import (
	pipeline "github.com/fitglue/server/src/go/pkg/types/pb/models/pipeline"
	user "github.com/fitglue/server/src/go/pkg/types/pb/models/user"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminEmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminEmptyResponse) Reset() {
	*x = AdminEmptyResponse{}
	mi := &file_gateway_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminEmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminEmptyResponse) ProtoMessage() {}

func (x *AdminEmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminEmptyResponse.ProtoReflect.Descriptor instead.
func (*AdminEmptyResponse) Descriptor() ([]byte, []int) {
	return file_gateway_admin_proto_rawDescGZIP(), []int{0}
}

// Platform Stats
type GetAdminStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminStatsRequest) Reset() {
	*x = GetAdminStatsRequest{}
	mi := &file_gateway_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminStatsRequest) ProtoMessage() {}

func (x *GetAdminStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminStatsRequest.ProtoReflect.Descriptor instead.
func (*GetAdminStatsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_admin_proto_rawDescGZIP(), []int{1}
}

type RecentPipelineRunCounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       int32                  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Failed        int32                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	Started       int32                  `protobuf:"varint,3,opt,name=started,proto3" json:"started,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentPipelineRunCounts) Reset() {
	*x = RecentPipelineRunCounts{}
	mi := &file_gateway_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentPipelineRunCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentPipelineRunCounts) ProtoMessage() {}

func (x *RecentPipelineRunCounts) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentPipelineRunCounts.ProtoReflect.Descriptor instead.
func (*RecentPipelineRunCounts) Descriptor() ([]byte, []int) {
	return file_gateway_admin_proto_rawDescGZIP(), []int{2}
}

func (x *RecentPipelineRunCounts) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *RecentPipelineRunCounts) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *RecentPipelineRunCounts) GetStarted() int32 {
	if x != nil {
		return x.Started
	}
	return 0
}

type GetAdminStatsResponse struct {
	state               protoimpl.MessageState   `protogen:"open.v1"`
	TotalUsers          int32                    `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	AthleteUsers        int32                    `protobuf:"varint,2,opt,name=athlete_users,json=athleteUsers,proto3" json:"athlete_users,omitempty"`
	AdminUsers          int32                    `protobuf:"varint,3,opt,name=admin_users,json=adminUsers,proto3" json:"admin_users,omitempty"`
	TotalSyncsThisMonth int32                    `protobuf:"varint,4,opt,name=total_syncs_this_month,json=totalSyncsThisMonth,proto3" json:"total_syncs_this_month,omitempty"`
	RecentExecutions    *RecentPipelineRunCounts `protobuf:"bytes,5,opt,name=recent_executions,json=recentExecutions,proto3" json:"recent_executions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetAdminStatsResponse) Reset() {
	*x = GetAdminStatsResponse{}
	mi := &file_gateway_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminStatsResponse) ProtoMessage() {}

func (x *GetAdminStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminStatsResponse.ProtoReflect.Descriptor instead.
func (*GetAdminStatsResponse) Descriptor() ([]byte, []int) {
	return file_gateway_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdminStatsResponse) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *GetAdminStatsResponse) GetAthleteUsers() int32 {
	if x != nil {
		return x.AthleteUsers
	}
	return 0
}

func (x *GetAdminStatsResponse) GetAdminUsers() int32 {
	if x != nil {
		return x.AdminUsers
	}
	return 0
}

func (x *GetAdminStatsResponse) GetTotalSyncsThisMonth() int32 {
	if x != nil {
		return x.TotalSyncsThisMonth
	}
	return 0
}

func (x *GetAdminStatsResponse) GetRecentExecutions() *RecentPipelineRunCounts {
	if x != nil {
		return x.RecentExecutions
	}
	return nil
}

// User Management
type ListUsersAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersAdminRequest) Reset() {
	*x = ListUsersAdminRequest{}
	mi := &file_gateway_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersAdminRequest) ProtoMessage() {}

func (x *ListUsersAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersAdminRequest.ProtoReflect.Descriptor instead.
func (*ListUsersAdminRequest) Descriptor() ([]byte, []int) {
	return file_gateway_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListUsersAdminRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsersAdminRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListUsersAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*user.UserProfile    `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersAdminResponse) Reset() {
	*x = ListUsersAdminResponse{}
	mi := &file_gateway_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersAdminResponse) ProtoMessage() {}

func (x *ListUsersAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersAdminResponse.ProtoReflect.Descriptor instead.
func (*ListUsersAdminResponse) Descriptor() ([]byte, []int) {
	return file_gateway_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersAdminResponse) GetUsers() []*user.UserProfile {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersAdminResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UserIdAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdAdminRequest) Reset() {
	*x = UserIdAdminRequest{}
	mi := &file_gateway_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdAdminRequest) ProtoMessage() {}

func (x *UserIdAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdAdminRequest.ProtoReflect.Descriptor instead.
func (*UserIdAdminRequest) Descriptor() ([]byte, []int) {
	return file_gateway_admin_proto_rawDescGZIP(), []int{6}
}

func (x *UserIdAdminRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateUserAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccessEnabled bool                   `protobuf:"varint,2,opt,name=access_enabled,json=accessEnabled,proto3" json:"access_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserAdminRequest) Reset() {
	*x = UpdateUserAdminRequest{}
	mi := &file_gateway_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserAdminRequest) ProtoMessage() {}

func (x *UpdateUserAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserAdminRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserAdminRequest) Descriptor() ([]byte, []int) {
	return file_gateway_admin_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserAdminRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserAdminRequest) GetAccessEnabled() bool {
	if x != nil {
		return x.AccessEnabled
	}
	return false
}

type DeleteUserDataAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DataType      string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserDataAdminRequest) Reset() {
	*x = DeleteUserDataAdminRequest{}
	mi := &file_gateway_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserDataAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserDataAdminRequest) ProtoMessage() {}

func (x *DeleteUserDataAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserDataAdminRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserDataAdminRequest) Descriptor() ([]byte, []int) {
	return file_gateway_admin_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserDataAdminRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteUserDataAdminRequest) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

// Pipeline Management
type ListAllPipelinesAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // required query param
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllPipelinesAdminRequest) Reset() {
	*x = ListAllPipelinesAdminRequest{}
	mi := &file_gateway_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllPipelinesAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllPipelinesAdminRequest) ProtoMessage() {}

func (x *ListAllPipelinesAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllPipelinesAdminRequest.ProtoReflect.Descriptor instead.
func (*ListAllPipelinesAdminRequest) Descriptor() ([]byte, []int) {
	return file_gateway_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ListAllPipelinesAdminRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListAllPipelinesAdminResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Pipelines     []*pipeline.PipelineConfig `protobuf:"bytes,1,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllPipelinesAdminResponse) Reset() {
	*x = ListAllPipelinesAdminResponse{}
	mi := &file_gateway_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllPipelinesAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllPipelinesAdminResponse) ProtoMessage() {}

func (x *ListAllPipelinesAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllPipelinesAdminResponse.ProtoReflect.Descriptor instead.
func (*ListAllPipelinesAdminResponse) Descriptor() ([]byte, []int) {
	return file_gateway_admin_proto_rawDescGZIP(), []int{10}
}

func (x *ListAllPipelinesAdminResponse) GetPipelines() []*pipeline.PipelineConfig {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

type ListPipelineRunsAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelineRunsAdminRequest) Reset() {
	*x = ListPipelineRunsAdminRequest{}
	mi := &file_gateway_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelineRunsAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelineRunsAdminRequest) ProtoMessage() {}

func (x *ListPipelineRunsAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelineRunsAdminRequest.ProtoReflect.Descriptor instead.
func (*ListPipelineRunsAdminRequest) Descriptor() ([]byte, []int) {
	return file_gateway_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ListPipelineRunsAdminRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListPipelineRunsAdminRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ListPipelineRunsAdminRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListPipelineRunsAdminRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPipelineRunsAdminRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListPipelineRunsAdminResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Runs          []*pipeline.PipelineRun `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	NextPageToken string                  `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelineRunsAdminResponse) Reset() {
	*x = ListPipelineRunsAdminResponse{}
	mi := &file_gateway_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelineRunsAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelineRunsAdminResponse) ProtoMessage() {}

func (x *ListPipelineRunsAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelineRunsAdminResponse.ProtoReflect.Descriptor instead.
func (*ListPipelineRunsAdminResponse) Descriptor() ([]byte, []int) {
	return file_gateway_admin_proto_rawDescGZIP(), []int{12}
}

func (x *ListPipelineRunsAdminResponse) GetRuns() []*pipeline.PipelineRun {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *ListPipelineRunsAdminResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_gateway_admin_proto protoreflect.FileDescriptor

const file_gateway_admin_proto_rawDesc = "" +
	"\n" +
	"\x13gateway/admin.proto\x12\x0ffitglue.gateway\x1a\x1cgoogle/api/annotations.proto\x1a\x19models/user/profile.proto\x1a\x1cmodels/pipeline/config.proto\x1a\x1fmodels/pipeline/execution.proto\"\x14\n" +
	"\x12AdminEmptyResponse\"\x16\n" +
	"\x14GetAdminStatsRequest\"e\n" +
	"\x17RecentPipelineRunCounts\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\x05R\asuccess\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x05R\x06failed\x12\x18\n" +
	"\astarted\x18\x03 \x01(\x05R\astarted\"\x8a\x02\n" +
	"\x15GetAdminStatsResponse\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x05R\n" +
	"totalUsers\x12#\n" +
	"\rathlete_users\x18\x02 \x01(\x05R\fathleteUsers\x12\x1f\n" +
	"\vadmin_users\x18\x03 \x01(\x05R\n" +
	"adminUsers\x123\n" +
	"\x16total_syncs_this_month\x18\x04 \x01(\x05R\x13totalSyncsThisMonth\x12U\n" +
	"\x11recent_executions\x18\x05 \x01(\v2(.fitglue.gateway.RecentPipelineRunCountsR\x10recentExecutions\"L\n" +
	"\x15ListUsersAdminRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"x\n" +
	"\x16ListUsersAdminResponse\x126\n" +
	"\x05users\x18\x01 \x03(\v2 .fitglue.models.user.UserProfileR\x05users\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"$\n" +
	"\x12UserIdAdminRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x16UpdateUserAdminRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eaccess_enabled\x18\x02 \x01(\bR\raccessEnabled\"I\n" +
	"\x1aDeleteUserDataAdminRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\"7\n" +
	"\x1cListAllPipelinesAdminRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"f\n" +
	"\x1dListAllPipelinesAdminResponse\x12E\n" +
	"\tpipelines\x18\x01 \x03(\v2'.fitglue.models.pipeline.PipelineConfigR\tpipelines\"\x9c\x01\n" +
	"\x1cListPipelineRunsAdminRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\x81\x01\n" +
	"\x1dListPipelineRunsAdminResponse\x128\n" +
	"\x04runs\x18\x01 \x03(\v2$.fitglue.models.pipeline.PipelineRunR\x04runs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xcd\a\n" +
	"\x13AdminGatewayService\x12i\n" +
	"\bGetStats\x12%.fitglue.gateway.GetAdminStatsRequest\x1a&.fitglue.gateway.GetAdminStatsResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/stats\x12l\n" +
	"\tListUsers\x12&.fitglue.gateway.ListUsersAdminRequest\x1a'.fitglue.gateway.ListUsersAdminResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/users\x12e\n" +
	"\aGetUser\x12#.fitglue.gateway.UserIdAdminRequest\x1a .fitglue.models.user.UserProfile\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/users/{id}\x12o\n" +
	"\n" +
	"UpdateUser\x12'.fitglue.gateway.UpdateUserAdminRequest\x1a .fitglue.models.user.UserProfile\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\x1a\v/users/{id}\x12k\n" +
	"\n" +
	"DeleteUser\x12#.fitglue.gateway.UserIdAdminRequest\x1a#.fitglue.gateway.AdminEmptyResponse\"\x13\x82\xd3\xe4\x93\x02\r*\v/users/{id}\x12\x83\x01\n" +
	"\x0eDeleteUserData\x12+.fitglue.gateway.DeleteUserDataAdminRequest\x1a#.fitglue.gateway.AdminEmptyResponse\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/users/{id}/{data_type}\x12\x85\x01\n" +
	"\x10ListAllPipelines\x12-.fitglue.gateway.ListAllPipelinesAdminRequest\x1a..fitglue.gateway.ListAllPipelinesAdminResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/pipelines\x12\x89\x01\n" +
	"\x10ListPipelineRuns\x12-.fitglue.gateway.ListPipelineRunsAdminRequest\x1a..fitglue.gateway.ListPipelineRunsAdminResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/pipeline-runsB7Z5github.com/fitglue/server/src/go/pkg/types/pb/gatewayb\x06proto3"

var (
	file_gateway_admin_proto_rawDescOnce sync.Once
	file_gateway_admin_proto_rawDescData []byte
)

func file_gateway_admin_proto_rawDescGZIP() []byte {
	file_gateway_admin_proto_rawDescOnce.Do(func() {
		file_gateway_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_admin_proto_rawDesc), len(file_gateway_admin_proto_rawDesc)))
	})
	return file_gateway_admin_proto_rawDescData
}

var file_gateway_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_gateway_admin_proto_goTypes = []any{
	(*AdminEmptyResponse)(nil),            // 0: fitglue.gateway.AdminEmptyResponse
	(*GetAdminStatsRequest)(nil),          // 1: fitglue.gateway.GetAdminStatsRequest
	(*RecentPipelineRunCounts)(nil),       // 2: fitglue.gateway.RecentPipelineRunCounts
	(*GetAdminStatsResponse)(nil),         // 3: fitglue.gateway.GetAdminStatsResponse
	(*ListUsersAdminRequest)(nil),         // 4: fitglue.gateway.ListUsersAdminRequest
	(*ListUsersAdminResponse)(nil),        // 5: fitglue.gateway.ListUsersAdminResponse
	(*UserIdAdminRequest)(nil),            // 6: fitglue.gateway.UserIdAdminRequest
	(*UpdateUserAdminRequest)(nil),        // 7: fitglue.gateway.UpdateUserAdminRequest
	(*DeleteUserDataAdminRequest)(nil),    // 8: fitglue.gateway.DeleteUserDataAdminRequest
	(*ListAllPipelinesAdminRequest)(nil),  // 9: fitglue.gateway.ListAllPipelinesAdminRequest
	(*ListAllPipelinesAdminResponse)(nil), // 10: fitglue.gateway.ListAllPipelinesAdminResponse
	(*ListPipelineRunsAdminRequest)(nil),  // 11: fitglue.gateway.ListPipelineRunsAdminRequest
	(*ListPipelineRunsAdminResponse)(nil), // 12: fitglue.gateway.ListPipelineRunsAdminResponse
	(*user.UserProfile)(nil),              // 13: fitglue.models.user.UserProfile
	(*pipeline.PipelineConfig)(nil),       // 14: fitglue.models.pipeline.PipelineConfig
	(*pipeline.PipelineRun)(nil),          // 15: fitglue.models.pipeline.PipelineRun
}
var file_gateway_admin_proto_depIdxs = []int32{
	2,  // 0: fitglue.gateway.GetAdminStatsResponse.recent_executions:type_name -> fitglue.gateway.RecentPipelineRunCounts
	13, // 1: fitglue.gateway.ListUsersAdminResponse.users:type_name -> fitglue.models.user.UserProfile
	14, // 2: fitglue.gateway.ListAllPipelinesAdminResponse.pipelines:type_name -> fitglue.models.pipeline.PipelineConfig
	15, // 3: fitglue.gateway.ListPipelineRunsAdminResponse.runs:type_name -> fitglue.models.pipeline.PipelineRun
	1,  // 4: fitglue.gateway.AdminGatewayService.GetStats:input_type -> fitglue.gateway.GetAdminStatsRequest
	4,  // 5: fitglue.gateway.AdminGatewayService.ListUsers:input_type -> fitglue.gateway.ListUsersAdminRequest
	6,  // 6: fitglue.gateway.AdminGatewayService.GetUser:input_type -> fitglue.gateway.UserIdAdminRequest
	7,  // 7: fitglue.gateway.AdminGatewayService.UpdateUser:input_type -> fitglue.gateway.UpdateUserAdminRequest
	6,  // 8: fitglue.gateway.AdminGatewayService.DeleteUser:input_type -> fitglue.gateway.UserIdAdminRequest
	8,  // 9: fitglue.gateway.AdminGatewayService.DeleteUserData:input_type -> fitglue.gateway.DeleteUserDataAdminRequest
	9,  // 10: fitglue.gateway.AdminGatewayService.ListAllPipelines:input_type -> fitglue.gateway.ListAllPipelinesAdminRequest
	11, // 11: fitglue.gateway.AdminGatewayService.ListPipelineRuns:input_type -> fitglue.gateway.ListPipelineRunsAdminRequest
	3,  // 12: fitglue.gateway.AdminGatewayService.GetStats:output_type -> fitglue.gateway.GetAdminStatsResponse
	5,  // 13: fitglue.gateway.AdminGatewayService.ListUsers:output_type -> fitglue.gateway.ListUsersAdminResponse
	13, // 14: fitglue.gateway.AdminGatewayService.GetUser:output_type -> fitglue.models.user.UserProfile
	13, // 15: fitglue.gateway.AdminGatewayService.UpdateUser:output_type -> fitglue.models.user.UserProfile
	0,  // 16: fitglue.gateway.AdminGatewayService.DeleteUser:output_type -> fitglue.gateway.AdminEmptyResponse
	0,  // 17: fitglue.gateway.AdminGatewayService.DeleteUserData:output_type -> fitglue.gateway.AdminEmptyResponse
	10, // 18: fitglue.gateway.AdminGatewayService.ListAllPipelines:output_type -> fitglue.gateway.ListAllPipelinesAdminResponse
	12, // 19: fitglue.gateway.AdminGatewayService.ListPipelineRuns:output_type -> fitglue.gateway.ListPipelineRunsAdminResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_gateway_admin_proto_init() }
func file_gateway_admin_proto_init() {
	if File_gateway_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_admin_proto_rawDesc), len(file_gateway_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_admin_proto_goTypes,
		DependencyIndexes: file_gateway_admin_proto_depIdxs,
		MessageInfos:      file_gateway_admin_proto_msgTypes,
	}.Build()
	File_gateway_admin_proto = out.File
	file_gateway_admin_proto_goTypes = nil
	file_gateway_admin_proto_depIdxs = nil
}
