// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: fitbit.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FitbitNotification represents the JSON payload sent by Fitbit Webhooks
// and published to topic-fitbit-updates.
type FitbitNotification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionType string                 `protobuf:"bytes,1,opt,name=collection_type,json=collectionType,proto3" json:"collection_type,omitempty"` // e.g. "activities"
	Date           string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`                                           // e.g. "2023-10-27"
	OwnerId        string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`                      // Fitbit User ID (e.g. "7N8X9Y")
	OwnerType      string                 `protobuf:"bytes,4,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`                // e.g. "user"
	SubscriptionId string                 `protobuf:"bytes,5,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"` // The subscription ID we created
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FitbitNotification) Reset() {
	*x = FitbitNotification{}
	mi := &file_fitbit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FitbitNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FitbitNotification) ProtoMessage() {}

func (x *FitbitNotification) ProtoReflect() protoreflect.Message {
	mi := &file_fitbit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FitbitNotification.ProtoReflect.Descriptor instead.
func (*FitbitNotification) Descriptor() ([]byte, []int) {
	return file_fitbit_proto_rawDescGZIP(), []int{0}
}

func (x *FitbitNotification) GetCollectionType() string {
	if x != nil {
		return x.CollectionType
	}
	return ""
}

func (x *FitbitNotification) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *FitbitNotification) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *FitbitNotification) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *FitbitNotification) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

var File_fitbit_proto protoreflect.FileDescriptor

const file_fitbit_proto_rawDesc = "" +
	"\n" +
	"\ffitbit.proto\x12\afitglue\"\xb4\x01\n" +
	"\x12FitbitNotification\x12'\n" +
	"\x0fcollection_type\x18\x01 \x01(\tR\x0ecollectionType\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x04 \x01(\tR\townerType\x12'\n" +
	"\x0fsubscription_id\x18\x05 \x01(\tR\x0esubscriptionIdB7Z5github.com/ripixel/fitglue-server/src/go/pkg/types/pbb\x06proto3"

var (
	file_fitbit_proto_rawDescOnce sync.Once
	file_fitbit_proto_rawDescData []byte
)

func file_fitbit_proto_rawDescGZIP() []byte {
	file_fitbit_proto_rawDescOnce.Do(func() {
		file_fitbit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fitbit_proto_rawDesc), len(file_fitbit_proto_rawDesc)))
	})
	return file_fitbit_proto_rawDescData
}

var file_fitbit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fitbit_proto_goTypes = []any{
	(*FitbitNotification)(nil), // 0: fitglue.FitbitNotification
}
var file_fitbit_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fitbit_proto_init() }
func file_fitbit_proto_init() {
	if File_fitbit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fitbit_proto_rawDesc), len(file_fitbit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fitbit_proto_goTypes,
		DependencyIndexes: file_fitbit_proto_depIdxs,
		MessageInfos:      file_fitbit_proto_msgTypes,
	}.Build()
	File_fitbit_proto = out.File
	file_fitbit_proto_goTypes = nil
	file_fitbit_proto_depIdxs = nil
}
