// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: pending_input.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PendingInput_Status int32

const (
	PendingInput_STATUS_UNSPECIFIED PendingInput_Status = 0
	PendingInput_STATUS_WAITING     PendingInput_Status = 1
	PendingInput_STATUS_COMPLETED   PendingInput_Status = 2
)

// Enum value maps for PendingInput_Status.
var (
	PendingInput_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_WAITING",
		2: "STATUS_COMPLETED",
	}
	PendingInput_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_WAITING":     1,
		"STATUS_COMPLETED":   2,
	}
)

func (x PendingInput_Status) Enum() *PendingInput_Status {
	p := new(PendingInput_Status)
	*p = x
	return p
}

func (x PendingInput_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PendingInput_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pending_input_proto_enumTypes[0].Descriptor()
}

func (PendingInput_Status) Type() protoreflect.EnumType {
	return &file_pending_input_proto_enumTypes[0]
}

func (x PendingInput_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PendingInput_Status.Descriptor instead.
func (PendingInput_Status) EnumDescriptor() ([]byte, []int) {
	return file_pending_input_proto_rawDescGZIP(), []int{0, 0}
}

// PendingInput represents a paused pipeline execution waiting for user interaction.
type PendingInput struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ActivityId string                 `protobuf:"bytes,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	UserId     string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status     PendingInput_Status    `protobuf:"varint,3,opt,name=status,proto3,enum=fitglue.PendingInput_Status" json:"status,omitempty"`
	// Fields the user interface should ask for (e.g. "title", "description")
	RequiredFields []string `protobuf:"bytes,4,rep,name=required_fields,json=requiredFields,proto3" json:"required_fields,omitempty"`
	// Data provided by the user (filled when status=COMPLETED)
	InputData map[string]string `protobuf:"bytes,5,rep,name=input_data,json=inputData,proto3" json:"input_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The original payload to be re-published once input is provided
	OriginalPayload *ActivityPayload     `protobuf:"bytes,6,opt,name=original_payload,json=originalPayload,proto3" json:"original_payload,omitempty"`
	CreatedAt       *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt     *timestamp.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PendingInput) Reset() {
	*x = PendingInput{}
	mi := &file_pending_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingInput) ProtoMessage() {}

func (x *PendingInput) ProtoReflect() protoreflect.Message {
	mi := &file_pending_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingInput.ProtoReflect.Descriptor instead.
func (*PendingInput) Descriptor() ([]byte, []int) {
	return file_pending_input_proto_rawDescGZIP(), []int{0}
}

func (x *PendingInput) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *PendingInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PendingInput) GetStatus() PendingInput_Status {
	if x != nil {
		return x.Status
	}
	return PendingInput_STATUS_UNSPECIFIED
}

func (x *PendingInput) GetRequiredFields() []string {
	if x != nil {
		return x.RequiredFields
	}
	return nil
}

func (x *PendingInput) GetInputData() map[string]string {
	if x != nil {
		return x.InputData
	}
	return nil
}

func (x *PendingInput) GetOriginalPayload() *ActivityPayload {
	if x != nil {
		return x.OriginalPayload
	}
	return nil
}

func (x *PendingInput) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PendingInput) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PendingInput) GetCompletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_pending_input_proto protoreflect.FileDescriptor

const file_pending_input_proto_rawDesc = "" +
	"\n" +
	"\x13pending_input.proto\x12\afitglue\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0eactivity.proto\"\xf0\x04\n" +
	"\fPendingInput\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\tR\n" +
	"activityId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x124\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1c.fitglue.PendingInput.StatusR\x06status\x12'\n" +
	"\x0frequired_fields\x18\x04 \x03(\tR\x0erequiredFields\x12C\n" +
	"\n" +
	"input_data\x18\x05 \x03(\v2$.fitglue.PendingInput.InputDataEntryR\tinputData\x12C\n" +
	"\x10original_payload\x18\x06 \x01(\v2\x18.fitglue.ActivityPayloadR\x0foriginalPayload\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x1a<\n" +
	"\x0eInputDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_WAITING\x10\x01\x12\x14\n" +
	"\x10STATUS_COMPLETED\x10\x02B7Z5github.com/ripixel/fitglue-server/src/go/pkg/types/pbb\x06proto3"

var (
	file_pending_input_proto_rawDescOnce sync.Once
	file_pending_input_proto_rawDescData []byte
)

func file_pending_input_proto_rawDescGZIP() []byte {
	file_pending_input_proto_rawDescOnce.Do(func() {
		file_pending_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pending_input_proto_rawDesc), len(file_pending_input_proto_rawDesc)))
	})
	return file_pending_input_proto_rawDescData
}

var file_pending_input_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pending_input_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pending_input_proto_goTypes = []any{
	(PendingInput_Status)(0),    // 0: fitglue.PendingInput.Status
	(*PendingInput)(nil),        // 1: fitglue.PendingInput
	nil,                         // 2: fitglue.PendingInput.InputDataEntry
	(*ActivityPayload)(nil),     // 3: fitglue.ActivityPayload
	(*timestamp.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_pending_input_proto_depIdxs = []int32{
	0, // 0: fitglue.PendingInput.status:type_name -> fitglue.PendingInput.Status
	2, // 1: fitglue.PendingInput.input_data:type_name -> fitglue.PendingInput.InputDataEntry
	3, // 2: fitglue.PendingInput.original_payload:type_name -> fitglue.ActivityPayload
	4, // 3: fitglue.PendingInput.created_at:type_name -> google.protobuf.Timestamp
	4, // 4: fitglue.PendingInput.updated_at:type_name -> google.protobuf.Timestamp
	4, // 5: fitglue.PendingInput.completed_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pending_input_proto_init() }
func file_pending_input_proto_init() {
	if File_pending_input_proto != nil {
		return
	}
	file_activity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pending_input_proto_rawDesc), len(file_pending_input_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pending_input_proto_goTypes,
		DependencyIndexes: file_pending_input_proto_depIdxs,
		EnumInfos:         file_pending_input_proto_enumTypes,
		MessageInfos:      file_pending_input_proto_msgTypes,
	}.Build()
	File_pending_input_proto = out.File
	file_pending_input_proto_goTypes = nil
	file_pending_input_proto_depIdxs = nil
}
