// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: uploaded_activity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UploadedActivityRecord tracks activities we've uploaded to destinations.
// Used for loop prevention: when a webhook comes back, we check if we just uploaded it.
type UploadedActivityRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Composite ID: "{source}:{external_id}" for efficient lookup
	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Activity identification
	Source     ActivitySource         `protobuf:"varint,3,opt,name=source,proto3,enum=fitglue.ActivitySource" json:"source,omitempty"` // Where the activity originally came from
	ExternalId string                 `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`    // External ID on the source platform
	StartTime  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`       // Activity start time for deduplication
	// Destination info
	Destination   Destination `protobuf:"varint,6,opt,name=destination,proto3,enum=fitglue.events.Destination" json:"destination,omitempty"` // Where we uploaded it
	DestinationId string      `protobuf:"bytes,7,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`         // ID on the destination platform
	// Timestamp for TTL-based cleanup
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadedActivityRecord) Reset() {
	*x = UploadedActivityRecord{}
	mi := &file_uploaded_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadedActivityRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadedActivityRecord) ProtoMessage() {}

func (x *UploadedActivityRecord) ProtoReflect() protoreflect.Message {
	mi := &file_uploaded_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadedActivityRecord.ProtoReflect.Descriptor instead.
func (*UploadedActivityRecord) Descriptor() ([]byte, []int) {
	return file_uploaded_activity_proto_rawDescGZIP(), []int{0}
}

func (x *UploadedActivityRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadedActivityRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadedActivityRecord) GetSource() ActivitySource {
	if x != nil {
		return x.Source
	}
	return ActivitySource_SOURCE_UNKNOWN
}

func (x *UploadedActivityRecord) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *UploadedActivityRecord) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *UploadedActivityRecord) GetDestination() Destination {
	if x != nil {
		return x.Destination
	}
	return Destination_DESTINATION_UNSPECIFIED
}

func (x *UploadedActivityRecord) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *UploadedActivityRecord) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

var File_uploaded_activity_proto protoreflect.FileDescriptor

const file_uploaded_activity_proto_rawDesc = "" +
	"\n" +
	"\x17uploaded_activity.proto\x12\afitglue\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0eactivity.proto\x1a\fevents.proto\"\xf1\x02\n" +
	"\x16UploadedActivityRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12/\n" +
	"\x06source\x18\x03 \x01(\x0e2\x17.fitglue.ActivitySourceR\x06source\x12\x1f\n" +
	"\vexternal_id\x18\x04 \x01(\tR\n" +
	"externalId\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12=\n" +
	"\vdestination\x18\x06 \x01(\x0e2\x1b.fitglue.events.DestinationR\vdestination\x12%\n" +
	"\x0edestination_id\x18\a \x01(\tR\rdestinationId\x12;\n" +
	"\vuploaded_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAtB/Z-github.com/fitglue/server/src/go/pkg/types/pbb\x06proto3"

var (
	file_uploaded_activity_proto_rawDescOnce sync.Once
	file_uploaded_activity_proto_rawDescData []byte
)

func file_uploaded_activity_proto_rawDescGZIP() []byte {
	file_uploaded_activity_proto_rawDescOnce.Do(func() {
		file_uploaded_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_uploaded_activity_proto_rawDesc), len(file_uploaded_activity_proto_rawDesc)))
	})
	return file_uploaded_activity_proto_rawDescData
}

var file_uploaded_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_uploaded_activity_proto_goTypes = []any{
	(*UploadedActivityRecord)(nil), // 0: fitglue.UploadedActivityRecord
	(ActivitySource)(0),            // 1: fitglue.ActivitySource
	(*timestamppb.Timestamp)(nil),  // 2: google.protobuf.Timestamp
	(Destination)(0),               // 3: fitglue.events.Destination
}
var file_uploaded_activity_proto_depIdxs = []int32{
	1, // 0: fitglue.UploadedActivityRecord.source:type_name -> fitglue.ActivitySource
	2, // 1: fitglue.UploadedActivityRecord.start_time:type_name -> google.protobuf.Timestamp
	3, // 2: fitglue.UploadedActivityRecord.destination:type_name -> fitglue.events.Destination
	2, // 3: fitglue.UploadedActivityRecord.uploaded_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_uploaded_activity_proto_init() }
func file_uploaded_activity_proto_init() {
	if File_uploaded_activity_proto != nil {
		return
	}
	file_activity_proto_init()
	file_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_uploaded_activity_proto_rawDesc), len(file_uploaded_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_uploaded_activity_proto_goTypes,
		DependencyIndexes: file_uploaded_activity_proto_depIdxs,
		MessageInfos:      file_uploaded_activity_proto_msgTypes,
	}.Build()
	File_uploaded_activity_proto = out.File
	file_uploaded_activity_proto_goTypes = nil
	file_uploaded_activity_proto_depIdxs = nil
}
