// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: user.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRecord struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	UserId       string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt    *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Integrations *UserIntegrations      `protobuf:"bytes,3,opt,name=integrations,proto3" json:"integrations,omitempty"`
	// Map of ActivitySource name (e.g. "SOURCE_HEVY") to enrichment rules
	Enrichments   map[string]*SourceEnrichmentConfig `protobuf:"bytes,4,rep,name=enrichments,proto3" json:"enrichments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRecord) Reset() {
	*x = UserRecord{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRecord) ProtoMessage() {}

func (x *UserRecord) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRecord.ProtoReflect.Descriptor instead.
func (*UserRecord) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRecord) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserRecord) GetIntegrations() *UserIntegrations {
	if x != nil {
		return x.Integrations
	}
	return nil
}

func (x *UserRecord) GetEnrichments() map[string]*SourceEnrichmentConfig {
	if x != nil {
		return x.Enrichments
	}
	return nil
}

type UserIntegrations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hevy          *HevyIntegration       `protobuf:"bytes,1,opt,name=hevy,proto3" json:"hevy,omitempty"`
	Fitbit        *FitbitIntegration     `protobuf:"bytes,2,opt,name=fitbit,proto3" json:"fitbit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIntegrations) Reset() {
	*x = UserIntegrations{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIntegrations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIntegrations) ProtoMessage() {}

func (x *UserIntegrations) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIntegrations.ProtoReflect.Descriptor instead.
func (*UserIntegrations) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserIntegrations) GetHevy() *HevyIntegration {
	if x != nil {
		return x.Hevy
	}
	return nil
}

func (x *UserIntegrations) GetFitbit() *FitbitIntegration {
	if x != nil {
		return x.Fitbit
	}
	return nil
}

type HevyIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HevyIntegration) Reset() {
	*x = HevyIntegration{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HevyIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HevyIntegration) ProtoMessage() {}

func (x *HevyIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HevyIntegration.ProtoReflect.Descriptor instead.
func (*HevyIntegration) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *HevyIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *HevyIntegration) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *HevyIntegration) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FitbitIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	FitbitUserId  string                 `protobuf:"bytes,5,opt,name=fitbit_user_id,json=fitbitUserId,proto3" json:"fitbit_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FitbitIntegration) Reset() {
	*x = FitbitIntegration{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FitbitIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FitbitIntegration) ProtoMessage() {}

func (x *FitbitIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FitbitIntegration.ProtoReflect.Descriptor instead.
func (*FitbitIntegration) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *FitbitIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FitbitIntegration) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *FitbitIntegration) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *FitbitIntegration) GetExpiresAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *FitbitIntegration) GetFitbitUserId() string {
	if x != nil {
		return x.FitbitUserId
	}
	return ""
}

type SourceEnrichmentConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrichers     []*EnricherConfig      `protobuf:"bytes,1,rep,name=enrichers,proto3" json:"enrichers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceEnrichmentConfig) Reset() {
	*x = SourceEnrichmentConfig{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceEnrichmentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceEnrichmentConfig) ProtoMessage() {}

func (x *SourceEnrichmentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceEnrichmentConfig.ProtoReflect.Descriptor instead.
func (*SourceEnrichmentConfig) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *SourceEnrichmentConfig) GetEnrichers() []*EnricherConfig {
	if x != nil {
		return x.Enrichers
	}
	return nil
}

type EnricherConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                               // e.g. "ai-description", "fitbit-hr"
	Inputs        map[string]string      `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g. {"prompt_style": "funny", "priority": "high"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnricherConfig) Reset() {
	*x = EnricherConfig{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnricherConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnricherConfig) ProtoMessage() {}

func (x *EnricherConfig) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnricherConfig.ProtoReflect.Descriptor instead.
func (*EnricherConfig) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *EnricherConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnricherConfig) GetInputs() map[string]string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\afitglue\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x02\n" +
	"\n" +
	"UserRecord\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fintegrations\x18\x03 \x01(\v2\x19.fitglue.UserIntegrationsR\fintegrations\x12F\n" +
	"\venrichments\x18\x04 \x03(\v2$.fitglue.UserRecord.EnrichmentsEntryR\venrichments\x1a_\n" +
	"\x10EnrichmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.fitglue.SourceEnrichmentConfigR\x05value:\x028\x01\"t\n" +
	"\x10UserIntegrations\x12,\n" +
	"\x04hevy\x18\x01 \x01(\v2\x18.fitglue.HevyIntegrationR\x04hevy\x122\n" +
	"\x06fitbit\x18\x02 \x01(\v2\x1a.fitglue.FitbitIntegrationR\x06fitbit\"]\n" +
	"\x0fHevyIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\xd6\x01\n" +
	"\x11FitbitIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12$\n" +
	"\x0efitbit_user_id\x18\x05 \x01(\tR\ffitbitUserId\"O\n" +
	"\x16SourceEnrichmentConfig\x125\n" +
	"\tenrichers\x18\x01 \x03(\v2\x17.fitglue.EnricherConfigR\tenrichers\"\x9c\x01\n" +
	"\x0eEnricherConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\x06inputs\x18\x02 \x03(\v2#.fitglue.EnricherConfig.InputsEntryR\x06inputs\x1a9\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x17Z\x15fitglue/pkg/shared/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_proto_goTypes = []any{
	(*UserRecord)(nil),             // 0: fitglue.UserRecord
	(*UserIntegrations)(nil),       // 1: fitglue.UserIntegrations
	(*HevyIntegration)(nil),        // 2: fitglue.HevyIntegration
	(*FitbitIntegration)(nil),      // 3: fitglue.FitbitIntegration
	(*SourceEnrichmentConfig)(nil), // 4: fitglue.SourceEnrichmentConfig
	(*EnricherConfig)(nil),         // 5: fitglue.EnricherConfig
	nil,                            // 6: fitglue.UserRecord.EnrichmentsEntry
	nil,                            // 7: fitglue.EnricherConfig.InputsEntry
	(*timestamp.Timestamp)(nil),    // 8: google.protobuf.Timestamp
}
var file_user_proto_depIdxs = []int32{
	8, // 0: fitglue.UserRecord.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: fitglue.UserRecord.integrations:type_name -> fitglue.UserIntegrations
	6, // 2: fitglue.UserRecord.enrichments:type_name -> fitglue.UserRecord.EnrichmentsEntry
	2, // 3: fitglue.UserIntegrations.hevy:type_name -> fitglue.HevyIntegration
	3, // 4: fitglue.UserIntegrations.fitbit:type_name -> fitglue.FitbitIntegration
	8, // 5: fitglue.FitbitIntegration.expires_at:type_name -> google.protobuf.Timestamp
	5, // 6: fitglue.SourceEnrichmentConfig.enrichers:type_name -> fitglue.EnricherConfig
	7, // 7: fitglue.EnricherConfig.inputs:type_name -> fitglue.EnricherConfig.InputsEntry
	4, // 8: fitglue.UserRecord.EnrichmentsEntry.value:type_name -> fitglue.SourceEnrichmentConfig
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
