// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: waitlist.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WaitlistEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // e.g. "web"
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitlistEntry) Reset() {
	*x = WaitlistEntry{}
	mi := &file_waitlist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitlistEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitlistEntry) ProtoMessage() {}

func (x *WaitlistEntry) ProtoReflect() protoreflect.Message {
	mi := &file_waitlist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitlistEntry.ProtoReflect.Descriptor instead.
func (*WaitlistEntry) Descriptor() ([]byte, []int) {
	return file_waitlist_proto_rawDescGZIP(), []int{0}
}

func (x *WaitlistEntry) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *WaitlistEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *WaitlistEntry) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WaitlistEntry) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *WaitlistEntry) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

var File_waitlist_proto protoreflect.FileDescriptor

const file_waitlist_proto_rawDesc = "" +
	"\n" +
	"\x0ewaitlist.proto\x12\afitglue\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x01\n" +
	"\rWaitlistEntry\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ipB\x17Z\x15fitglue/pkg/shared/pbb\x06proto3"

var (
	file_waitlist_proto_rawDescOnce sync.Once
	file_waitlist_proto_rawDescData []byte
)

func file_waitlist_proto_rawDescGZIP() []byte {
	file_waitlist_proto_rawDescOnce.Do(func() {
		file_waitlist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_waitlist_proto_rawDesc), len(file_waitlist_proto_rawDesc)))
	})
	return file_waitlist_proto_rawDescData
}

var file_waitlist_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_waitlist_proto_goTypes = []any{
	(*WaitlistEntry)(nil),       // 0: fitglue.WaitlistEntry
	(*timestamp.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_waitlist_proto_depIdxs = []int32{
	1, // 0: fitglue.WaitlistEntry.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_waitlist_proto_init() }
func file_waitlist_proto_init() {
	if File_waitlist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_waitlist_proto_rawDesc), len(file_waitlist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waitlist_proto_goTypes,
		DependencyIndexes: file_waitlist_proto_depIdxs,
		MessageInfos:      file_waitlist_proto_msgTypes,
	}.Build()
	File_waitlist_proto = out.File
	file_waitlist_proto_goTypes = nil
	file_waitlist_proto_depIdxs = nil
}
